# Grand Challenge Accenture Notebook

## Initialization

<div style="display:flex; align-items:center;">
  <hr style="flex:1;">
  <span style="padding:0 10px;"><b>Import libraries</b></span>
  <hr style="flex:1;">
</div>

In [241]:
# initials
import pandas as pd
from pathlib import Path
import os
import numpy as np
import statsmodels.api as sm
import sqlite3
import matplotlib.pyplot as plt
import geopandas as gpd

# plotting
import plotly.graph_objects as go
import tempfile
from playwright.async_api import TimeoutError as PlaywrightTimeoutError, async_playwright
import glob
from plotly.subplots import make_subplots

<div style="display:flex; align-items:center;">
  <hr style="flex:1;">
  <span style="padding:0 10px;"><b>Paths initializtion</b></span>
  <hr style="flex:1;">
</div>

In [242]:
data_folder = Path("Data/")
data_folder.mkdir(parents=True, exist_ok=True)

raw_dir = data_folder / "Raw"
raw_dir.mkdir(parents=True, exist_ok=True)

derived_dir = data_folder / "Derived"
derived_dir.mkdir(parents=True, exist_ok=True)

assets_dir = Path("Assets/")
assets_dir.mkdir(parents=True, exist_ok=True)

graphs_dir = assets_dir / "Graphs"
graphs_dir.mkdir(parents=True, exist_ok=True)

<div style="display:flex; align-items:center;">
  <hr style="flex:1;">
  <span style="padding:0 10px;"><b>Import Raw data</b></span>
  <hr style="flex:1;">
</div>

In [243]:
csv_paths = sorted(raw_dir.glob("*.csv"))

# Keep only Italy raw air-quality files and ignore other CSVs (e.g., population.csv).
it_csv_paths = [path for path in csv_paths if path.name.endswith("_IT.csv")]

dfs = {}
for path in it_csv_paths:
    name = path.stem
    df = pd.read_csv(path)
    dfs[name] = df
    
dfs_pop = {}
for path in it_csv_paths:
    name = path.stem
    df = pd.read_csv(path)
    dfs_pop[name] = df

dfs_industry = {}
path = "Data/Derived/2023_IT_industrial_derived.csv"
name = "2023_IT_industrial_derived"
df = pd.read_csv(path)
dfs_industry[name] = df

dfs_pie = {}
path1 = "Data/Raw/IT_industrial_area.csv"
path2 = "Data/Raw/IT_urban_green_area.csv"
name1 = "IT_industrial_area"
name2 = "IT_urban_green_area"
df = pd.read_csv(path1)
dfs_pie[name1] = df
df = pd.read_csv(path2)
dfs_pie[name2] = df

## Data validation

<div style="display:flex; align-items:center;">
  <hr style="flex:1;">
  <span style="padding:0 10px;"><b>Integrity check</b></span>
  <hr style="flex:1;">
</div>

In [244]:
def check_dataset_integrity(file_list):
 
    EXPECTED_COLUMNS = dfs[csv_paths[0].stem].columns.tolist() if csv_paths else []

    NUMERIC_COLUMNS = [
        col for col in EXPECTED_COLUMNS if pd.api.types.is_numeric_dtype(dfs[csv_paths[0].stem][col])
    ]

    report = {}

    for file_name in file_list:
        full_path = raw_dir / file_name
        if not os.path.exists(full_path):
            report[file_name] = ["Error: File not found"]
            continue
            
        issues = []
        try:
            
            df_headers = pd.read_csv(full_path, nrows=0)
            actual_columns = list(df_headers.columns)

           
            if actual_columns != EXPECTED_COLUMNS:
                missing = set(EXPECTED_COLUMNS) - set(actual_columns)
                extra = set(actual_columns) - set(EXPECTED_COLUMNS)
                if missing: issues.append(f"Missing columns: {missing}")
                if extra: issues.append(f"Unexpected columns: {extra}")
                if not missing and not extra:
                    issues.append("Column order is inconsistent with the standard schema.")

            
            df = pd.read_csv(full_path)
            
            for col in NUMERIC_COLUMNS:
                if col in df.columns:
                    
                    invalid_mask = pd.to_numeric(df[col], errors='coerce').isna() & df[col].notna()
                    error_count = invalid_mask.sum()
                    if error_count > 0:
                        issues.append(f"Format Error: Column '{col}' has {error_count} non-numeric values.")

           
            if 'Year' in df.columns:
                
                try:
                    expected_year = int(os.path.basename(file_name).split('_')[0])
                    wrong_years = df[df['Year'] != expected_year]['Year'].unique()
                    if len(wrong_years) > 0:
                        issues.append(f"Data Consistency: Found years {wrong_years} in a {expected_year} file.")
                except ValueError:
                    pass 

            report[file_name] = issues if issues else ["Integrity Check Passed"]

        except Exception as e:
            report[file_name] = [f"Critical Error: {str(e)}"]

    return report

files_to_check = [
    "2023_NO2_IT.csv", "2023_O3_IT.csv", "2023_PM10_IT.csv", "2023_PM25_IT.csv",
    "2024_NO2_IT.csv", "2024_O3_IT.csv", "2024_PM10_IT.csv", "2024_PM25_IT.csv"
]

validation_results = check_dataset_integrity(files_to_check)

print(f"{'File Name':<20} | Status/Issues")
print("-" * 60)
for file, logs in validation_results.items():
    print(f"{file:<20} | {logs[0]}")
    for log in logs[1:]:
        print(f"{'':<20} | {log}")

File Name            | Status/Issues
------------------------------------------------------------
2023_NO2_IT.csv      | Integrity Check Passed
2023_O3_IT.csv       | Integrity Check Passed
2023_PM10_IT.csv     | Integrity Check Passed
2023_PM25_IT.csv     | Integrity Check Passed
2024_NO2_IT.csv      | Integrity Check Passed
2024_O3_IT.csv       | Integrity Check Passed
2024_PM10_IT.csv     | Integrity Check Passed
2024_PM25_IT.csv     | Integrity Check Passed

<div style="display:flex; align-items:center;">
  <hr style="flex:1;">
  <span style="padding:0 10px;"><b>Data overlay</b></span>
  <hr style="flex:1;">
</div>

In [245]:
# visualizing data structure, content snippet, and information for each column in the dataset, for each file present in the Data directory

for name, df in dfs.items():
    print(f"\n=== {name} ===")
    display(df.head())
    df.info()
    display(df.describe(include="all"))
    display(df.isnull().sum())

=== 2023_NO2_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2040A,CENQU1,SPO.IT2040A_8_chemi_2011-05-19_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hr-max-per99.79,1 year 99.79 %ile of hourly values in a given ...,...,9.1881,39.2328,8.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:03:38,https://eeadmz1batchservice02.blob.core.window...,hour
1,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2008A,CESGI1,SPO.IT2008A_8_chemi_2011-02-17_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hr-min,1 year hour min,...,8.6053,39.8853,4.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:03:46,https://eeadmz1batchservice02.blob.core.window...,hour
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2040A,CENQU1,SPO.IT2040A_8_chemi_2011-05-19_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hrsAbove200,1 year hour exceed 200,...,9.1881,39.2328,8.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:08,https://eeadmz1batchservice02.blob.core.window...,hour
3,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_8_chemi_2011-02-04_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hr-max,1 year hour max,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:03:19,https://eeadmz1batchservice02.blob.core.window...,hour
4,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_8_chemi_2011-02-04_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hrsAbove150,1 year hour exceed 150,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:00,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 11951 entries, 0 to 11950
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         11951 non-null  str
 1   Air Quality Network                                             11951 non-null  str
 2   Air Quality Network Name                                        11951 non-null  str
 3   Air Quality Station EoI Code                                    11951 non-null  str
 4   Air Quality Station Name                                        11951 non-null  str
 5   Sampling Point Id                                               11951 non-null  str
 6   Air Pollutant                                                   11951 non-null  str
 7   Air Pollutant Description                                       11951 non-null  str
 8   Data Aggregation Process Id                                     11951 non-null  str
 9   Data Aggregation Process                                        11951 non-null  str
 10  Year                                                            11951 non-null  int64
 11  Air Pollution Level                                             11951 non-null  float64
 12  Unit Of Air Pollution Level                                     11951 non-null  str
 13  Data Coverage                                                   11951 non-null  float64
 14  Verification                                                    11951 non-null  int64
 15  Air Quality Station Type                                        11951 non-null  str
 16  Air Quality Station Area                                        11951 non-null  str
 17  Longitude                                                       11951 non-null  float64
 18  Latitude                                                        11951 non-null  float64
 19  Altitude                                                        11951 non-null  float64
 20  City                                                            4598 non-null   str
 21  City Code                                                       4598 non-null   str
 22  City Population                                                 4598 non-null   float64
 23  Source Of Data Flow                                             11951 non-null  str
 24  Calculation Time                                                11951 non-null  str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  11951 non-null  str
 26  Observation Frequency                                           11951 non-null  str
dtypes: float64(6), int64(2), str(19)
memory usage: 2.5 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,11951,11951,11951,11951,11951,11951,11951,11951,11951,11951,...,11951.000000,11951.000000,11951.000000,4598,4598,4.598000e+03,11951,11951,11951,11951
unique,1,58,58,629,629,629,1,1,19,19,...,NaN,NaN,NaN,78,78,NaN,1,19,629,1
top,Italy,NET.IT112A,Regione Lazio,IT2040A,CENQU1,SPO.IT2040A_8_chemi_2011-05-19_00:00:00,NO2,Nitrogen dioxide (air),P1Y-hr-max-per99.79,1 year 99.79 %ile of hourly values in a given ...,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:03:38,https://eeadmz1batchservice02.blob.core.window...,hour
freq,11951,1026,1026,19,19,19,11951,11951,629,629,...,NaN,NaN,NaN,342,342,NaN,11951,629,19,11951
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.031678,42.979061,181.781876,NaN,NaN,7.529412e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.725990,2.550565,257.400108,NaN,NaN,1.176173e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.835900,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.666900,40.990500,20.000000,NaN,NaN,9.255000e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.902200,43.738900,80.000000,NaN,NaN,1.540110e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.137800,45.248900,234.000000,NaN,NaN,5.657520e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.176700,46.797400,1770.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                  0
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              7353
City Code                                                         7353
City Population                                                   7353
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                                0
dtype: int64

=== 2023_O3_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),AOT40f,AOT40 for forest protection,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 22:18:33,https://eeadmz1batchservice02.blob.core.window...,hour
1,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2009A,CENS16,SPO.IT2009A_7_UV-P_2012-01-01_00:00:00,O3,Ozone (air),P1Y-dmax-per95.07,1 year 95.07 percentile daily 8h maximum,...,8.5761,40.7244,275.0,Sassari ...,IT026C1 ...,125273.0,E1a/validated data AQ e-Reporting,10/02/2026 23:02:59,https://eeadmz1batchservice02.blob.core.window...,hour
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2009A,CENS16,SPO.IT2009A_7_UV-P_2012-01-01_00:00:00,O3,Ozone (air),P1Y-hr-min,1 year hour min,...,8.5761,40.7244,275.0,Sassari ...,IT026C1 ...,125273.0,E1a/validated data AQ e-Reporting,10/02/2026 23:03:46,https://eeadmz1batchservice02.blob.core.window...,hour
3,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2040A,CENQU1,SPO.IT2040A_7_UV-P_2011-05-19_00:00:00,O3,Ozone (air),AOT40fmeasured,AOT40 vegetation protection,...,9.1881,39.2328,8.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 22:18:37,https://eeadmz1batchservice02.blob.core.window...,hour
4,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2072A,BADIA POLESINE,SPO.IT2072A_7_UV-P_2011-01-01_00:00:00,O3,Ozone (air),AOT40cmeasured,AOT40c UNCORRECTED for data capture,...,11.5533,45.1039,6.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 22:18:26,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 10077 entries, 0 to 10076
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         10077 non-null  str
 1   Air Quality Network                                             10077 non-null  str
 2   Air Quality Network Name                                        10077 non-null  str
 3   Air Quality Station EoI Code                                    10077 non-null  str
 4   Air Quality Station Name                                        10077 non-null  str
 5   Sampling Point Id                                               10077 non-null  str
 6   Air Pollutant                                                   10077 non-null  str
 7   Air Pollutant Description                                       10077 non-null  str
 8   Data Aggregation Process Id                                     10077 non-null  str
 9   Data Aggregation Process                                        10077 non-null  str
 10  Year                                                            10077 non-null  int64
 11  Air Pollution Level                                             10049 non-null  float64
 12  Unit Of Air Pollution Level                                     10077 non-null  str
 13  Data Coverage                                                   10077 non-null  float64
 14  Verification                                                    10077 non-null  int64
 15  Air Quality Station Type                                        10077 non-null  str
 16  Air Quality Station Area                                        10077 non-null  str
 17  Longitude                                                       10077 non-null  float64
 18  Latitude                                                        10077 non-null  float64
 19  Altitude                                                        10077 non-null  float64
 20  City                                                            3277 non-null   str
 21  City Code                                                       3277 non-null   str
 22  City Population                                                 3277 non-null   float64
 23  Source Of Data Flow                                             10077 non-null  str
 24  Calculation Time                                                10077 non-null  str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  10052 non-null  str
 26  Observation Frequency                                           10077 non-null  str
dtypes: float64(6), int64(2), str(19)
memory usage: 2.1 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,10077,10077,10077,10077,10077,10077,10077,10077,10077,10077,...,10077.000000,10077.000000,10077.000000,3277,3277,3.277000e+03,10077,10077,10052,10077
unique,1,54,54,348,348,348,1,1,29,28,...,NaN,NaN,NaN,70,70,NaN,2,29,348,1
top,Italy,NET.IT255A,RETE REGIONALE DI QUALITÀ DELL'ARIA DELLA REGI...,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-dmax-per95.07,AOT40 vegetation protection,...,NaN,NaN,NaN,Roma ...,IT001C1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:59,https://eeadmz1batchservice02.blob.core.window...,hour
freq,10077,986,986,29,29,29,10077,10077,348,692,...,NaN,NaN,NaN,261,261,NaN,10052,348,29,10077
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.952978,43.157442,235.143485,NaN,NaN,7.916427e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.631557,2.628911,318.905158,NaN,NaN,1.217241e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.977800,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.566400,41.067100,28.000000,NaN,NaN,8.446500e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.944000,44.095800,114.000000,NaN,NaN,1.270370e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.855000,45.463300,273.000000,NaN,NaN,5.657520e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.173600,46.797400,1770.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                 28
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              6800
City Code                                                         6800
City Population                                                   6800
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)      25
Observation Frequency                                                0
dtype: int64

=== 2023_PM10_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2008A,CESGI1,SPO.IT2008A_5_BETA_2011-02-17_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-P1D-per95.07,1 year 95.07 percentile of daily means (P1D) o...,...,8.6053,39.8853,4.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:38,https://eeadmz1batchservice02.blob.core.window...,day
1,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2071A,ALTA PADOVANA,SPO.IT2071A_5_gravi_2011-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,11.9022,45.6003,25.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,day
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_5_BETA_2012-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y,Annual mean / 1 calendar year,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:07,https://eeadmz1batchservice02.blob.core.window...,day
3,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_5_BETA_2012-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-3daysAbove90,3 consecutive days in exceedance of 90,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:21,https://eeadmz1batchservice02.blob.core.window...,day
4,Italy,NET.IT282A,RETE REGIONALE QUALIT� ARIA AMBIENTE,IT0459A,CHIARAVALLE2,SPO.IT0459A_5_BETA_2006-02-20_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y,Annual mean / 1 calendar year,...,13.3419,43.5989,15.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:07,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 8228 entries, 0 to 8227
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         8228 non-null   str
 1   Air Quality Network                                             8228 non-null   str
 2   Air Quality Network Name                                        8228 non-null   str
 3   Air Quality Station EoI Code                                    8228 non-null   str
 4   Air Quality Station Name                                        8228 non-null   str
 5   Sampling Point Id                                               8228 non-null   str
 6   Air Pollutant                                                   8228 non-null   str
 7   Air Pollutant Description                                       8228 non-null   str
 8   Data Aggregation Process Id                                     8228 non-null   str
 9   Data Aggregation Process                                        8228 non-null   str
 10  Year                                                            8228 non-null   int64
 11  Air Pollution Level                                             8228 non-null   float64
 12  Unit Of Air Pollution Level                                     8228 non-null   str
 13  Data Coverage                                                   8228 non-null   float64
 14  Verification                                                    8228 non-null   int64
 15  Air Quality Station Type                                        8228 non-null   str
 16  Air Quality Station Area                                        8228 non-null   str
 17  Longitude                                                       8228 non-null   float64
 18  Latitude                                                        8228 non-null   float64
 19  Altitude                                                        8228 non-null   float64
 20  City                                                            3223 non-null   str
 21  City Code                                                       3223 non-null   str
 22  City Population                                                 3223 non-null   float64
 23  Source Of Data Flow                                             8228 non-null   str
 24  Calculation Time                                                8228 non-null   str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  8228 non-null   str
 26  Observation Frequency                                           8228 non-null   str
dtypes: float64(6), int64(2), str(19)
memory usage: 1.7 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,8228,8228,8228,8228,8228,8228,8228,8228,8228,8228,...,8228.000000,8228.000000,8228.000000,3223,3223,3.223000e+03,8228,8228,8228,8228
unique,1,60,60,569,569,569,1,1,17,17,...,NaN,NaN,NaN,77,77,NaN,1,17,569,3
top,Italy,NET.IT250A,RETE REGIONALE DI RILEVAMENTO DELLA QUALITA' D...,IT0459A,CHIARAVALLE2,SPO.IT0459A_5_BETA_2006-02-20_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y,Annual mean / 1 calendar year,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:07,https://eeadmz1batchservice02.blob.core.window...,day
freq,8228,723,723,17,17,17,8228,8228,569,569,...,NaN,NaN,NaN,232,232,NaN,8228,569,17,6146
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.216315,42.905639,166.760598,NaN,NaN,6.782997e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.703116,2.574691,236.697413,NaN,NaN,1.093863e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.835900,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.870600,40.927500,17.000000,NaN,NaN,9.327500e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.245800,43.568900,68.000000,NaN,NaN,1.570170e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.197500,45.183600,221.000000,NaN,NaN,3.954160e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.176700,46.797400,1639.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                  0
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              5005
City Code                                                         5005
City Population                                                   5005
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                                0
dtype: int64

=== 2023_PM25_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_6001_BETA_2012-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-P1D-per95.07,1 year 95.07 percentile of daily means (P1D) o...,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:38,https://eeadmz1batchservice02.blob.core.window...,day
1,Italy,NET.IT282A,RETE REGIONALE QUALIT� ARIA AMBIENTE,IT0459A,CHIARAVALLE2,SPO.IT0459A_6001_BETA_2006-02-20_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,13.3419,43.5989,15.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
2,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2319A,VE - Rio Novo,SPO.IT2319A_6001_gravi_2018-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-day-max,1 year day max,...,12.3231,45.4356,1.0,Venezia ...,IT011C1 ...,258685.0,E1a/validated data AQ e-Reporting,10/02/2026 23:01:43,https://eeadmz1batchservice02.blob.core.window...,day
3,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2319A,VE - Rio Novo,SPO.IT2319A_6001_gravi_2018-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-P1D-per99,1 year 99 percentile of daily means (P1D) or ....,...,12.3231,45.4356,1.0,Venezia ...,IT011C1 ...,258685.0,E1a/validated data AQ e-Reporting,10/02/2026 23:04:44,https://eeadmz1batchservice02.blob.core.window...,day
4,Italy,NET.IT282A,RETE REGIONALE QUALIT� ARIA AMBIENTE,IT0461A,FALCONARA SCUOLA,SPO.IT0461A_6001_BETA_2005-11-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-daysAbove25,1 year day exceed 25,...,13.3875,43.6333,10.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:27,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 3573 entries, 0 to 3572
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         3573 non-null   str
 1   Air Quality Network                                             3573 non-null   str
 2   Air Quality Network Name                                        3573 non-null   str
 3   Air Quality Station EoI Code                                    3573 non-null   str
 4   Air Quality Station Name                                        3573 non-null   str
 5   Sampling Point Id                                               3573 non-null   str
 6   Air Pollutant                                                   3573 non-null   str
 7   Air Pollutant Description                                       3573 non-null   str
 8   Data Aggregation Process Id                                     3573 non-null   str
 9   Data Aggregation Process                                        3573 non-null   str
 10  Year                                                            3573 non-null   int64
 11  Air Pollution Level                                             3573 non-null   float64
 12  Unit Of Air Pollution Level                                     3573 non-null   str
 13  Data Coverage                                                   3573 non-null   float64
 14  Verification                                                    3573 non-null   int64
 15  Air Quality Station Type                                        3573 non-null   str
 16  Air Quality Station Area                                        3573 non-null   str
 17  Longitude                                                       3573 non-null   float64
 18  Latitude                                                        3573 non-null   float64
 19  Altitude                                                        3573 non-null   float64
 20  City                                                            1526 non-null   str
 21  City Code                                                       1526 non-null   str
 22  City Population                                                 1526 non-null   float64
 23  Source Of Data Flow                                             3573 non-null   str
 24  Calculation Time                                                3573 non-null   str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  3573 non-null   str
 26  Observation Frequency                                           3573 non-null   str
dtypes: float64(6), int64(2), str(19)
memory usage: 753.8 KB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,3573,3573,3573,3573,3573,3573,3573,3573,3573,3573,...,3573.000000,3573.000000,3573.000000,1526,1526,1.526000e+03,3573,3573,3573,3573
unique,1,55,55,333,333,333,1,1,13,13,...,NaN,NaN,NaN,73,73,NaN,1,13,333,2
top,Italy,NET.IT116A,MONITORAGGIO AMBIENTALE DELLA REGIONE CAMPANIA...,IT0459A,CHIARAVALLE2,SPO.IT0459A_6001_BETA_2006-02-20_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-P1D-per95.07,1 year 95.07 percentile of daily means (P1D) o...,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:38,https://eeadmz1batchservice02.blob.core.window...,day
freq,3573,349,349,13,13,13,3573,3573,333,333,...,NaN,NaN,NaN,140,140,NaN,3573,333,13,2520
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.263229,43.015055,168.785894,NaN,NaN,7.028122e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.737342,2.338658,221.984073,NaN,NaN,1.112394e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.304300,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.880300,40.990500,17.000000,NaN,NaN,9.255000e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.468100,43.461100,72.000000,NaN,NaN,1.510050e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.213100,45.104100,233.000000,NaN,NaN,5.657520e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.176700,46.619500,1225.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                  0
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              2047
City Code                                                         2047
City Population                                                   2047
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                                0
dtype: int64

=== 2024_NO2_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2008A,CESGI1,SPO.IT2008A_8_chemi_2011-02-17_00:00:00,NO2,Nitrogen dioxide (air),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,8.6053,39.8853,4.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
1,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2040A,CENQU1,SPO.IT2040A_8_chemi_2011-05-19_00:00:00,NO2,Nitrogen dioxide (air),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,9.1881,39.2328,8.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2008A,CESGI1,SPO.IT2008A_8_chemi_2011-02-17_00:00:00,NO2,Nitrogen dioxide (air),P1Y-P1D-per99,1 year 99 percentile of daily means (P1D) or ....,...,8.6053,39.8853,4.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:44,https://eeadmz1batchservice02.blob.core.window...,hour
3,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_8_chemi_2011-02-04_00:00:00,NO2,Nitrogen dioxide (air),P1Y-3hAbove200,3 consecutive hours in exceedance of 200,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:25,https://eeadmz1batchservice02.blob.core.window...,hour
4,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_8_chemi_2011-02-04_00:00:00,NO2,Nitrogen dioxide (air),P1Y-day-min,1 year day min,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:04,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 11875 entries, 0 to 11874
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         11875 non-null  str
 1   Air Quality Network                                             11875 non-null  str
 2   Air Quality Network Name                                        11875 non-null  str
 3   Air Quality Station EoI Code                                    11875 non-null  str
 4   Air Quality Station Name                                        11875 non-null  str
 5   Sampling Point Id                                               11875 non-null  str
 6   Air Pollutant                                                   11875 non-null  str
 7   Air Pollutant Description                                       11875 non-null  str
 8   Data Aggregation Process Id                                     11875 non-null  str
 9   Data Aggregation Process                                        11875 non-null  str
 10  Year                                                            11875 non-null  int64
 11  Air Pollution Level                                             11856 non-null  float64
 12  Unit Of Air Pollution Level                                     11875 non-null  str
 13  Data Coverage                                                   11875 non-null  float64
 14  Verification                                                    11875 non-null  int64
 15  Air Quality Station Type                                        11875 non-null  str
 16  Air Quality Station Area                                        11875 non-null  str
 17  Longitude                                                       11875 non-null  float64
 18  Latitude                                                        11875 non-null  float64
 19  Altitude                                                        11875 non-null  float64
 20  City                                                            4522 non-null   str
 21  City Code                                                       4522 non-null   str
 22  City Population                                                 4522 non-null   float64
 23  Source Of Data Flow                                             11875 non-null  str
 24  Calculation Time                                                11875 non-null  str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  11875 non-null  str
 26  Observation Frequency                                           11875 non-null  str
dtypes: float64(6), int64(2), str(19)
memory usage: 2.4 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,11875,11875,11875,11875,11875,11875,11875,11875,11875,11875,...,11875.00000,11875.000000,11875.000000,4522,4522,4.522000e+03,11875,11875,11875,11875
unique,1,58,58,625,625,625,1,1,19,19,...,NaN,NaN,NaN,78,78,NaN,1,19,625,1
top,Italy,NET.IT112A,Regione Lazio,IT2008A,CESGI1,SPO.IT2008A_8_chemi_2011-02-17_00:00:00,NO2,Nitrogen dioxide (air),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
freq,11875,1007,1007,19,19,19,11875,11875,625,625,...,NaN,NaN,NaN,342,342,NaN,11875,625,19,11875
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.02466,42.975441,181.148480,NaN,NaN,7.632695e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.73077,2.552616,257.067642,NaN,NaN,1.183259e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.83590,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.61470,40.990500,20.000000,NaN,NaN,9.255000e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.90580,43.730600,80.000000,NaN,NaN,1.570170e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.13780,45.235000,233.000000,NaN,NaN,5.657520e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.17670,46.797400,1770.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                 19
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              7353
City Code                                                         7353
City Population                                                   7353
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                                0
dtype: int64

=== 2024_O3_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
1,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-dmaxAbove120,1 year daymax exceed 120,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:51,https://eeadmz1batchservice02.blob.core.window...,hour
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-dmax-per95.07,1 year 95.07 percentile daily 8h maximum,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:59,https://eeadmz1batchservice02.blob.core.window...,hour
3,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-dx-max,1 year day max max,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:03:11,https://eeadmz1batchservice02.blob.core.window...,hour
4,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2040A,CENQU1,SPO.IT2040A_7_UV-P_2011-05-19_00:00:00,O3,Ozone (air),AOT40c,AOT40 vegetation protection,...,9.1881,39.2328,8.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 22:18:22,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 10075 entries, 0 to 10074
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         10075 non-null  str
 1   Air Quality Network                                             10075 non-null  str
 2   Air Quality Network Name                                        10075 non-null  str
 3   Air Quality Station EoI Code                                    10075 non-null  str
 4   Air Quality Station Name                                        10075 non-null  str
 5   Sampling Point Id                                               10075 non-null  str
 6   Air Pollutant                                                   10075 non-null  str
 7   Air Pollutant Description                                       10075 non-null  str
 8   Data Aggregation Process Id                                     10075 non-null  str
 9   Data Aggregation Process                                        10075 non-null  str
 10  Year                                                            10075 non-null  int64
 11  Air Pollution Level                                             10032 non-null  float64
 12  Unit Of Air Pollution Level                                     10075 non-null  str
 13  Data Coverage                                                   10075 non-null  float64
 14  Verification                                                    10075 non-null  int64
 15  Air Quality Station Type                                        10075 non-null  str
 16  Air Quality Station Area                                        10075 non-null  str
 17  Longitude                                                       10075 non-null  float64
 18  Latitude                                                        10075 non-null  float64
 19  Altitude                                                        10075 non-null  float64
 20  City                                                            3240 non-null   str
 21  City Code                                                       3240 non-null   str
 22  City Population                                                 3240 non-null   float64
 23  Source Of Data Flow                                             10075 non-null  str
 24  Calculation Time                                                10075 non-null  str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  10061 non-null  str
 26  Observation Frequency                                           10075 non-null  str
dtypes: float64(6), int64(2), str(19)
memory usage: 2.1 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,10075,10075,10075,10075,10075,10075,10075,10075,10075,10075,...,10075.000000,10075.000000,10075.000000,3240,3240,3.240000e+03,10075,10075,10061,10075
unique,1,54,54,348,348,348,1,1,29,28,...,NaN,NaN,NaN,70,70,NaN,2,29,348,1
top,Italy,NET.IT255A,RETE REGIONALE DI QUALITÀ DELL'ARIA DELLA REGI...,IT2010A,CENPT1,SPO.IT2010A_7_NDIR_2012-01-01_00:00:00,O3,Ozone (air),P1Y-day-per50,AOT40 vegetation protection,...,NaN,NaN,NaN,Roma ...,IT001C1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
freq,10075,986,986,29,29,29,10075,10075,348,692,...,NaN,NaN,NaN,261,261,NaN,10061,348,29,10075
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.953988,43.160899,234.154035,NaN,NaN,7.993750e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.629801,2.629029,318.071324,NaN,NaN,1.222008e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.977800,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.566400,41.067100,28.000000,NaN,NaN,8.446500e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.961100,44.095800,114.000000,NaN,NaN,1.270370e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.855000,45.463300,273.000000,NaN,NaN,6.474220e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.173600,46.797400,1770.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                 43
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              6835
City Code                                                         6835
City Population                                                   6835
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)      14
Observation Frequency                                                0
dtype: int64

=== 2024_PM10_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2008A,CESGI1,SPO.IT2008A_5_BETA_2011-02-17_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-P1D-per99,1 year 99 percentile of daily means (P1D) or ....,...,8.6053,39.8853,4.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:44,https://eeadmz1batchservice02.blob.core.window...,day
1,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2071A,ALTA PADOVANA,SPO.IT2071A_5_gravi_2011-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-daysAbove45,1 year day exceed 45,...,11.9022,45.6003,25.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:34,https://eeadmz1batchservice02.blob.core.window...,day
2,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2071A,ALTA PADOVANA,SPO.IT2071A_5_gravi_2011-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-daysAbove50,1 year day exceed 50,...,11.9022,45.6003,25.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:38,https://eeadmz1batchservice02.blob.core.window...,day
3,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2071A,ALTA PADOVANA,SPO.IT2071A_5_gravi_2011-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-P1D-per90.41,1 year 90.41 percentile,...,11.9022,45.6003,25.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:34,https://eeadmz1batchservice02.blob.core.window...,day
4,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_5_BETA_2012-01-01_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y-P1D-per95.07,1 year 95.07 percentile of daily means (P1D) o...,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:04:38,https://eeadmz1batchservice02.blob.core.window...,day

<class 'pandas.DataFrame'>
RangeIndex: 8384 entries, 0 to 8383
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         8384 non-null   str
 1   Air Quality Network                                             8384 non-null   str
 2   Air Quality Network Name                                        8384 non-null   str
 3   Air Quality Station EoI Code                                    8384 non-null   str
 4   Air Quality Station Name                                        8384 non-null   str
 5   Sampling Point Id                                               8384 non-null   str
 6   Air Pollutant                                                   8384 non-null   str
 7   Air Pollutant Description                                       8384 non-null   str
 8   Data Aggregation Process Id                                     8384 non-null   str
 9   Data Aggregation Process                                        8384 non-null   str
 10  Year                                                            8384 non-null   int64
 11  Air Pollution Level                                             8368 non-null   float64
 12  Unit Of Air Pollution Level                                     8384 non-null   str
 13  Data Coverage                                                   8384 non-null   float64
 14  Verification                                                    8384 non-null   int64
 15  Air Quality Station Type                                        8384 non-null   str
 16  Air Quality Station Area                                        8384 non-null   str
 17  Longitude                                                       8384 non-null   float64
 18  Latitude                                                        8384 non-null   float64
 19  Altitude                                                        8384 non-null   float64
 20  City                                                            3212 non-null   str
 21  City Code                                                       3212 non-null   str
 22  City Population                                                 3212 non-null   float64
 23  Source Of Data Flow                                             8384 non-null   str
 24  Calculation Time                                                8384 non-null   str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  8384 non-null   str
 26  Observation Frequency                                           8350 non-null   str
dtypes: float64(6), int64(2), str(19)
memory usage: 1.7 MB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,8384,8384,8384,8384,8384,8384,8384,8384,8384,8384,...,8384.000000,8384.000000,8384.000000,3212,3212,3.212000e+03,8384,8384,8384,8350
unique,1,60,60,576,576,578,1,1,17,17,...,NaN,NaN,NaN,77,77,NaN,1,17,578,2
top,Italy,NET.IT250A,RETE REGIONALE DI RILEVAMENTO DELLA QUALITA' D...,IT0461A,FALCONARA SCUOLA,SPO.IT0459A_5_BETA_2006-02-20_00:00:00,PM10,Particulate matter < 10 µm (aerosol),P1Y,Annual mean / 1 calendar year,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:07,https://eeadmz1batchservice02.blob.core.window...,day
freq,8384,723,723,34,34,17,8384,8384,578,578,...,NaN,NaN,NaN,232,232,NaN,8384,578,17,6132
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.192225,42.923696,169.074332,NaN,NaN,6.798686e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.721610,2.567756,239.230399,NaN,NaN,1.095473e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.835900,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.838700,40.928300,18.000000,NaN,NaN,9.327500e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.239200,43.605900,70.000000,NaN,NaN,1.570170e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.197500,45.185600,224.000000,NaN,NaN,3.954160e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.176700,46.797400,1639.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                 16
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              5172
City Code                                                         5172
City Population                                                   5172
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                               34
dtype: int64

=== 2024_PM25_IT ===

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
0,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2243A,VR- Giarol Grande,SPO.IT2243A_6001_BETA_2016-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-daysAbove50,1 year day exceed 50,...,11.0301,45.4330,48.0,Verona ...,IT012C1 ...,259087.0,E1a/validated data AQ e-Reporting,10/02/2026 23:02:38,https://eeadmz1batchservice02.blob.core.window...,day
1,Italy,NET.IT281A,RETE REGIONALE QUALITA' ARIA DEL VENETO,IT2243A,VR- Giarol Grande,SPO.IT2243A_6001_BETA_2016-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P3Y,3 subsequent calendar years mean,...,11.0301,45.4330,48.0,Verona ...,IT012C1 ...,259087.0,E1a/validated data AQ e-Reporting,10/02/2026 23:04:51,https://eeadmz1batchservice02.blob.core.window...,day
2,Italy,NET.IT280A,RETE MONITORAGGIO ARIA REGIONE SARDEGNA,IT2010A,CENPT1,SPO.IT2010A_6001_BETA_2012-01-01_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-3daysAbove50,3 consecutive days in exceedance of 50,...,8.4053,40.8314,16.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:01:17,https://eeadmz1batchservice02.blob.core.window...,day
3,Italy,NET.IT282A,RETE REGIONALE QUALIT� ARIA AMBIENTE,IT0459A,CHIARAVALLE2,SPO.IT0459A_6001_BETA_2006-02-20_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-day-per50,1 year 50 %ile of daily values in a year,...,13.3419,43.5989,15.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:14,https://eeadmz1batchservice02.blob.core.window...,hour
4,Italy,NET.IT282A,RETE REGIONALE QUALIT� ARIA AMBIENTE,IT0459A,CHIARAVALLE2,SPO.IT0459A_6001_BETA_2006-02-20_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-daysAbove25,1 year day exceed 25,...,13.3419,43.5989,15.0,NaN,NaN,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:27,https://eeadmz1batchservice02.blob.core.window...,hour

<class 'pandas.DataFrame'>
RangeIndex: 3704 entries, 0 to 3703
Data columns (total 27 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         3704 non-null   str
 1   Air Quality Network                                             3704 non-null   str
 2   Air Quality Network Name                                        3704 non-null   str
 3   Air Quality Station EoI Code                                    3704 non-null   str
 4   Air Quality Station Name                                        3704 non-null   str
 5   Sampling Point Id                                               3704 non-null   str
 6   Air Pollutant                                                   3704 non-null   str
 7   Air Pollutant Description                                       3704 non-null   str
 8   Data Aggregation Process Id                                     3704 non-null   str
 9   Data Aggregation Process                                        3704 non-null   str
 10  Year                                                            3704 non-null   int64
 11  Air Pollution Level                                             3674 non-null   float64
 12  Unit Of Air Pollution Level                                     3704 non-null   str
 13  Data Coverage                                                   3704 non-null   float64
 14  Verification                                                    3704 non-null   int64
 15  Air Quality Station Type                                        3704 non-null   str
 16  Air Quality Station Area                                        3704 non-null   str
 17  Longitude                                                       3704 non-null   float64
 18  Latitude                                                        3704 non-null   float64
 19  Altitude                                                        3704 non-null   float64
 20  City                                                            1532 non-null   str
 21  City Code                                                       1532 non-null   str
 22  City Population                                                 1532 non-null   float64
 23  Source Of Data Flow                                             3704 non-null   str
 24  Calculation Time                                                3704 non-null   str
 25  Link to raw data (only E1a/validated data from AQ e-Reporting)  3704 non-null   str
 26  Observation Frequency                                           3691 non-null   str
dtypes: float64(6), int64(2), str(19)
memory usage: 781.4 KB

,Country,Air Quality Network,Air Quality Network Name,Air Quality Station EoI Code,Air Quality Station Name,Sampling Point Id,Air Pollutant,Air Pollutant Description,Data Aggregation Process Id,Data Aggregation Process,...,Longitude,Latitude,Altitude,City,City Code,City Population,Source Of Data Flow,Calculation Time,Link to raw data (only E1a/validated data from AQ e-Reporting),Observation Frequency
count,3704,3704,3704,3704,3704,3704,3704,3704,3704,3704,...,3704.000000,3704.000000,3704.000000,1532,1532,1.532000e+03,3704,3704,3704,3691
unique,1,56,56,343,343,344,1,1,13,13,...,NaN,NaN,NaN,74,74,NaN,1,13,344,2
top,Italy,NET.IT116A,MONITORAGGIO AMBIENTALE DELLA REGIONE CAMPANIA...,IT1827A,Ancona Cittadella,SPO.IT0459A_6001_BETA_2006-02-20_00:00:00,PM2.5,Particulate matter < 2.5 µm (aerosol),P1Y-daysAbove50,1 year day exceed 50,...,NaN,NaN,NaN,Napoli (greater city) ...,IT003K1 ...,NaN,E1a/validated data AQ e-Reporting,10/02/2026 23:02:38,https://eeadmz1batchservice02.blob.core.window...,day
freq,3704,349,349,26,26,13,3704,3704,344,344,...,NaN,NaN,NaN,140,140,NaN,3704,344,13,2560
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.239757,43.009523,171.784827,NaN,NaN,7.000310e+05,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.763926,2.337458,225.694293,NaN,NaN,1.111198e+06,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.304300,35.502800,-2.000000,NaN,NaN,4.027800e+04,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.838700,41.045900,20.000000,NaN,NaN,9.255000e+04,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.447600,43.472800,76.500000,NaN,NaN,1.496730e+05,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.213100,45.104100,233.250000,NaN,NaN,5.657520e+05,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.176700,46.619500,1225.000000,NaN,NaN,3.622641e+06,NaN,NaN,NaN,NaN

Country                                                              0
Air Quality Network                                                  0
Air Quality Network Name                                             0
Air Quality Station EoI Code                                         0
Air Quality Station Name                                             0
Sampling Point Id                                                    0
Air Pollutant                                                        0
Air Pollutant Description                                            0
Data Aggregation Process Id                                          0
Data Aggregation Process                                             0
Year                                                                 0
Air Pollution Level                                                 30
Unit Of Air Pollution Level                                          0
Data Coverage                                                        0
Verification                                                         0
Air Quality Station Type                                             0
Air Quality Station Area                                             0
Longitude                                                            0
Latitude                                                             0
Altitude                                                             0
City                                                              2172
City Code                                                         2172
City Population                                                   2172
Source Of Data Flow                                                  0
Calculation Time                                                     0
Link to raw data (only E1a/validated data from AQ e-Reporting)       0
Observation Frequency                                               13
dtype: int64

## Data cleaning

### Helper methods

In [246]:
# cleaning helper functions for a single DataFrame and for the full dfs dictionary

def remove_column(df, name_of_col: str):
    return df.drop(columns=[name_of_col], errors="ignore")

def remove_duplicate_rows(df):
    return df.drop_duplicates()

def remove_missing_values(df, subset=None):
    return df.dropna(subset=subset)

def filter_rows_by_condition(df, condition_builder, keep_when_true=True):
    """Reusable row filter helper. condition_builder receives df and returns a boolean mask."""
    mask = condition_builder(df)
    if not isinstance(mask, pd.Series):
        raise ValueError("condition_builder must return a pandas Series")
    mask = mask.reindex(df.index, fill_value=False).fillna(False)
    if not keep_when_true:
        mask = ~mask
    return df.loc[mask].copy()

def filter_numeric_column(df, column_name, threshold, operator=">="):
    """Generic numeric threshold filter usable for different if/condition rules."""
    if column_name not in df.columns:
        return df

    numeric_values = pd.to_numeric(df[column_name], errors="coerce")
    comparators = {
        ">": numeric_values > threshold,
        ">=": numeric_values >= threshold,
        "<": numeric_values < threshold,
        "<=": numeric_values <= threshold,
        "==": numeric_values == threshold,
        "!=": numeric_values != threshold,
    }

    if operator not in comparators:
        raise ValueError(f"Unsupported operator '{operator}'")

    return filter_rows_by_condition(df, lambda _: comparators[operator])

def normalize_unit_label(value):
    unit = str(value).strip().lower()
    unit = unit.replace("µ", "u").replace("μ", "u").replace("³", "3")
    unit = unit.replace(" ", "")
    return unit

def keep_ugm3_rows(df, unit_col="Unit Of Air Pollution Level"):
    if unit_col not in df.columns:
        return df

    normalized_units = df[unit_col].map(normalize_unit_label)
    ugm3_mask = normalized_units.isin({"ug/m3", "ug/m^3"})
    return df.loc[ugm3_mask].copy()

def keep_min_coverage_rows(df, coverage_col="Data Coverage", min_coverage=75):
    if coverage_col not in df.columns:
        return df

    coverage_values = pd.to_numeric(df[coverage_col], errors="coerce")

    # Handle both [0, 1] and [0, 100] coverage representations.
    non_null_values = coverage_values.dropna()
    if not non_null_values.empty and non_null_values.max() <= 1:
        coverage_values = coverage_values * 100

    return filter_rows_by_condition(df, lambda _: coverage_values >= min_coverage)

def apply_to_all(dataframes, transform):
    return {name: transform(df.copy()) for name, df in dataframes.items()}

### Features selection and null dropping

AQ data cleanijg

In [247]:
# remove raw-data-link column from all datasets and remove duplicate rows

raw_data_col = "Link to raw data (only E1a/validated data from AQ e-Reporting)"
required_measurement_cols = [
    "Air Quality Station EoI Code",
    "Year",
    "Air Pollutant",
    "Data Aggregation Process",
    "Air Pollution Level",
]

dfs = apply_to_all(dfs, lambda df: remove_column(df, raw_data_col))
dfs_pop = apply_to_all(dfs_pop, lambda df: remove_column(df, raw_data_col))

dfs = apply_to_all(dfs, lambda df: remove_missing_values(df, subset=required_measurement_cols))
dfs_pop = apply_to_all(dfs_pop, lambda df: remove_missing_values(df, subset=required_measurement_cols))

dfs = apply_to_all(dfs, remove_duplicate_rows)
dfs_pop = apply_to_all(dfs_pop, remove_duplicate_rows)

# Keep only concentration measurements in ug/m3 and drop count-based rows.
annual_process = "Annual mean / 1 calendar year"

dfs = apply_to_all(
    dfs,
    lambda df: filter_rows_by_condition(
        df,
        lambda d: (
            d["Unit Of Air Pollution Level"].map(normalize_unit_label).isin({"ug/m3", "ug/m^3"})
            & d["Data Aggregation Process"].astype(str).str.strip().eq(annual_process)
        )
    )
)

dfs_pop = apply_to_all(
    dfs_pop,
    lambda df: filter_rows_by_condition(
        df,
        lambda d: (
            d["Unit Of Air Pollution Level"].map(normalize_unit_label).isin({"ug/m3", "ug/m^3"})
            & d["Data Aggregation Process"].astype(str).str.strip().eq(annual_process)
        )
    )
)

# Remove station records where data coverage is below 75%.
dfs = apply_to_all(dfs, lambda df: keep_min_coverage_rows(df, min_coverage=75))
dfs_pop = apply_to_all(dfs_pop, lambda df: keep_min_coverage_rows(df, min_coverage=75))

In [248]:
# table of % missing values per column for each dataset in dfs
missing_tables = {}

for key, df in dfs.items():
    missing_pct = (df.isnull().mean() * 100).round(2)
    missing_tables[key] = missing_pct.to_frame(name="% missing")

# combine into one table
combined_missing_table = pd.concat(missing_tables, axis=0)

combined_missing_table  # open this variable with data wrangler to inspect missing values

                                           % missing
2023_NO2_IT  Country                            0.00
             Air Quality Network                0.00
             Air Quality Network Name           0.00
             Air Quality Station EoI Code       0.00
             Air Quality Station Name           0.00
...                                              ...
2024_PM25_IT City Code                         57.85
             City Population                   57.85
             Source Of Data Flow                0.00
             Calculation Time                   0.00
             Observation Frequency              0.00

[208 rows x 1 columns]

In [249]:
# extract population from population csv
reference_year = 2022
population_path = raw_dir / "population.csv"
population_raw = pd.read_csv(population_path)

population_reference = (
    population_raw[
        pd.to_numeric(population_raw["Year"], errors="coerce").eq(reference_year)
    ][["Country Name", "Country Code", "Year", "Value"]]
    .copy()
    .rename(columns={"Country Name": "Country", "Value": "Population"})
)

population_reference["Population"] = pd.to_numeric(population_reference["Population"], errors="coerce")
population_reference = population_reference.dropna(subset=["Population"]).reset_index(drop=True)
population_reference["Population"] = population_reference["Population"].astype(np.int64)
population_reference = population_reference.sort_values("Country").reset_index(drop=True)

population_reference

                         Country Country Code  Year  Population
0                    Afghanistan          AFG  2022    40578842
1    Africa Eastern and Southern          AFE  2022   731821393
2     Africa Western and Central          AFW  2022   497387180
3                        Albania          ALB  2022     2451636
4                        Algeria          DZA  2022    45477389
..                           ...          ...   ...         ...
260           West Bank and Gaza          PSE  2022     5043612
261                        World          WLD  2022  7989545217
262                  Yemen, Rep.          YEM  2022    38222876
263                       Zambia          ZMB  2022    20152938
264                     Zimbabwe          ZWE  2022    16069056

[265 rows x 4 columns]

Total emmision

In [250]:
# extract total produced pollution per country
import h5py

emissions_path = raw_dir / "v8.1_FT2022_AP_PM2.5_2022_TOTALS_emi.nc"

with h5py.File(emissions_path, "r") as emissions_file:
    emissions_grid = emissions_file["emissions"][:].astype(np.float64)
    latitudes = emissions_file["lat"][:]
    longitudes = emissions_file["lon"][:]

# Bounding boxes are a temporary approximation for country extraction from the global PM2.5 grid.
country_bounding_boxes = {
    #"Austria": {"lat_min": 46.3, "lat_max": 49.1, "lon_min": 9.4, "lon_max": 17.2},
    #"Belgium": {"lat_min": 49.4, "lat_max": 51.6, "lon_min": 2.4, "lon_max": 6.4},
    #"Bulgaria": {"lat_min": 41.2, "lat_max": 44.3, "lon_min": 22.3, "lon_max": 28.6},
    #"Croatia": {"lat_min": 42.2, "lat_max": 46.6, "lon_min": 13.4, "lon_max": 19.5},
    #"Cyprus": {"lat_min": 34.5, "lat_max": 35.8, "lon_min": 32.1, "lon_max": 34.8},
    #"Czechia": {"lat_min": 48.5, "lat_max": 51.1, "lon_min": 12.1, "lon_max": 18.9},
    #"Denmark": {"lat_min": 54.5, "lat_max": 57.8, "lon_min": 7.8, "lon_max": 15.3},
    #"Estonia": {"lat_min": 57.5, "lat_max": 59.8, "lon_min": 21.7, "lon_max": 28.2},
    #"Finland": {"lat_min": 59.7, "lat_max": 70.1, "lon_min": 20.6, "lon_max": 31.6},
    "Italy": {"lat_min": 35.4, "lat_max": 47.2, "lon_min": 6.5, "lon_max": 18.7},
    "Germany": {"lat_min": 47.2, "lat_max": 55.1, "lon_min": 5.5, "lon_max": 15.6},
    "France": {"lat_min": 41.2, "lat_max": 51.3, "lon_min": -5.5, "lon_max": 9.8},
    #"Greece": {"lat_min": 34.8, "lat_max": 41.8, "lon_min": 19.3, "lon_max": 29.7},
    #"Hungary": {"lat_min": 45.7, "lat_max": 48.6, "lon_min": 16.1, "lon_max": 22.9},
    #"Ireland": {"lat_min": 51.4, "lat_max": 55.4, "lon_min": -10.8, "lon_max": -5.4},
    #"Latvia": {"lat_min": 55.6, "lat_max": 58.1, "lon_min": 20.9, "lon_max": 28.2},
    #"Lithuania": {"lat_min": 53.8, "lat_max": 56.5, "lon_min": 20.9, "lon_max": 26.8},
    #"Luxembourg": {"lat_min": 49.4, "lat_max": 50.2, "lon_min": 5.7, "lon_max": 6.6},
    #"Malta": {"lat_min": 35.8, "lat_max": 36.1, "lon_min": 14.2, "lon_max": 14.7},
    #"Netherlands": {"lat_min": 50.7, "lat_max": 53.7, "lon_min": 3.2, "lon_max": 7.3},
    #"Norway": {"lat_min": 57.9, "lat_max": 71.2, "lon_min": 4.5, "lon_max": 31.3},
    #"Poland": {"lat_min": 49.0, "lat_max": 54.9, "lon_min": 14.1, "lon_max": 24.2},
    #"Portugal": {"lat_min": 36.8, "lat_max": 42.2, "lon_min": -9.6, "lon_max": -6.0},
    #"Romania": {"lat_min": 43.6, "lat_max": 48.3, "lon_min": 20.2, "lon_max": 29.7},
    #"Slovak Republic": {"lat_min": 47.7, "lat_max": 49.7, "lon_min": 16.8, "lon_max": 22.6},
    #"Slovenia": {"lat_min": 45.4, "lat_max": 46.9, "lon_min": 13.3, "lon_max": 16.6},
    "Spain": {"lat_min": 35.5, "lat_max": 43.9, "lon_min": -9.5, "lon_max": 4.5},
    #"Sweden": {"lat_min": 55.3, "lat_max": 69.1, "lon_min": 11.0, "lon_max": 24.3},
    #"Switzerland": {"lat_min": 45.8, "lat_max": 47.9, "lon_min": 5.9, "lon_max": 10.5},
    "United Kingdom": {"lat_min": 49.8, "lat_max": 58.8, "lon_min": -8.6, "lon_max": 1.8},
}

country_pm25_totals = []

for country, bounds in country_bounding_boxes.items():
    lat_mask = (latitudes >= bounds["lat_min"]) & (latitudes <= bounds["lat_max"])
    lon_mask = (longitudes >= bounds["lon_min"]) & (longitudes <= bounds["lon_max"])

    pm25_total_tonnes = float(np.nansum(emissions_grid[np.ix_(lat_mask, lon_mask)]))

    country_pm25_totals.append(
        {
            "Country": country,
            "Year": reference_year,
            "PM25_Produced_Tonnes": pm25_total_tonnes,
        }
    )

country_emissions_reference = pd.DataFrame(country_pm25_totals)
country_emissions_reference = country_emissions_reference.sort_values("Country").reset_index(drop=True)

shared_countries = sorted(
    set(population_reference["Country"]).intersection(country_emissions_reference["Country"])
)

population_reference = (
    population_reference[population_reference["Country"].isin(shared_countries)]
    .sort_values("Country")
    .reset_index(drop=True)
)
country_emissions_reference = (
    country_emissions_reference[country_emissions_reference["Country"].isin(shared_countries)]
    .sort_values("Country")
    .reset_index(drop=True)
)

print(f"Countries present in both population and pollution datasets: {len(shared_countries)}")

country_emissions_reference

Countries present in both population and pollution datasets: 5

          Country  Year  PM25_Produced_Tonnes
0          France  2022         393307.885039
1         Germany  2022         236738.864585
2           Italy  2022         322061.964530
3           Spain  2022         210383.324063
4  United Kingdom  2022         123137.000814

GISCO cleaning (leaving italy only info)

In [251]:
# 1) DERIVE GISCO -> ITALY ONLY
import geopandas as gpd
import pyogrio

gisco_path = f"{raw_dir}/GISCO_country_borders.gpkg"
gisco_layer = pyogrio.list_layers(gisco_path)[0][0]

out_gisco_it = f"{derived_dir}/GISCO_country_borders_derived.gpkg"
out_layer = "GISCO_IT_2024_03M_3035"

gisco = gpd.read_file(gisco_path, layer=gisco_layer)

gisco_it = gisco[(gisco["CNTR_ID"] == "IT") | (gisco["ISO3_CODE"] == "ITA")].copy()
if gisco_it.empty:
    raise ValueError(f"Italy not found. Available columns: {list(gisco.columns)}")

gisco_it.to_file(out_gisco_it, layer=out_layer, driver="GPKG")
print("Saved:", out_gisco_it, "| rows:", len(gisco_it), "| CRS:", gisco_it.crs)

DataSourceError: Data/Raw/GISCO_country_borders.gpkg: No such file or directory

### Saving derived data into CSV

In [252]:
# save the derived data into csv files under Data/Derived directory
for name, df in dfs.items():
    output_path = derived_dir / f"{name}_derived.csv"
    df.to_csv(output_path, index=False)
    print(f"Saved: {output_path}")

Saved: Data/Derived/2023_NO2_IT_derived.csv
Saved: Data/Derived/2023_O3_IT_derived.csv
Saved: Data/Derived/2023_PM10_IT_derived.csv
Saved: Data/Derived/2023_PM25_IT_derived.csv
Saved: Data/Derived/2024_NO2_IT_derived.csv
Saved: Data/Derived/2024_O3_IT_derived.csv
Saved: Data/Derived/2024_PM10_IT_derived.csv
Saved: Data/Derived/2024_PM25_IT_derived.csv

In [253]:
# save country/population/produced pollution
country_population_emissions_2022 = population_reference.merge(
    country_emissions_reference,
    on=["Country", "Year"],
    how="inner",
)

country_population_emissions_2022["PM25_Produced_Kg_per_Person"] = (
    country_population_emissions_2022["PM25_Produced_Tonnes"] * 1000
    / country_population_emissions_2022["Population"]
)
country_population_emissions_2022["PM25_Produced_Kg_per_Person"] = (
    country_population_emissions_2022["PM25_Produced_Kg_per_Person"].round(6)
)
country_population_emissions_2022["PM25_Produced_Tonnes"] = (
    country_population_emissions_2022["PM25_Produced_Tonnes"].round(3)
)

country_population_emissions_output_path = derived_dir / f"country_population_pm25_{reference_year}.csv"
country_population_emissions_2022.to_csv(country_population_emissions_output_path, index=False)
print(f"Saved: {country_population_emissions_output_path}")

country_population_emissions_2022

Saved: Data/Derived/country_population_pm25_2022.csv

,Country,Country Code,Year,Population,PM25_Produced_Tonnes,PM25_Produced_Kg_per_Person
0,France,FRA,2022,68184457,393307.885,5.768292
1,Germany,DEU,2022,83177813,236738.865,2.846178
2,Italy,ITA,2022,59013667,322061.965,5.457413
3,Spain,ESP,2022,47786102,210383.324,4.402605
4,United Kingdom,GBR,2022,67604000,123137.001,1.821445

In [254]:
dfs_pie["2023_NO2_IT_derived"] = pd.read_csv("Data/Derived/2023_NO2_IT_derived.csv")
dfs_pie["2023_O3_IT_derived"] = pd.read_csv("Data/Derived/2023_O3_IT_derived.csv")
dfs_pie["2023_PM10_IT_derived"] = pd.read_csv("Data/Derived/2023_PM10_IT_derived.csv")
dfs_pie["2023_PM25_IT_derived"] = pd.read_csv("Data/Derived/2023_PM25_IT_derived.csv")

## EDA and Plotting

### Style Presets

In [256]:
CHART_STYLE_PRESETS = {
    "horizontal_bar": {
        "primary_color": "#345782",
        "secondary_color": "#0284b8",
        "track_color": "#161e30",
        "paper_bgcolor": "#162036",
        "plot_bgcolor": "#213052",
        "title_font_size": 25,
        "axis_title_font_size": 17,
        "x_tick_font_size": 15,
        "y_tick_font_size": 15,
        "title_y": 0.92,
        "track_width": 0.62,
        "primary_bar_width": 0.62,
        "secondary_bar_width": 0.35,
        "bar_gap": 0.34,
        "x_max_multiplier": 1.30,
        "split_line_color": "rgba(255,255,255,0.14)",
        "show_tracks": True,
        "min_height": 700,
        "pixels_per_category": 28,
        "y_axis_label_shift": 14,
    },
    "box_plot": {
        "fill_color": "rgba(2, 132, 184, .52)",
        "line_color": "#9bd1ee",
        "point_color": "#0284b8",
        "outlier_color": "rgba(239, 68, 68, 0.35)",
        "paper_bgcolor": "#162036",
        "plot_bgcolor": "#162036",
        "font_color": "#e8eef7",
        "x_grid_color": "rgba(255,255,255,0.12)",
        "y_grid_color": "rgba(255,255,255,0.07)",
        "title_font_size": 24,
        "axis_title_font_size": 16,
        "axis_tick_font_size": 13,
        "base_font_size": 14,
        "min_height": 650,
        "pixels_per_category": 36,
    },
    "map": {
        "paper_bgcolor": "#162036",
        "ocean_color": "#101c33",
        "land_color": "#162a46",
        "country_border_color": "rgba(220,235,255,0.55)",
        "coastline_color": "rgba(220,235,255,0.55)",
        "points_label": "Air Quality Station",
        "legend_panel_scale": 2.0,
        "dot_color": "#22d3cf",
        "dot_glow_color": "rgba(34, 211, 207, 0.30)",
        "dot_border_color": "#b6fff8",
        "font_color": "#e8eef7",
        "title_font_size": 64,
        "title_y": 0.98,
        "frame_aspect_ratio": 2200 / 1200,
        "dot_size": 4,
        "dot_glow_size": 2,
        "height": 900,
        "use_fixed_frame": True,
        "fixed_lat_min": 35.25,
        "fixed_lat_max": 47.65,
        "fixed_lon_min": 5.5,
        "fixed_lon_max": 20.0,
        "fixed_zoom": 4.2,
    },
    "vertical_bar": {
        # Inherited from annual_mean_pollutants style family.
        "color_palette": ["#345782", "#0284b8", "#3D5467", "#63D2FF", "#94B0DA"],
        "paper_bgcolor": "#162036",
        "plot_bgcolor": "#162036",
        "font_family": "Arial",
        "font_color": "#e8eef7",
        "title_font_size": 25,
        "axis_title_font_size": 17,
        "axis_tick_font_size": 15,
        "legend_font_size": 12,
        "grid_color": "rgba(255,255,255,0.10)",
        "x_tick_angle": 0,
        "bar_width": 0.20,
        "bar_gap": 0.24,
        "bar_group_gap": 0.05,
        "show_value_labels": False,
        "value_label_font_size": 11,
        "value_format": ".2f",
    },
}

comparison_barchart_style = CHART_STYLE_PRESETS["horizontal_bar"]

bar_chart_style = {
    **CHART_STYLE_PRESETS["horizontal_bar"],
    "title_font_size": 38,
    "axis_title_font_size": 25,
    "x_tick_font_size": 20,
    "y_tick_font_size": 18,
    "show_tracks": False,
    "min_height": 1100,
    "pixels_per_category": 32,
    "y_axis_label_shift": 18,
    "track_width": 0.72,
    "primary_bar_width": 0.68,
    "title_y": 0.97,
    "x_max_multiplier": 1.07,
}

boxplot_style = CHART_STYLE_PRESETS["box_plot"]

vertical_barchart_style = {
    **CHART_STYLE_PRESETS["vertical_bar"],
    "title_font_size": 30,
    "axis_title_font_size": 18,
    "axis_tick_font_size": 14,
}

dot_distribution_map_style = CHART_STYLE_PRESETS["map"]

polygon_map_style = {
    **CHART_STYLE_PRESETS["map"],
    "paper_bgcolor": "#162036",
    "font_color": "#E8EEF7",
    "country_border_color": "#E8EEF7",
    "land_color": "#66BB6A",
    "title_font_size": 16,
    "title_font_weight": "bold",
}

### Plotting Helper methods

In [257]:
async def save_plotly_graph_png(fig, output_path, width=1200, height=700, scale=2, force_canvas_size=False):
    """Save a Plotly chart by screenshotting the rendered web version headlessly."""
    output_path = Path(output_path).with_suffix(".png")

    # Legacy behavior keeps figure-controlled height unless explicitly forced.
    fig_for_export = go.Figure(fig)
    fig_for_export.update_layout(width=width)
    if force_canvas_size:
        fig_for_export.update_layout(height=height)

    html = fig_for_export.to_html(
        include_plotlyjs=True,
        full_html=False,
        config={"displayModeBar": False, "responsive": False},
    )
    if force_canvas_size:
        page_html = (
            "<!doctype html><html><head><meta charset='utf-8'>"
            "<style>"
            "html, body {margin: 0; padding: 0; background: transparent;}"
            f"#plot-wrap {{width: {width}px; height: {height}px;}}"
            "#plot-wrap .plotly-graph-div {width: 100% !important; height: 100% !important;}"
            "</style></head><body>"
            f"<div id='plot-wrap'>{html}</div>"
            "</body></html>"
        )
    else:
        page_html = (
            "<!doctype html><html><head><meta charset='utf-8'>"
            "<style>"
            "html, body {margin: 0; padding: 0; background: transparent;}"
            f"#plot-wrap {{width: {width}px;}}"
            "</style></head><body>"
            f"<div id='plot-wrap'>{html}</div>"
            "</body></html>"
        )

    try:
        with tempfile.TemporaryDirectory() as tmp_dir:
            html_path = Path(tmp_dir) / "plot.html"
            html_path.write_text(page_html, encoding="utf-8")

            async with async_playwright() as playwright:
                browser = await playwright.chromium.launch(headless=True)
                context = await browser.new_context(
                    viewport={"width": width, "height": height},
                    device_scale_factor=scale,
                )
                page = await context.new_page()
                await page.goto(html_path.as_uri(), wait_until="domcontentloaded")
                chart = page.locator(".plotly-graph-div").first
                await chart.wait_for(state="visible", timeout=30000)

                # Wait until Plotly has rendered any SVG trace or mapbox canvas.
                await page.wait_for_function(
                    "() => { const root = document.querySelector('.plotly-graph-div'); if (!root) return false; "
                    "const traces = root.querySelectorAll('svg .trace, .geo path').length; "
                    "const mapboxCanvas = root.querySelectorAll('.mapboxgl-canvas').length; "
                    "return traces > 0 || mapboxCanvas > 0; }",
                    timeout=30000,
                )
                await page.wait_for_timeout(1200)

                screenshot_target = page.locator("#plot-wrap").first if force_canvas_size else chart
                await screenshot_target.screenshot(path=str(output_path), omit_background=True)
                await context.close()
                await browser.close()
    except PlaywrightTimeoutError as exc:
        raise RuntimeError(
            "Timed out waiting for Plotly chart rendering (including map layers) in headless browser."
        ) from exc
    except Exception as exc:
        raise RuntimeError(
            "Headless export failed. Install Playwright and Chromium once with: "
            "pip install -U playwright && playwright install chromium"
        ) from exc

    print(f"Saved PNG graph to: {output_path}")

In [258]:
# plot polygon map
from matplotlib.patches import Patch

def plot_polygon_map(
    data,
    title,
    category_col=None,
    class_styles=None,
    border_data=None,
    figsize=(9, 11),
    output_path=None,
    show=True,
    style_config=None,
):
    # Reusable polygon map renderer for GeoDataFrames.
    if style_config is None:
        style_config = {}
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS.get("map", {}), **style_config}
    paper_bg = style.get("paper_bgcolor", "#162036")
    font_color = style.get("font_color", "#E8EEF7")
    border_color = style.get("country_border_color", "#E8EEF7")
    default_color = style.get("land_color", "#66BB6A")
    title_font_size = style.get("title_font_size", 16)
    title_font_weight = style.get("title_font_weight", "normal")

    if data is None or data.empty:
        raise ValueError("`data` is empty. Provide a non-empty GeoDataFrame.")

    gdf = data.copy()

    fig, ax = plt.subplots(figsize=figsize, facecolor=paper_bg)
    ax.set_facecolor(paper_bg)

    legend_handles = []

    if category_col is None:
        gdf.plot(ax=ax, color=default_color, linewidth=0, alpha=0.95)
    else:
        if category_col not in gdf.columns:
            raise ValueError(f"Missing category column: {category_col}")

        gdf[category_col] = gdf[category_col].astype(str)
        categories = sorted(gdf[category_col].dropna().unique().tolist())

        for category in categories:
            subset = gdf[gdf[category_col] == category]
            if subset.empty:
                continue

            color = default_color
            label = str(category)
            if isinstance(class_styles, dict) and category in class_styles:
                style_entry = class_styles[category]
                if isinstance(style_entry, dict):
                    color = style_entry.get("color", default_color)
                    label = style_entry.get("label", str(category))
                else:
                    color = str(style_entry)

            subset.plot(ax=ax, color=color, linewidth=0, alpha=0.95)
            legend_handles.append(Patch(facecolor=color, edgecolor="none", label=label))

    if border_data is not None and not border_data.empty:
        border_gdf = border_data.copy()
        if border_gdf.crs != gdf.crs:
            border_gdf = border_gdf.to_crs(gdf.crs)
        border_gdf.boundary.plot(ax=ax, color=border_color, linewidth=0.7, alpha=0.9)

    ax.set_title(title, fontsize=title_font_size, fontweight=title_font_weight, color=font_color, pad=12)
    ax.set_axis_off()

    if legend_handles:
        dedup = {}
        for handle in legend_handles:
            dedup[handle.get_label()] = handle
        legend = ax.legend(
            handles=list(dedup.values()),
            loc="lower left",
            frameon=True,
            facecolor=paper_bg,
            edgecolor="#9BD1EE",
        )
        for text in legend.get_texts():
            text.set_color(font_color)

    plt.tight_layout()

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, dpi=300, bbox_inches="tight", facecolor=fig.get_facecolor())
        print(f"Saved: {output_path}")

    if show:
        plt.show()

    return fig, ax

In [259]:
def create_comparison_horizontal_barchart(
    data,
    category_col,
    group_col,
    value_col,
    primary_group,
    secondary_group,
    title,
    xaxis_title,
    primary_label=None,
    secondary_label=None,
    category_order=None,
    sort_ascending=True,
    show_value_labels=True,
    auto_height=False,
    style_config=None,
):
    """Draw a two-series horizontal comparison bar chart from preprocessed data."""
    if style_config is None:
        style_config = {}
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS["horizontal_bar"], **style_config}

    required_columns = [category_col, group_col, value_col]
    missing_columns = [col for col in required_columns if col not in data.columns]
    if missing_columns:
        raise ValueError("Missing DataFrame columns: " + ", ".join(sorted(missing_columns)))

    working_df = data[required_columns].copy()
    selected_groups = [primary_group, secondary_group]
    working_df = working_df[working_df[group_col].isin(selected_groups)]
    if working_df.empty:
        raise ValueError("No rows available after filtering by selected groups.")

    try:
        pivot_df = working_df.pivot(
            index=category_col,
            columns=group_col,
            values=value_col,
        )
    except ValueError as exc:
        raise ValueError(
            "Input data must be pre-aggregated with one row per category/group before plotting."
        ) from exc

    required_groups = [primary_group, secondary_group]
    missing_groups = [group for group in required_groups if group not in pivot_df.columns]
    if missing_groups:
        raise ValueError("Selected groups not found in data: " + ", ".join(map(str, missing_groups)))

    pivot_df = pivot_df.dropna(subset=required_groups, how="any")
    if pivot_df.empty:
        raise ValueError("No comparable category rows remain after pivoting/dropna.")

    if category_order is not None:
        if not isinstance(category_order, (list, tuple)):
            raise TypeError("`category_order` must be a list/tuple when provided.")
        known_categories = pivot_df.index.tolist()
        categories = [cat for cat in category_order if cat in known_categories]
        categories.extend([cat for cat in known_categories if cat not in categories])
        pivot_df = pivot_df.reindex(categories)
    else:
        pivot_df = pivot_df.sort_values(primary_group, ascending=bool(sort_ascending))

    categories = pivot_df.index.tolist()
    primary_values = pivot_df[primary_group].tolist()
    secondary_values = pivot_df[secondary_group].tolist()

    primary_label = primary_label or str(primary_group)
    secondary_label = secondary_label or str(secondary_group)

    figure_height = (
        max(style["min_height"], int(len(categories) * style["pixels_per_category"]))
        if auto_height
        else None
    )

    max_value = max(primary_values + secondary_values)
    x_max = float(max_value * style["x_max_multiplier"]) if max_value > 0 else 1.0

    primary_text = [f"{value:.2f}" for value in primary_values]
    secondary_text = [f"{value:.2f}" for value in secondary_values]

    label_offset = max(max_value, 1.0) * 0.0001
    primary_label_x = [value + label_offset for value in primary_values]
    secondary_label_x = [value + label_offset for value in secondary_values]

    def build_value_annotations():
        if not show_value_labels:
            return []

        annotations = [
            dict(
                x=x,
                y=y,
                xref="x",
                yref="y",
                text=text,
                showarrow=False,
                xanchor="center",
                yanchor="middle",
                yshift=25,
                font=dict(color="#DCE7FF", size=14),
                align="center",
            )
            for x, y, text in zip(primary_label_x, categories, primary_text)
        ]

        annotations.extend(
            [
                dict(
                    x=x,
                    y=y,
                    xref="x",
                    yref="y",
                    text=text,
                    showarrow=False,
                    xanchor="center",
                    yanchor="middle",
                    yshift=-25,
                    font=dict(color="#E5FFFE", size=14),
                    align="center",
                )
                for x, y, text in zip(secondary_label_x, categories, secondary_text)
            ]
        )
        return annotations

    fig = go.Figure()

    if style["show_tracks"]:
        fig.add_trace(
            go.Bar(
                x=[x_max] * len(categories),
                y=categories,
                orientation="h",
                marker=dict(color=style["track_color"]),
                width=style["track_width"],
                hoverinfo="skip",
                showlegend=False,
                name="Track",
            )
        )

    fig.add_trace(
        go.Bar(
            x=primary_values,
            y=categories,
            orientation="h",
            name=primary_label,
            marker=dict(color=style["primary_color"]),
            width=style["primary_bar_width"],
            opacity=0.95,
            hovertemplate=f"%{{y}}<br>{primary_label}: %{{x:.2f}}<extra></extra>",
        )
    )

    fig.add_trace(
        go.Bar(
            x=secondary_values,
            y=categories,
            orientation="h",
            name=secondary_label,
            marker=dict(color=style["secondary_color"]),
            width=style["secondary_bar_width"],
            opacity=0.98,
            hovertemplate=f"%{{y}}<br>{secondary_label}: %{{x:.2f}}<extra></extra>",
        )
    )

    fig.update_layout(
        title=dict(
            text=f"<b>{title}</b>",
            x=0.02,
            y=style["title_y"],
            font=dict(size=style["title_font_size"], color="#FFFFFF"),
        ),
        barmode="overlay",
        height=figure_height,
        bargap=style["bar_gap"],
        paper_bgcolor=style["paper_bgcolor"],
        plot_bgcolor=style["plot_bgcolor"],
        margin=dict(l=60, r=250, t=120, b=100),
        legend=dict(
            title="",
            orientation="h",
            x=0.0,
            xanchor="left",
            y=1.14,
            bgcolor="rgba(0,0,0,0)",
            font=dict(color="#EAF2FF", size=18),
        ),
        showlegend=False,
        annotations=build_value_annotations(),
        font=dict(family="Arial", color="#EAF2FF"),
    )

    fig.update_xaxes(
        title_text=xaxis_title,
        range=[0, x_max],
        showgrid=True,
        gridcolor=style["split_line_color"],
        zeroline=False,
        tickfont=dict(size=style["x_tick_font_size"], color="#DFE8FF"),
        title_font=dict(size=style["axis_title_font_size"], color="#D7E6FF"),
    )

    fig.update_yaxes(
        title_text="",
        side="right",
        anchor="free",
        position=1,
        shift=style["y_axis_label_shift"],
        automargin=True,
        showgrid=False,
        tickfont=dict(size=style["y_tick_font_size"], color="#F1F6FF"),
    )

    return fig

In [260]:
def create_horizontal_barchart(
    data,
    category_col,
    value_col,
    title,
    xaxis_title,
    bar_label="Value",
    category_order=None,
    sort_ascending=True,
    show_value_labels=True,
    auto_height=False,
    style_config=None,
):
    """Draw a single-series horizontal bar chart from preprocessed data."""
    if style_config is None:
        style_config = {}
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS["horizontal_bar"], **style_config}

    required_columns = [category_col, value_col]
    missing_columns = [col for col in required_columns if col not in data.columns]
    if missing_columns:
        raise ValueError("Missing DataFrame columns: " + ", ".join(sorted(missing_columns)))

    working_df = data[required_columns].copy()
    if working_df[category_col].duplicated().any():
        raise ValueError(
            "Input data must be pre-aggregated with one row per category before plotting."
        )

    pivot_df = working_df.set_index(category_col)[[value_col]]
    if pivot_df.empty:
        raise ValueError("No rows available for horizontal chart.")

    if category_order is not None:
        if not isinstance(category_order, (list, tuple)):
            raise TypeError("`category_order` must be a list/tuple when provided.")
        known_categories = pivot_df.index.tolist()
        categories = [cat for cat in category_order if cat in known_categories]
        categories.extend([cat for cat in known_categories if cat not in categories])
        pivot_df = pivot_df.reindex(categories)
    else:
        pivot_df = pivot_df.sort_values(value_col, ascending=bool(sort_ascending))

    categories = pivot_df.index.tolist()
    primary_values = pivot_df[value_col].tolist()

    figure_height = (
        max(style["min_height"], int(len(categories) * style["pixels_per_category"]))
        if auto_height
        else None
    )

    max_value = max(primary_values)
    x_max = float(max_value * style["x_max_multiplier"]) if max_value > 0 else 1.0

    primary_text = [f"{value:.2f}" for value in primary_values]
    single_series_label_offset = max(max_value, 1.0) * max(0.0001, 0.015)
    primary_label_x = [value + single_series_label_offset for value in primary_values]

    def build_value_annotations():
        if not show_value_labels:
            return []

        return [
            dict(
                x=x,
                y=y,
                xref="x",
                yref="y",
                text=text,
                showarrow=False,
                xanchor="left",
                yanchor="middle",
                yshift=0,
                font=dict(color="#DCE7FF", size=14),
                align="center",
            )
            for x, y, text in zip(primary_label_x, categories, primary_text)
        ]

    fig = go.Figure()

    if style["show_tracks"]:
        fig.add_trace(
            go.Bar(
                x=[x_max] * len(categories),
                y=categories,
                orientation="h",
                marker=dict(color=style["track_color"]),
                width=style["track_width"],
                hoverinfo="skip",
                showlegend=False,
                name="Track",
            )
        )

    fig.add_trace(
        go.Bar(
            x=primary_values,
            y=categories,
            orientation="h",
            name=bar_label,
            marker=dict(color=style["primary_color"]),
            width=style["primary_bar_width"],
            opacity=0.95,
            hovertemplate=f"%{{y}}<br>{bar_label}: %{{x:.2f}}<extra></extra>",
        )
    )

    fig.update_layout(
        title=dict(
            text=f"<b>{title}</b>",
            x=0.02,
            y=style["title_y"],
            font=dict(size=style["title_font_size"], color="#FFFFFF"),
        ),
        barmode="relative",
        height=figure_height,
        bargap=style["bar_gap"],
        paper_bgcolor=style["paper_bgcolor"],
        plot_bgcolor=style["plot_bgcolor"],
        margin=dict(l=60, r=250, t=120, b=100),
        legend=dict(
            title="",
            orientation="h",
            x=0.0,
            xanchor="left",
            y=1.14,
            bgcolor="rgba(0,0,0,0)",
            font=dict(color="#EAF2FF", size=18),
        ),
        showlegend=False,
        annotations=build_value_annotations(),
        font=dict(family="Arial", color="#EAF2FF"),
    )

    fig.update_xaxes(
        title_text=xaxis_title,
        range=[0, x_max],
        showgrid=True,
        gridcolor=style["split_line_color"],
        zeroline=False,
        tickfont=dict(size=style["x_tick_font_size"], color="#DFE8FF"),
        title_font=dict(size=style["axis_title_font_size"], color="#D7E6FF"),
    )

    fig.update_yaxes(
        title_text="",
        side="right",
        anchor="free",
        position=1,
        shift=style["y_axis_label_shift"],
        automargin=True,
        showgrid=False,
        tickfont=dict(size=style["y_tick_font_size"], color="#F1F6FF"),
    )

    return fig

In [261]:
def create_boxplot(
    data,
    category_col,
    value_col,
    title,
    xaxis_title,
    yaxis_title,
    use_log_x=True,
    category_order=None,
    style_config=None,
):
    """Build a reusable horizontal box plot from preprocessed data."""
    if style_config is None:
        style_config = {}
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS["box_plot"], **style_config}

    missing_columns = [col for col in [category_col, value_col] if col not in data.columns]
    if missing_columns:
        raise ValueError("Missing DataFrame columns: " + ", ".join(sorted(missing_columns)))

    working_df = data[[category_col, value_col]].copy()
    working_df["_plot_value"] = pd.to_numeric(working_df[value_col], errors="coerce")
    working_df = working_df.dropna(subset=[category_col, "_plot_value"])

    if use_log_x:
        # Log scale cannot plot <= 0 values.
        working_df = working_df[working_df["_plot_value"] > 0]

    if working_df.empty:
        raise ValueError("No rows available for box plot after filtering.")

    if category_order is not None:
        if not isinstance(category_order, (list, tuple)):
            raise TypeError("`category_order` must be a list/tuple when provided.")
        known_categories = working_df[category_col].drop_duplicates().tolist()
        category_order = [cat for cat in category_order if cat in known_categories]
        category_order.extend([cat for cat in known_categories if cat not in category_order])
    else:
        category_order = (
            working_df.groupby(category_col)["_plot_value"]
            .median()
            .sort_values(ascending=False)
            .index.tolist()
        )

    plot_height = max(style["min_height"], int(working_df[category_col].nunique() * style["pixels_per_category"]))

    fig = go.Figure()
    fig.add_trace(
        go.Box(
            x=working_df["_plot_value"],
            y=working_df[category_col],
            orientation="h",
            boxpoints="outliers",
            jitter=0.2,
            pointpos=0,
            fillcolor=style["fill_color"],
            marker=dict(
                color=style["point_color"],
                outliercolor=style["outlier_color"],
                size=3,
                line=dict(width=0),
            ),
            line=dict(color=style["line_color"], width=1.2),
            whiskerwidth=0.75,
            hovertemplate="<b>%{y}</b><br>%{x:.3f}<extra></extra>",
            name=value_col,
        )
    )

    fig.update_layout(
        title=dict(
            text=f"<b>{title}</b>",
            x=0.5,
            xanchor="center",
            y=0.97,
            font=dict(size=style["title_font_size"]),
        ),
        xaxis=dict(
            title=xaxis_title,
            type="log" if use_log_x else "linear",
            gridcolor=style["x_grid_color"],
            zeroline=False,
            tickfont=dict(size=style["axis_tick_font_size"]),
            title_font=dict(size=style["axis_title_font_size"]),
        ),
        yaxis=dict(
            title=yaxis_title,
            categoryorder="array",
            categoryarray=category_order,
            gridcolor=style["y_grid_color"],
            tickfont=dict(size=style["axis_tick_font_size"]),
            title_font=dict(size=style["axis_title_font_size"]),
        ),
        height=plot_height,
        margin=dict(l=280, r=30, t=70, b=45),
        showlegend=False,
        paper_bgcolor=style["paper_bgcolor"],
        plot_bgcolor=style["plot_bgcolor"],
        font=dict(color=style["font_color"], size=style["base_font_size"], family="Arial"),
    )

    return fig

In [262]:
def create_dot_distribution_map(
    data,
    lat_col,
    lon_col,
    label_col,
    title,
    map_engine="geo",
    map_style="carto-darkmatter",
    size_col=None,
    use_variable_dot_size=False,
    size_range=(2, 10),
    style_config=None,
):
    """Build a reusable dot distribution map from latitude/longitude points."""
    if style_config is None:
        style_config = {}
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS["map"], **style_config}

    required_columns = [lat_col, lon_col, label_col]
    if use_variable_dot_size:
        if size_col is None:
            raise ValueError("`size_col` must be provided when `use_variable_dot_size=True`.")
        required_columns.append(size_col)
    missing_columns = [col for col in required_columns if col not in data.columns]
    if missing_columns:
        raise ValueError("Missing DataFrame columns: " + ", ".join(sorted(missing_columns)))

    working_df = data[required_columns].copy()
    working_df["_lat"] = pd.to_numeric(working_df[lat_col], errors="coerce")
    working_df["_lon"] = pd.to_numeric(working_df[lon_col], errors="coerce")
    working_df = working_df.dropna(subset=["_lat", "_lon"])
    working_df = working_df[
        working_df["_lat"].between(-90, 90) & working_df["_lon"].between(-180, 180)
    ]
    if working_df.empty:
        raise ValueError("No valid latitude/longitude rows available after cleaning.")

    if use_variable_dot_size:
        size_min, size_max = map(float, size_range)
        if size_min <= 0 or size_max <= 0 or size_max < size_min:
            raise ValueError("`size_range` must contain positive values with max >= min.")

        working_df["_size_value"] = pd.to_numeric(working_df[size_col], errors="coerce")
        working_df = working_df.dropna(subset=["_size_value"])
        if working_df.empty:
            raise ValueError("No valid numeric rows available for variable dot sizing.")

        source_min = float(working_df["_size_value"].min())
        source_max = float(working_df["_size_value"].max())
        if source_max > source_min:
            normalized = (working_df["_size_value"] - source_min) / (source_max - source_min)
        else:
            normalized = pd.Series(0.5, index=working_df.index)

        working_df["_dot_size"] = size_min + normalized * (size_max - size_min)
        glow_padding = max(1.0, float(style["dot_glow_size"]))
        working_df["_glow_size"] = working_df["_dot_size"] + glow_padding
    else:
        working_df["_dot_size"] = float(style["dot_size"])
        working_df["_glow_size"] = float(style["dot_glow_size"])

    map_engine = str(map_engine).strip().lower()
    if map_engine not in {"geo", "tile", "auto"}:
        raise ValueError("`map_engine` must be one of: geo, tile, auto")

    has_maplibre = hasattr(go, "Scattermap") and hasattr(go.Layout(), "map")
    has_mapbox = hasattr(go, "Scattermapbox")

    if map_engine == "auto":
        map_engine = "tile" if (has_maplibre or has_mapbox) else "geo"
    if map_engine == "tile" and not (has_maplibre or has_mapbox):
        map_engine = "geo"

    use_fixed_frame = bool(style.get("use_fixed_frame", False))
    if use_fixed_frame:
        lat_min = float(style.get("fixed_lat_min", 35.25))
        lat_max = float(style.get("fixed_lat_max", 47.65))
        lon_min = float(style.get("fixed_lon_min", 5.5))
        lon_max = float(style.get("fixed_lon_max", 20.0))
        if lat_max <= lat_min or lon_max <= lon_min:
            raise ValueError(
                "Fixed map frame bounds are invalid. Ensure max > min for latitude and longitude."
            )
        lat_center = (lat_min + lat_max) / 2
        lon_center = (lon_min + lon_max) / 2
        lat_span = lat_max - lat_min
        lon_span = lon_max - lon_min
    else:
        lat_center = float(working_df["_lat"].mean())
        lon_center = float(working_df["_lon"].mean())
        lat_span = float(working_df["_lat"].max() - working_df["_lat"].min())
        lon_span = float(working_df["_lon"].max() - working_df["_lon"].min())
        lat_pad = max(0.8, lat_span * 0.20)
        lon_pad = max(1.0, lon_span * 0.20)

        lat_min = float(working_df["_lat"].min() - lat_pad)
        lat_max = float(working_df["_lat"].max() + lat_pad)
        lon_min = float(working_df["_lon"].min() - lon_pad)
        lon_max = float(working_df["_lon"].max() + lon_pad)

    max_span = max(lat_span, lon_span)

    if map_engine == "geo":
        import math

        frame_ratio = float(style["frame_aspect_ratio"])
        lat_min_clip = max(-85.0, min(85.0, lat_min))
        lat_max_clip = max(-85.0, min(85.0, lat_max))
        y_min = math.log(math.tan(math.pi / 4 + math.radians(lat_min_clip) / 2))
        y_max = math.log(math.tan(math.pi / 4 + math.radians(lat_max_clip) / 2))
        required_lon_span = math.degrees((y_max - y_min) * frame_ratio)
        current_lon_span = lon_max - lon_min

        if required_lon_span > current_lon_span:
            extra = (required_lon_span - current_lon_span) / 2
            lon_min -= extra
            lon_max += extra

    fixed_zoom = style.get("fixed_zoom")
    if use_fixed_frame and fixed_zoom is not None:
        zoom = float(fixed_zoom)
    elif max_span <= 0.15:
        zoom = 8.0
    elif max_span <= 0.35:
        zoom = 7.2
    elif max_span <= 0.8:
        zoom = 6.3
    elif max_span <= 1.8:
        zoom = 5.5
    elif max_span <= 3.5:
        zoom = 4.8
    elif max_span <= 7.0:
        zoom = 4.1
    else:
        zoom = 3.5

    title_text = f"<b>{title}</b>"
    panel_scale = max(0.5, float(style["legend_panel_scale"]))
    legend_font_size = max(10, int(round(16 * panel_scale)))
    legend_itemwidth = max(30, int(round(40 * panel_scale)))
    legend_dot_size = max(6, int(round(10 * panel_scale)))

    fig = go.Figure()

    if map_engine == "tile":
        scatter_cls = go.Scattermap if has_maplibre else go.Scattermapbox

        fig.add_trace(
            scatter_cls(
                lat=working_df["_lat"],
                lon=working_df["_lon"],
                mode="markers",
                marker=dict(
                    size=working_df["_glow_size"],
                    color=style["dot_glow_color"],
                    opacity=0.55,
                ),
                hoverinfo="skip",
                showlegend=False,
            )
        )

        fig.add_trace(
            scatter_cls(
                lat=working_df["_lat"],
                lon=working_df["_lon"],
                mode="markers",
                text=working_df[label_col].astype(str),
                hovertemplate="<b>%{text}</b><extra></extra>",
                marker=dict(
                    size=working_df["_dot_size"],
                    color=style["dot_color"],
                    opacity=0.95,
                ),
                showlegend=False,
            )
        )

        fig.add_trace(
            scatter_cls(
                lat=[lat_center],
                lon=[lon_center],
                mode="markers",
                marker=dict(
                    size=legend_dot_size,
                    color=style["dot_color"],
                    opacity=0.95,
                ),
                name=style["points_label"],
                hoverinfo="skip",
                visible="legendonly",
            )
        )

        layout_kwargs = dict(
            annotations=[
                dict(
                    x=0.02,
                    y=style["title_y"],
                    xref="paper",
                    yref="paper",
                    xanchor="left",
                    yanchor="top",
                    text=title_text,
                    showarrow=False,
                    font=dict(size=style["title_font_size"], color=style["font_color"]),
                )
            ],
            paper_bgcolor=style["paper_bgcolor"],
            plot_bgcolor=style["paper_bgcolor"],
            font=dict(color=style["font_color"], family="Arial", size=14),
            height=style["height"],
            margin=dict(l=0, r=0, t=0, b=0),
            legend=dict(
                orientation="h",
                x=0.02,
                y=0.04,
                xanchor="left",
                yanchor="bottom",
                bgcolor="rgba(12, 22, 38, 0.80)",
                borderwidth=0,
                itemwidth=legend_itemwidth,
                font=dict(size=legend_font_size, color=style["font_color"]),
                itemsizing="trace",
            ),
        )

        map_layout = dict(
            style=map_style,
            center={"lat": lat_center, "lon": lon_center},
            zoom=zoom,
            domain={"x": [0, 1], "y": [0, 1]},
        )

        if has_maplibre:
            layout_kwargs["map"] = map_layout
        else:
            layout_kwargs["mapbox"] = map_layout

        fig.update_layout(**layout_kwargs)
        return fig

    fig.add_trace(
        go.Scattergeo(
            lat=working_df["_lat"],
            lon=working_df["_lon"],
            mode="markers",
            marker=dict(
                size=working_df["_glow_size"],
                color=style["dot_glow_color"],
                opacity=0.55,
            ),
            hoverinfo="skip",
            showlegend=False,
        )
    )

    fig.add_trace(
        go.Scattergeo(
            lat=working_df["_lat"],
            lon=working_df["_lon"],
            mode="markers",
            text=working_df[label_col].astype(str),
            hovertemplate="<b>%{text}</b><extra></extra>",
            marker=dict(
                size=working_df["_dot_size"],
                color=style["dot_color"],
                line=dict(color=style["dot_border_color"], width=0.5),
                opacity=0.95,
            ),
            showlegend=False,
        )
    )

    fig.add_trace(
        go.Scattergeo(
            lat=[lat_center],
            lon=[lon_center],
            mode="markers",
            marker=dict(
                size=legend_dot_size,
                color=style["dot_color"],
                line=dict(color=style["dot_border_color"], width=0.5),
                opacity=0.95,
            ),
            name=style["points_label"],
            hoverinfo="skip",
            visible="legendonly",
        )
    )

    fig.update_layout(
        annotations=[
            dict(
                x=0.02,
                y=style["title_y"],
                xref="paper",
                yref="paper",
                xanchor="left",
                yanchor="top",
                text=title_text,
                showarrow=False,
                font=dict(size=style["title_font_size"], color=style["font_color"]),
            )
        ],
        paper_bgcolor=style["paper_bgcolor"],
        plot_bgcolor=style["paper_bgcolor"],
        font=dict(color=style["font_color"], family="Arial", size=14),
        height=style["height"],
        margin=dict(l=0, r=0, t=0, b=0),
        legend=dict(
            orientation="h",
            x=0.02,
            y=0.04,
            xanchor="left",
            yanchor="bottom",
            bgcolor="rgba(12, 22, 38, 0.80)",
            borderwidth=0,
            itemwidth=legend_itemwidth,
            font=dict(size=legend_font_size, color=style["font_color"]),
            itemsizing="trace",
        ),
        geo=dict(
            projection_type="mercator",
            center=dict(lat=lat_center, lon=lon_center),
            showcountries=True,
            countrycolor=style["country_border_color"],
            showcoastlines=True,
            coastlinecolor=style["coastline_color"],
            showland=True,
            landcolor=style["land_color"],
            showocean=True,
            oceancolor=style["ocean_color"],
            showlakes=False,
            showframe=False,
            domain=dict(x=[0, 1], y=[0, 1]),
            bgcolor=style["paper_bgcolor"],
            lataxis=dict(
                range=[lat_min, lat_max],
                showgrid=False,
            ),
            lonaxis=dict(
                range=[lon_min, lon_max],
                showgrid=False,
            ),
        ),
    )

    return fig

In [263]:
def create_vertical_grouped_barchart(
    data,
    category_col,
    group_col,
    value_col,
    primary_group,
    secondary_groups=None,
    title="Vertical Grouped Bar Chart",
    xaxis_title="Category",
    yaxis_title="Value",
    group_labels=None,
    category_order=None,
    sort_categories=False,
    sort_ascending=True,
    barmode="group",
    style_config=None,
):
    """Build a reusable vertical grouped bar chart from preprocessed long-format data."""
    if secondary_groups is None:
        secondary_groups = []
    if group_labels is None:
        group_labels = {}
    if style_config is None:
        style_config = {}

    if not isinstance(secondary_groups, (list, tuple)):
        raise TypeError("`secondary_groups` must be a list or tuple when provided.")
    if not isinstance(group_labels, dict):
        raise TypeError("`group_labels` must be a dictionary when provided.")
    if not isinstance(style_config, dict):
        raise TypeError("`style_config` must be a dictionary when provided.")

    style = {**CHART_STYLE_PRESETS["vertical_bar"], **style_config}

    selected_groups = list(dict.fromkeys([primary_group, *list(secondary_groups)]))
    if not selected_groups:
        raise ValueError("At least one group is required to plot bars.")

    required_columns = [category_col, group_col, value_col]
    missing_columns = [col for col in required_columns if col not in data.columns]
    if missing_columns:
        raise ValueError("Missing DataFrame columns: " + ", ".join(sorted(missing_columns)))

    working_df = data[required_columns].copy()
    working_df = working_df[working_df[group_col].isin(selected_groups)]
    if working_df.empty:
        raise ValueError("No rows available after filtering by selected groups.")

    working_df["_plot_value"] = pd.to_numeric(working_df[value_col], errors="coerce")
    working_df = working_df.dropna(subset=[category_col, group_col, "_plot_value"])

    if working_df.duplicated(subset=[category_col, group_col]).any():
        raise ValueError(
            "Input data must be pre-aggregated with one row per category/group before plotting."
        )

    aggregated_df = working_df[[category_col, group_col, "_plot_value"]].copy()

    if category_order is not None:
        if not isinstance(category_order, (list, tuple)):
            raise TypeError("`category_order` must be a list/tuple when provided.")
        known_categories = aggregated_df[category_col].drop_duplicates().tolist()
        categories = [cat for cat in category_order if cat in known_categories]
        categories.extend([cat for cat in known_categories if cat not in categories])
    elif sort_categories:
        categories = (
            aggregated_df
            .groupby(category_col)["_plot_value"]
            .mean()
            .sort_values(ascending=bool(sort_ascending))
            .index.tolist()
        )
    else:
        categories = aggregated_df[category_col].drop_duplicates().tolist()

    if not categories:
        raise ValueError("No categories available to plot.")

    palette = list(dict.fromkeys(style["color_palette"]))
    if not palette:
        raise ValueError("`color_palette` must include at least one color.")

    group_color_map = {
        group: palette[idx % len(palette)]
        for idx, group in enumerate(selected_groups)
    }

    valid_barmodes = {"group", "stack", "relative", "overlay"}
    if barmode not in valid_barmodes:
        raise ValueError("`barmode` must be one of: " + ", ".join(sorted(valid_barmodes)))

    bar_gap = float(style["bar_gap"])
    bar_group_gap = float(style["bar_group_gap"])
    if not 0 <= bar_gap < 1:
        raise ValueError("`bar_gap` must be in [0, 1).")
    if bar_group_gap < 0:
        raise ValueError("`bar_group_gap` must be >= 0.")

    requested_bar_width = style["bar_width"]
    if requested_bar_width is not None and float(requested_bar_width) <= 0:
        raise ValueError("`bar_width` must be > 0 when provided.")

    category_band = max(0.05, 1.0 - bar_gap)
    if len(selected_groups) > 1:
        max_non_overlap_width = category_band / (
            len(selected_groups) + ((len(selected_groups) - 1) * bar_group_gap)
        )
    else:
        max_non_overlap_width = category_band

    if requested_bar_width is None:
        effective_bar_width = max_non_overlap_width * 0.92
    else:
        effective_bar_width = min(float(requested_bar_width), max_non_overlap_width * 0.98)

    fig = go.Figure()
    for group in selected_groups:
        group_df = (
            aggregated_df[aggregated_df[group_col] == group]
            .set_index(category_col)
            .reindex(categories)
        )
        y_values = group_df["_plot_value"].tolist()
        text_values = [
            format(value, style["value_format"]) if pd.notna(value) else ""
            for value in y_values
        ]

        fig.add_trace(
            go.Bar(
                x=categories,
                y=y_values,
                name=group_labels.get(group, str(group)),
                marker=dict(color=group_color_map[group]),
                width=effective_bar_width,
                offsetgroup=str(group),
                alignmentgroup="vertical_grouped_bars",
                text=text_values if style["show_value_labels"] else None,
                textposition="outside" if style["show_value_labels"] else None,
                textfont=dict(size=style["value_label_font_size"], color=style["font_color"]),
                cliponaxis=False,
                hovertemplate="%{x}<br>" + str(group_labels.get(group, group)) + ": %{y:.2f}<extra></extra>",
            )
        )

    fig.update_layout(
        title=dict(
            text=f"<b>{title}</b>",
            x=0.5,
            xanchor="center",
            y=0.97,
            font=dict(size=style["title_font_size"], color=style["font_color"]),
        ),
        barmode=barmode,
        bargap=bar_gap,
        bargroupgap=bar_group_gap,
        paper_bgcolor=style["paper_bgcolor"],
        plot_bgcolor=style["plot_bgcolor"],
        margin=dict(l=75, r=40, t=95, b=90),
        legend=dict(
            title="",
            orientation="v",
            x=1.01,
            xanchor="left",
            y=1.0,
            yanchor="top",
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=style["legend_font_size"], color=style["font_color"]),
        ),
        font=dict(family=style["font_family"], color=style["font_color"]),
    )

    fig.update_xaxes(
        title_text=xaxis_title,
        tickangle=style["x_tick_angle"],
        showgrid=False,
        zeroline=False,
        tickfont=dict(size=style["axis_tick_font_size"], color=style["font_color"]),
        title_font=dict(size=style["axis_title_font_size"], color=style["font_color"]),
    )

    fig.update_yaxes(
        title_text=yaxis_title,
        showgrid=True,
        gridcolor=style["grid_color"],
        zeroline=False,
        tickfont=dict(size=style["axis_tick_font_size"], color=style["font_color"]),
        title_font=dict(size=style["axis_title_font_size"], color=style["font_color"]),
    )

    return fig

### EDA calculations

In [264]:
# clean our industry and green area datas to only keep relevant cities

for key in dfs_pie:
    if key.endswith("IT_derived"):
        dfs_pie[key]["City"] = (
            dfs_pie[key]["City"]
            .str.strip()
            .str.lower()
            .str.replace(r"\s*\(greater city\)", "", regex=True)
        )
        dfs_pie[key] = dfs_pie[key].dropna(subset=["City"])


# collect normalized cities
all_cities = pd.concat(
    [dfs_pie[key]["City"]
     for key in dfs_pie
     if key.endswith("IT_derived")]
).unique()

dfs_pie["all_present_cities"] = pd.DataFrame(
    sorted(all_cities),
    columns=["City"]
)


# normalize comparison columns
dfs_pie["IT_industrial_area"]["municipality_name"] = (
    dfs_pie["IT_industrial_area"]["municipality_name"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s*\(greater city\)", "", regex=True)
)

dfs_pie["IT_urban_green_area"]["city"] = (
    dfs_pie["IT_urban_green_area"]["city"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s*\(greater city\)", "", regex=True)
)


allowed_cities = set(dfs_pie["all_present_cities"]["City"])


dfs_pie["IT_industrial_area"] = (
    dfs_pie["IT_industrial_area"]
    [dfs_pie["IT_industrial_area"]["municipality_name"].isin(allowed_cities)]
)

dfs_pie["IT_urban_green_area"] = (
    dfs_pie["IT_urban_green_area"]
    [dfs_pie["IT_urban_green_area"]["city"].isin(allowed_cities)]
)


# get the intersection of cities between industrial and urban green
common_cities = (
    set(dfs_pie["IT_industrial_area"]["municipality_name"])
    & set(dfs_pie["IT_urban_green_area"]["city"])
)

dfs_pie["IT_industrial_area"] = (
    dfs_pie["IT_industrial_area"]
    [dfs_pie["IT_industrial_area"]["municipality_name"].isin(common_cities)]
)

dfs_pie["IT_urban_green_area"] = (
    dfs_pie["IT_urban_green_area"]
    [dfs_pie["IT_urban_green_area"]["city"].isin(common_cities)]
)


# calculate percentage coverage of each category
industrial = dfs_pie["IT_industrial_area"][[
    "municipality_name",
    "municipality_area_km2",
    "industrial_area_km2"
]].copy()

green = dfs_pie["IT_urban_green_area"][[
    "city",
    "green_area_m2"
]].copy()

green["green_area_km2"] = green["green_area_m2"] / 1_000_000

city_land_cover = industrial.merge(
    green,
    left_on="municipality_name",
    right_on="city",
    how="inner"
)

city_land_cover["industry_share"] = (
    city_land_cover["industrial_area_km2"]
    / city_land_cover["municipality_area_km2"]
)

city_land_cover["green_share"] = (
    city_land_cover["green_area_km2"]
    / city_land_cover["municipality_area_km2"]
)

city_land_cover["urban_share"] = (
    1
    - city_land_cover["industry_share"]
    - city_land_cover["green_share"]
)

city_land_cover["industry_percent"] = city_land_cover["industry_share"] * 100
city_land_cover["green_percent"] = city_land_cover["green_share"] * 100
city_land_cover["urban_percent"] = city_land_cover["urban_share"] * 100


dfs_pie["IT_city_land_cover"] = city_land_cover

dfs_pie["IT_city_land_cover"].to_csv(
    "Data/Derived/IT_city_land_cover.csv",
    index=False
)

In [265]:
annual_mean_cols = [
    "Year",
    "Air Pollutant",
    "Air Pollution Level",
    "Unit Of Air Pollution Level",
    "Data Aggregation Process",
]

annual_mean_parts = []
for path in sorted(derived_dir.glob("*_IT_derived.csv")):
    part = pd.read_csv(path, usecols=annual_mean_cols)
    annual_mean_parts.append(part)

annual_mean_source = pd.concat(annual_mean_parts, ignore_index=True)

years = [2023, 2024]
unit = "ug/m3"
annual_process = "Annual mean / 1 calendar year"

annual_mean_filtered = annual_mean_source[
    annual_mean_source["Year"].isin(years)
    & (annual_mean_source["Unit Of Air Pollution Level"] == unit)
    & (annual_mean_source["Data Aggregation Process"] == annual_process)
]

annual_mean_pollutants = (
    annual_mean_filtered
    .groupby(["Year", "Air Pollutant"], as_index=False)["Air Pollution Level"]
    .mean()
    .sort_values(["Year", "Air Pollutant"])
)

annual_mean_pivot = annual_mean_pollutants.pivot(
    index="Air Pollutant",
    columns="Year",
    values="Air Pollution Level",
)
annual_mean_pivot.columns = [f"{year} (ug/m3)" for year in annual_mean_pivot.columns]

In [266]:
aggregation_chart_cols = [
    "Data Aggregation Process",
    "Air Pollution Level",
    "Unit Of Air Pollution Level",
]

aggregation_derived_parts = []
for path in sorted(derived_dir.glob("*_IT_derived.csv")):
    part = pd.read_csv(path, usecols=aggregation_chart_cols)
    aggregation_derived_parts.append(part)

aggregation_raw_parts = []
for path in sorted(raw_dir.glob("*_IT.csv")):
    part = pd.read_csv(path, usecols=aggregation_chart_cols)
    aggregation_raw_parts.append(part)

aggregation_derived_source = keep_ugm3_rows(pd.concat(aggregation_derived_parts, ignore_index=True))
aggregation_raw_source = keep_ugm3_rows(pd.concat(aggregation_raw_parts, ignore_index=True))

derived_process_count = (
    aggregation_derived_source["Data Aggregation Process"]
    .dropna()
    .astype(str)
    .str.strip()
    .nunique()
)

if derived_process_count <= 1 and not aggregation_raw_source.empty:
    aggregation_process_chart_source = aggregation_raw_source.copy()
else:
    aggregation_process_chart_source = aggregation_derived_source.copy()

data_aggregation_usage = (
    aggregation_process_chart_source["Data Aggregation Process"]
    .value_counts()
    .sort_values(ascending=True)
    .rename_axis("Data Aggregation Process")
    .reset_index(name="Total # of Usage")
)

In [267]:
air_pollution_boxplot_data = aggregation_process_chart_source.copy()

In [268]:
# Air quality station distribution source (ug/m3)
station_map_cols = [
    "Air Quality Station EoI Code",
    "Unit Of Air Pollution Level",
    "Latitude",
    "Longitude",
]

station_map_parts = []
for path in sorted(derived_dir.glob("*_IT_derived.csv")):
    part = pd.read_csv(path, usecols=station_map_cols)
    station_map_parts.append(part)

station_map_source = pd.concat(station_map_parts, ignore_index=True)
station_map_filtered = station_map_source[
    station_map_source["Unit Of Air Pollution Level"] == "ug/m3"
]

air_quality_station_points = (
    station_map_filtered
    .drop_duplicates(subset=["Air Quality Station EoI Code"])
    .rename(columns={"Air Quality Station EoI Code": "Station_ID"})
)

print(f"Plotting {len(air_quality_station_points)} unique stations across Italy.")

# Annual mean pollutant concentration by station area (ug/m3)
station_area_cols = [
    "Air Quality Station Area",
    "Air Pollutant",
    "Air Pollution Level",
    "Unit Of Air Pollution Level",
    "Data Aggregation Process",
]

station_area_parts = []
for path in sorted(derived_dir.glob("*_IT_derived.csv")):
    part = pd.read_csv(path, usecols=station_area_cols)
    station_area_parts.append(part)

station_area_source = pd.concat(station_area_parts, ignore_index=True)

station_area_filtered = station_area_source[
    (station_area_source["Unit Of Air Pollution Level"] == "ug/m3")
    & (station_area_source["Data Aggregation Process"] == "Annual mean / 1 calendar year")
]

station_area_pollutant_stats = (
    station_area_filtered
    .groupby(["Air Quality Station Area", "Air Pollutant"], as_index=False)["Air Pollution Level"]
    .mean()
)

Plotting 658 unique stations across Italy.

In [269]:
# annual mean of each pollutant grouped by city code
city_info = {}

# convert data to city level info

for name, df in dfs_pop.items():
    pollutant = name.split("_")[1]

    city_info[name] = (
        df.groupby(["City Code", "City", "City Population"], as_index=False)["Air Pollution Level"]
          .mean()
          .rename(columns={"Air Pollution Level": pollutant})
    )

pollutants = ["NO2", "O3", "PM10", "PM25"]

pollutant_avg = {}

# combine 23 and 24 data for each pollutant

for pollutant in pollutants:
    matching_dfs = []

    for name, df in city_info.items():
        current_pollutant = name.split("_")[1]
        if current_pollutant == pollutant:
            matching_dfs.append(df)

    if len(matching_dfs) == 0:
        continue

    # average pollutant values across years for each city

    combined = pd.concat(matching_dfs, ignore_index=True)

    pollutant_avg[pollutant] = (
        combined.groupby(["City Code", "City", "City Population"], as_index=False)[pollutant]
                .mean()
    )

# merge all pollutants into a single city level dataframe where we have
# City Code | City | City Population | NO2 | O3 | PM10 | PM25 | log_population

df_pollution_pop = pollutant_avg["NO2"]

for pollutant in ["O3", "PM10", "PM25"]:
    df_pollution_pop = pd.merge(
        df_pollution_pop,
        pollutant_avg[pollutant],
        on=["City Code", "City", "City Population"],
        how="inner"
    )

df_pollution_pop = df_pollution_pop.sort_values("City Population").reset_index(drop=True)

# logarithmically scale the population so the data is not skewed towards more common entries

df_pollution_pop["log_population"] = np.log(df_pollution_pop["City Population"])

In [270]:
# linear regression on population data and pollution level for each pollutant

regression_results = []

for pollutant in ["NO2", "O3", "PM10", "PM25"]:
    X = sm.add_constant(df_pollution_pop["log_population"])
    y = df_pollution_pop[pollutant]

    model = sm.OLS(y, X).fit()

    regression_results.append({
        "Pollutant": pollutant,
        "Intercept": model.params["const"],
        "Slope_log_population": model.params["log_population"],
        "R_squared": model.rsquared,
        "p_value": model.pvalues["log_population"]
    })

df_regression_results = pd.DataFrame(regression_results)

print(df_regression_results)

  Pollutant  Intercept  Slope_log_population  R_squared   p_value
0       NO2 -22.604716              3.692474   0.313230  0.000001
1        O3  62.901524             -0.743868   0.004919  0.575767
2      PM10   7.497894              1.380019   0.087293  0.016020
3      PM25   5.368744              0.722681   0.031372  0.154813

In [271]:
# mean pollution per city for 2023 (NO2, PM10, PM2.5)

# Build city-level pollution means from enhanced files.
# Method: average at station level first, then average across stations in each city.
# This avoids overweighting cities that have more station records.
# Final outputs are split by pollutant (excluding O3).

city_analysis_year = 2023
city_dot_map_aggregation_process = "Annual mean / 1 calendar year"
minimum_city_stations = 2

# If top_k_cities == -1, keep all available city records for each pollutant.
top_k_cities = 30

city_map_cols = [
    "Year",
    "Air Pollutant",
    "Data Aggregation Process",
    "Unit Of Air Pollution Level",
    "Data Coverage",
    "Air Quality Station Area",
    "Air Quality Station EoI Code",
    "City",
    "Latitude",
    "Longitude",
    "Air Pollution Level",
]

enhanced_paths = sorted(derived_dir.glob("*_IT_derived.csv"))
if not enhanced_paths:
    raise FileNotFoundError(
        f"No enhanced CSV files were found in {derived_dir}. "
        "Run the Data Enhancement block first."
    )

city_parts = [pd.read_csv(path, usecols=city_map_cols) for path in enhanced_paths]
city_source = pd.concat(city_parts, ignore_index=True)

if "normalize_unit_label" in globals():
    normalized_units = city_source["Unit Of Air Pollution Level"].map(normalize_unit_label)
else:
    normalized_units = (
        city_source["Unit Of Air Pollution Level"]
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace("µ", "u", regex=False)
        .str.replace("μ", "u", regex=False)
        .str.replace("³", "3", regex=False)
        .str.replace(" ", "", regex=False)
    )

city_source = city_source[normalized_units.isin({"ug/m3", "ug/m^3"})].copy()
city_source = city_source[
    city_source["Data Aggregation Process"].astype(str).str.strip().eq(city_dot_map_aggregation_process)
].copy()

city_source["Year"] = pd.to_numeric(city_source["Year"], errors="coerce")
city_source = city_source[city_source["Year"].eq(city_analysis_year)].copy()

city_source["Data Coverage"] = pd.to_numeric(city_source["Data Coverage"], errors="coerce")
coverage_values = city_source["Data Coverage"].copy()
non_null_coverage = coverage_values.dropna()
if not non_null_coverage.empty and non_null_coverage.max() <= 1:
    coverage_values = coverage_values * 100
city_source = city_source[coverage_values > 75].copy()

city_source["Air Quality Station Area"] = (
    city_source["Air Quality Station Area"].fillna("").astype(str).str.strip().str.lower()
)
city_source = city_source[city_source["Air Quality Station Area"].eq("urban")].copy()

city_source["City"] = city_source["City"].fillna("").astype(str).str.strip()
city_source = city_source[city_source["City"].ne("")].copy()

city_source["Air Pollution Level"] = pd.to_numeric(city_source["Air Pollution Level"], errors="coerce")
city_source["Latitude"] = pd.to_numeric(city_source["Latitude"], errors="coerce")
city_source["Longitude"] = pd.to_numeric(city_source["Longitude"], errors="coerce")
city_source = city_source.dropna(
    subset=["Air Pollution Level", "Latitude", "Longitude", "Air Quality Station EoI Code"]
)

if city_source.empty:
    raise ValueError(
        f"No rows available after filtering for year {city_analysis_year}, urban stations, coverage > 75, and annual mean ug/m3 data."
    )


def normalize_pollutant_label(value):
    normalized = str(value).strip().upper().replace(" ", "").replace(".", "")
    if normalized in {"PM25", "PM2,5"}:
        return "PM25"
    return normalized


city_source["Pollutant"] = city_source["Air Pollutant"].map(normalize_pollutant_label)

station_city_year_pollutant = (
    city_source
    .groupby(["Year", "Pollutant", "City", "Air Quality Station EoI Code"], as_index=False)
    .agg(
        station_pollution=("Air Pollution Level", "mean"),
        station_latitude=("Latitude", "mean"),
        station_longitude=("Longitude", "mean"),
    )
)

city_pollution_map_by_pollutant = (
    station_city_year_pollutant
    .groupby(["Year", "Pollutant", "City"], as_index=False)
    .agg(
        mean_city_pollution=("station_pollution", "mean"),
        city_latitude=("station_latitude", "mean"),
        city_longitude=("station_longitude", "mean"),
        station_count=("Air Quality Station EoI Code", "nunique"),
    )
    .sort_values(["Year", "Pollutant", "City"])
    .reset_index(drop=True)
)

final_pollutants = ["NO2", "PM10", "PM25"]

city_pollution_dot_map_data_full_by_pollutant = {}
city_pollution_dot_map_data_by_pollutant = {}

for pollutant in final_pollutants:
    pollutant_city_pollution_map = (
        city_pollution_map_by_pollutant[city_pollution_map_by_pollutant["Pollutant"].eq(pollutant)]
        .groupby("City", as_index=False)
        .agg(
            mean_city_pollution=("mean_city_pollution", "mean"),
            city_latitude=("city_latitude", "mean"),
            city_longitude=("city_longitude", "mean"),
            pollutant_year_points=("mean_city_pollution", "size"),
            stations_used=("station_count", "max"),
        )
        .query("stations_used >= @minimum_city_stations")
        .sort_values("mean_city_pollution", ascending=False)
        .reset_index(drop=True)
    )

    pollutant_dot_map_data_full = pollutant_city_pollution_map.rename(
        columns={
            "city_latitude": "Latitude",
            "city_longitude": "Longitude",
            "mean_city_pollution": "Mean Pollution (ug/m3)",
            "stations_used": "Stations Used",
            "pollutant_year_points": "Pollutant-Year Points",
        }
    )[[
        "City",
        "Latitude",
        "Longitude",
        "Mean Pollution (ug/m3)",
        "Stations Used",
        "Pollutant-Year Points",
    ]]

    pollutant_dot_map_data_full.insert(1, "Pollutant", pollutant)
    pollutant_dot_map_data_full["City_Label"] = (
        pollutant_dot_map_data_full["City"].astype(str)
        + "<br>Mean pollution: "
        + pollutant_dot_map_data_full["Mean Pollution (ug/m3)"].round(2).astype(str)
        + " ug/m3"
        + "<br>Stations used: "
        + pollutant_dot_map_data_full["Stations Used"].astype(int).astype(str)
    )

    pollutant_dot_map_data_full = pollutant_dot_map_data_full[[
        "City",
        "Pollutant",
        "Latitude",
        "Longitude",
        "Mean Pollution (ug/m3)",
        "Stations Used",
        "Pollutant-Year Points",
        "City_Label",
    ]]

    city_pollution_dot_map_data_full_by_pollutant[pollutant] = pollutant_dot_map_data_full

    sorted_city_data = pollutant_dot_map_data_full.sort_values("Mean Pollution (ug/m3)", ascending=False)
    if top_k_cities == -1:
        selected_city_data = sorted_city_data
    else:
        selected_city_data = sorted_city_data.head(top_k_cities)

    city_pollution_dot_map_data_by_pollutant[pollutant] = selected_city_data.reset_index(drop=True)

# Convenience outputs (requested final tables)
city_pollution_dot_map_data_no2 = city_pollution_dot_map_data_by_pollutant["NO2"].copy()
city_pollution_dot_map_data_pm10 = city_pollution_dot_map_data_by_pollutant["PM10"].copy()
city_pollution_dot_map_data_pm25 = city_pollution_dot_map_data_by_pollutant["PM25"].copy()

# Backward compatibility with existing downstream references.
city_pollution_dot_map_data = city_pollution_dot_map_data_no2.copy()

print(f"Analysis year: {city_analysis_year}")
print(f"Enhanced files loaded: {len(enhanced_paths)}")
print(f"Aggregation process used: {city_dot_map_aggregation_process}")
print("Filters applied: unit=ug/m3, station area=Urban, data coverage>75")
print(f"Minimum stations per city: {minimum_city_stations}")
print(f"Top-K cities selected per pollutant: {top_k_cities} (-1 means all)")

for pollutant in final_pollutants:
    final_df = city_pollution_dot_map_data_by_pollutant[pollutant]
    print()
    print(f"{pollutant} | Total cities available: {len(city_pollution_dot_map_data_full_by_pollutant[pollutant])}")
    print(f"{pollutant} | City rows ready for dot map: {len(final_df)}")
    display(final_df)

Analysis year: 2023
Enhanced files loaded: 8
Aggregation process used: Annual mean / 1 calendar year
Filters applied: unit=ug/m3, station area=Urban, data coverage>75
Minimum stations per city: 2
Top-K cities selected per pollutant: 30 (-1 means all)

NO2 | Total cities available: 55
NO2 | City rows ready for dot map: 30

,City,Pollutant,Latitude,Longitude,Mean Pollution (ug/m3),Stations Used,Pollutant-Year Points,City_Label
0,Torino,NO2,45.061675,7.662125,34.268000,4,1,Torino<br>Mean pollution: 34.27 ug/m3<br>Stati...
1,Palermo,NO2,38.122780,13.342380,33.461800,5,1,Palermo<br>Mean pollution: 33.46 ug/m3<br>Stat...
2,Milano (greater city),NO2,45.518421,9.196114,33.407286,14,1,Milano (greater city)<br>Mean pollution: 33.41...
3,Catania,NO2,37.518900,15.084500,32.940333,3,1,Catania<br>Mean pollution: 32.94 ug/m3<br>Stat...
4,Bergamo,NO2,45.693000,9.652800,32.063000,2,1,Bergamo<br>Mean pollution: 32.06 ug/m3<br>Stat...
5,Napoli (greater city),NO2,40.859420,14.317530,31.699900,10,1,Napoli (greater city)<br>Mean pollution: 31.7 ...
6,Roma,NO2,41.902950,12.507100,31.680000,10,1,Roma<br>Mean pollution: 31.68 ug/m3<br>Station...
7,Brescia,NO2,45.531675,10.235950,30.466000,4,1,Brescia<br>Mean pollution: 30.47 ug/m3<br>Stat...
8,Firenze,NO2,43.781867,11.263700,29.355000,3,1,Firenze<br>Mean pollution: 29.36 ug/m3<br>Stat...
9,Padova,NO2,45.402600,11.866250,29.352500,2,1,Padova<br>Mean pollution: 29.35 ug/m3<br>Stati...
10,Trento,NO2,46.083600,11.118200,29.221000,2,1,Trento<br>Mean pollution: 29.22 ug/m3<br>Stati...
11,Bologna,NO2,44.491500,11.341650,29.166500,2,1,Bologna<br>Mean pollution: 29.17 ug/m3<br>Stat...
12,Genova,NO2,44.409729,8.930871,28.671857,7,1,Genova<br>Mean pollution: 28.67 ug/m3<br>Stati...
13,Bari,NO2,41.112500,16.873700,27.344333,3,1,Bari<br>Mean pollution: 27.34 ug/m3<br>Station...
14,Venezia,NO2,45.475175,12.256100,27.299250,4,1,Venezia<br>Mean pollution: 27.3 ug/m3<br>Stati...
15,Modena,NO2,44.643300,10.905500,26.989000,2,1,Modena<br>Mean pollution: 26.99 ug/m3<br>Stati...
16,Bolzano,NO2,46.492333,11.341267,26.052333,3,1,Bolzano<br>Mean pollution: 26.05 ug/m3<br>Stat...
17,Pavia,NO2,45.189750,9.155800,25.548500,2,1,Pavia<br>Mean pollution: 25.55 ug/m3<br>Statio...
18,Novara,NO2,45.440000,8.620050,25.261000,2,1,Novara<br>Mean pollution: 25.26 ug/m3<br>Stati...
19,Treviso,NO2,45.665650,12.227350,24.903000,2,1,Treviso<br>Mean pollution: 24.9 ug/m3<br>Stati...
20,Rimini,NO2,44.057350,12.564450,24.858500,2,1,Rimini<br>Mean pollution: 24.86 ug/m3<br>Stati...
21,Cremona,NO2,45.137500,10.031250,24.594000,2,1,Cremona<br>Mean pollution: 24.59 ug/m3<br>Stat...
22,Verona,NO2,45.439150,10.997000,24.207000,2,1,Verona<br>Mean pollution: 24.21 ug/m3<br>Stati...
23,Lecco,NO2,45.849400,9.395800,23.976500,2,1,Lecco<br>Mean pollution: 23.98 ug/m3<br>Statio...
24,Campobasso,NO2,41.560550,14.673750,23.708500,2,1,Campobasso<br>Mean pollution: 23.71 ug/m3<br>S...
25,Parma,NO2,44.790950,10.334200,23.647500,2,1,Parma<br>Mean pollution: 23.65 ug/m3<br>Statio...
26,Reggio nell'Emilia,NO2,44.695550,10.643750,23.493000,2,1,Reggio nell'Emilia<br>Mean pollution: 23.49 ug...
27,Varese,NO2,45.826500,8.812250,23.246500,2,1,Varese<br>Mean pollution: 23.25 ug/m3<br>Stati...
28,Alessandria,NO2,44.913450,8.617600,23.089000,2,1,Alessandria<br>Mean pollution: 23.09 ug/m3<br>...
29,Messina,NO2,38.186300,15.549700,22.850000,2,1,Messina<br>Mean pollution: 22.85 ug/m3<br>Stat...

PM10 | Total cities available: 52
PM10 | City rows ready for dot map: 30

,City,Pollutant,Latitude,Longitude,Mean Pollution (ug/m3),Stations Used,Pollutant-Year Points,City_Label
0,Padova,PM10,45.394233,11.890833,32.472333,3,1,Padova<br>Mean pollution: 32.47 ug/m3<br>Stati...
1,Vicenza,PM10,45.546100,11.531933,31.598000,3,1,Vicenza<br>Mean pollution: 31.6 ug/m3<br>Stati...
2,Verona,PM10,45.439150,10.997000,31.541500,2,1,Verona<br>Mean pollution: 31.54 ug/m3<br>Stati...
3,Cremona,PM10,45.137500,10.031250,31.119000,2,1,Cremona<br>Mean pollution: 31.12 ug/m3<br>Stat...
4,Venezia,PM10,45.475175,12.256100,30.514750,4,1,Venezia<br>Mean pollution: 30.51 ug/m3<br>Stat...
5,Gela,PM10,37.067700,14.257450,30.353000,2,1,Gela<br>Mean pollution: 30.35 ug/m3<br>Station...
6,Treviso,PM10,45.665650,12.227350,30.321500,2,1,Treviso<br>Mean pollution: 30.32 ug/m3<br>Stat...
7,Brescia,PM10,45.531567,10.224967,29.554333,3,1,Brescia<br>Mean pollution: 29.55 ug/m3<br>Stat...
8,Torino,PM10,45.061675,7.662125,28.823000,4,1,Torino<br>Mean pollution: 28.82 ug/m3<br>Stati...
9,Alessandria,PM10,44.913450,8.617600,28.521500,2,1,Alessandria<br>Mean pollution: 28.52 ug/m3<br>...
10,Modena,PM10,44.643300,10.905500,28.447500,2,1,Modena<br>Mean pollution: 28.45 ug/m3<br>Stati...
11,Asti,PM10,44.901550,8.201500,28.269000,2,1,Asti<br>Mean pollution: 28.27 ug/m3<br>Station...
12,Catania,PM10,37.518900,15.084500,27.916333,3,1,Catania<br>Mean pollution: 27.92 ug/m3<br>Stat...
13,Pavia,PM10,45.189750,9.155800,27.817500,2,1,Pavia<br>Mean pollution: 27.82 ug/m3<br>Statio...
14,Milano (greater city),PM10,45.532250,9.200513,27.400000,8,1,Milano (greater city)<br>Mean pollution: 27.4 ...
15,Reggio nell'Emilia,PM10,44.695550,10.643750,26.864500,2,1,Reggio nell'Emilia<br>Mean pollution: 26.86 ug...
16,Parma,PM10,44.790950,10.334200,26.716000,2,1,Parma<br>Mean pollution: 26.72 ug/m3<br>Statio...
17,Terni,PM10,42.564700,12.642033,25.987667,3,1,Terni<br>Mean pollution: 25.99 ug/m3<br>Statio...
18,Piacenza,PM10,45.043600,9.681250,25.881000,2,1,Piacenza<br>Mean pollution: 25.88 ug/m3<br>Sta...
19,Napoli (greater city),PM10,40.846522,14.329322,25.730444,9,1,Napoli (greater city)<br>Mean pollution: 25.73...
20,Palermo,PM10,38.122780,13.342380,25.712000,5,1,Palermo<br>Mean pollution: 25.71 ug/m3<br>Stat...
21,Rimini,PM10,44.057350,12.564450,25.528000,2,1,Rimini<br>Mean pollution: 25.53 ug/m3<br>Stati...
22,Siracusa,PM10,37.078300,15.283067,25.271667,3,1,Siracusa<br>Mean pollution: 25.27 ug/m3<br>Sta...
23,Caserta,PM10,41.081200,14.337950,25.054000,2,1,Caserta<br>Mean pollution: 25.05 ug/m3<br>Stat...
24,Ferrara,PM10,44.833750,11.631400,24.831500,2,1,Ferrara<br>Mean pollution: 24.83 ug/m3<br>Stat...
25,Bergamo,PM10,45.693000,9.652800,24.823000,2,1,Bergamo<br>Mean pollution: 24.82 ug/m3<br>Stat...
26,Ravenna,PM10,44.424300,12.206150,24.460500,2,1,Ravenna<br>Mean pollution: 24.46 ug/m3<br>Stat...
27,Roma,PM10,41.902950,12.507100,24.300200,10,1,Roma<br>Mean pollution: 24.3 ug/m3<br>Stations...
28,Firenze,PM10,43.777725,11.260075,23.931750,4,1,Firenze<br>Mean pollution: 23.93 ug/m3<br>Stat...
29,Novara,PM10,45.440000,8.620050,23.503000,2,1,Novara<br>Mean pollution: 23.5 ug/m3<br>Statio...

PM25 | Total cities available: 24
PM25 | City rows ready for dot map: 24

,City,Pollutant,Latitude,Longitude,Mean Pollution (ug/m3),Stations Used,Pollutant-Year Points,City_Label
0,Vicenza,PM25,45.546250,11.530800,23.493000,2,1,Vicenza<br>Mean pollution: 23.49 ug/m3<br>Stat...
1,Venezia,PM25,45.467400,12.292650,21.402000,2,1,Venezia<br>Mean pollution: 21.4 ug/m3<br>Stati...
2,Cremona,PM25,45.137500,10.031250,21.295500,2,1,Cremona<br>Mean pollution: 21.3 ug/m3<br>Stati...
3,Brescia,PM25,45.521600,10.233133,18.233667,3,1,Brescia<br>Mean pollution: 18.23 ug/m3<br>Stat...
4,Milano (greater city),PM25,45.530917,9.193383,17.904000,6,1,Milano (greater city)<br>Mean pollution: 17.9 ...
5,Torino,PM25,45.056967,7.656767,17.303667,3,1,Torino<br>Mean pollution: 17.3 ug/m3<br>Statio...
6,Terni,PM25,42.564700,12.642033,15.664000,3,1,Terni<br>Mean pollution: 15.66 ug/m3<br>Statio...
7,Napoli (greater city),PM25,40.840567,14.364267,14.918500,6,1,Napoli (greater city)<br>Mean pollution: 14.92...
8,Ancona,PM25,43.608800,13.500450,14.547500,2,1,Ancona<br>Mean pollution: 14.55 ug/m3<br>Stati...
9,Prato,PM25,43.873750,11.098600,13.608500,2,1,Prato<br>Mean pollution: 13.61 ug/m3<br>Statio...
10,Bologna,PM25,44.491500,11.341650,13.369000,2,1,Bologna<br>Mean pollution: 13.37 ug/m3<br>Stat...
11,Palermo,PM25,38.113500,13.350333,13.134667,3,1,Palermo<br>Mean pollution: 13.13 ug/m3<br>Stat...
12,Roma,PM25,41.907680,12.493640,12.672400,5,1,Roma<br>Mean pollution: 12.67 ug/m3<br>Station...
13,Lecce,PM25,40.358150,18.174900,12.629500,2,1,Lecce<br>Mean pollution: 12.63 ug/m3<br>Statio...
14,Firenze,PM25,43.779900,11.279850,12.525000,2,1,Firenze<br>Mean pollution: 12.52 ug/m3<br>Stat...
15,Pescara,PM25,42.461400,14.223900,12.521000,2,1,Pescara<br>Mean pollution: 12.52 ug/m3<br>Stat...
16,Perugia,PM25,43.098800,12.394233,12.482333,3,1,Perugia<br>Mean pollution: 12.48 ug/m3<br>Stat...
17,Pisa,PM25,43.726400,10.406150,12.420500,2,1,Pisa<br>Mean pollution: 12.42 ug/m3<br>Station...
18,Bari,PM25,41.118450,16.880700,12.110500,2,1,Bari<br>Mean pollution: 12.11 ug/m3<br>Station...
19,Caserta,PM25,41.081200,14.337950,10.943000,2,1,Caserta<br>Mean pollution: 10.94 ug/m3<br>Stat...
20,Genova,PM25,44.413100,8.944900,9.827500,4,1,Genova<br>Mean pollution: 9.83 ug/m3<br>Statio...
21,La Spezia,PM25,44.108775,9.838100,9.645750,4,1,La Spezia<br>Mean pollution: 9.65 ug/m3<br>Sta...
22,Savona,PM25,44.314050,8.479150,9.368500,2,1,Savona<br>Mean pollution: 9.37 ug/m3<br>Statio...
23,Livorno,PM25,43.537350,10.325700,8.988000,2,1,Livorno<br>Mean pollution: 8.99 ug/m3<br>Stati...

In [272]:
# calculate pollution per capita for each country
country_reference_year = 2022

country_pollution_path = derived_dir / f"country_population_pm25_{country_reference_year}.csv"
if not country_pollution_path.exists():
    raise FileNotFoundError(
        f"Missing {country_pollution_path}. Run the 'save country/population/produced pollution' block first."
    )

country_pollution_reference = pd.read_csv(country_pollution_path)
required_country_cols = ["Country", "Year", "Population", "PM25_Produced_Tonnes"]
missing_country_cols = [col for col in required_country_cols if col not in country_pollution_reference.columns]
if missing_country_cols:
    raise ValueError(
        "Country pollution dataset is missing required columns: " + ", ".join(missing_country_cols)
    )

country_pollution_reference["Year"] = pd.to_numeric(country_pollution_reference["Year"], errors="coerce")
country_pollution_reference["Population"] = pd.to_numeric(country_pollution_reference["Population"], errors="coerce")
country_pollution_reference["PM25_Produced_Tonnes"] = pd.to_numeric(
    country_pollution_reference["PM25_Produced_Tonnes"], errors="coerce"
)

country_pollution_per_capita_2022 = (
    country_pollution_reference[
        country_pollution_reference["Year"].eq(country_reference_year)
    ]
    .dropna(subset=["Population", "PM25_Produced_Tonnes"])
    .copy()
)
country_pollution_per_capita_2022 = country_pollution_per_capita_2022[
    country_pollution_per_capita_2022["Population"] > 0
]

country_pollution_per_capita_2022["PM25_Produced_Kg_per_Person"] = (
    country_pollution_per_capita_2022["PM25_Produced_Tonnes"] * 1000
    / country_pollution_per_capita_2022["Population"]
)

country_pollution_per_capita_2022 = country_pollution_per_capita_2022.sort_values(
    "PM25_Produced_Kg_per_Person",
    ascending=False,
).reset_index(drop=True)

country_pollution_per_capita_2022[["PM25_Produced_Tonnes", "PM25_Produced_Kg_per_Person"]] = (
    country_pollution_per_capita_2022[["PM25_Produced_Tonnes", "PM25_Produced_Kg_per_Person"]].round(6)
)

country_pollution_per_capita_2022

,Country,Country Code,Year,Population,PM25_Produced_Tonnes,PM25_Produced_Kg_per_Person
0,France,FRA,2022,68184457,393307.885,5.768292
1,Italy,ITA,2022,59013667,322061.965,5.457413
2,Spain,ESP,2022,47786102,210383.324,4.402605
3,Germany,DEU,2022,83177813,236738.865,2.846178
4,United Kingdom,GBR,2022,67604000,123137.001,1.821445

### Plotting

In [273]:
# Italy forest map
import pyogrio

forest_path = derived_dir / "CLC2018_IT_forest_derived.gpkg"
border_path = derived_dir / "GISCO_country_borders_derived.gpkg"

forest_layer = pyogrio.list_layers(forest_path)[0][0]
forest_it = gpd.read_file(forest_path, layer=forest_layer)

border_layer = pyogrio.list_layers(border_path)[0][0]
border_it = gpd.read_file(border_path, layer=border_layer)

forest_it = forest_it.copy()
forest_it["Code_18"] = forest_it["Code_18"].astype(str).str.zfill(3)

forest_styles = {
    "311": {"label": "Broad-leaved forest", "color": "#2E7D32"},
    "312": {"label": "Coniferous forest", "color": "#1B5E20"},
    "313": {"label": "Mixed forest", "color": "#66BB6A"},
}

graph_png_path = graphs_dir / "italy_forest_map.png"

plot_polygon_map(
    data=forest_it,
    title="Italy Forest Map",
    category_col="Code_18",
    class_styles=forest_styles,
    border_data=border_it,
    output_path=graph_png_path,
    figsize=(9, 11),
    style_config=polygon_map_style,
)

DataSourceError: Data/Derived/CLC2018_IT_forest_derived.gpkg: No such file or directory

In [ ]:
# Italy mountains map
import pyogrio

mountains_path = derived_dir / "CLC2018_IT_mountains_derived.gpkg"
border_path = derived_dir / "GISCO_country_borders_derived.gpkg"

mountains_layer = pyogrio.list_layers(mountains_path)[0][0]
mountains_it = gpd.read_file(mountains_path, layer=mountains_layer)

border_layer = pyogrio.list_layers(border_path)[0][0]
border_it = gpd.read_file(border_path, layer=border_layer)

mountains_it = mountains_it.copy()
mountains_it["Code_18"] = mountains_it["Code_18"].astype(str).str.zfill(3)

mountain_styles = {
    "332": {"label": "Bare rocks", "color": "#8D6E63"},
    "333": {"label": "Sparsely vegetated areas", "color": "#BCAAA4"},
    "335": {"label": "Glaciers and perpetual snow", "color": "#ECEFF1"},
}

graph_png_path = graphs_dir / "italy_mountains_map.png"

plot_polygon_map(
    data=mountains_it,
    title="Italy Mountain Areas",
    category_col="Code_18",
    class_styles=mountain_styles,
    border_data=border_it,
    output_path=graph_png_path,
    figsize=(9, 11),
    style_config=polygon_map_style
)

DataSourceError: Data/Derived/CLC2018_IT_mountains_derived.gpkg: No such file or directory

In [274]:
# METALS

df_it = dfs_industry["2023_IT_industrial_derived"].copy()

df_metals = df_it[
    df_it["eprtr_sectors"].str.upper() == "METALS"
].copy()

df_metals["label"] = df_metals["siteName"].astype(str)

metals_map_fig = create_dot_distribution_map(
    data=df_metals,
    lat_col="Latitude",
    lon_col="Longitude",
    label_col="label",
    title="Metal Plants in Italy",
    map_engine="geo",
    style_config={**dot_distribution_map_style, "points_label": "Metal Plants"}
)

graph_png_path = graphs_dir / "metals_dot_map.png"
await save_plotly_graph_png(
    metals_map_fig,
    graph_png_path,
    width=2200,
    height=1200,
    scale=2,
    force_canvas_size=True
)

# ENERGY

df_it = dfs_industry["2023_IT_industrial_derived"].copy()

df_energy = df_it[
    df_it["eprtr_sectors"].str.upper() == "ENERGY"
].copy()

df_energy["label"] = df_energy["siteName"].astype(str)

energy_map_fig = create_dot_distribution_map(
    data=df_energy,
    lat_col="Latitude",
    lon_col="Longitude",
    label_col="label",
    title="Energy Plants in Italy",
    map_engine="geo",
    style_config={**dot_distribution_map_style, "points_label": "Energy Plants"}
)

graph_png_path = graphs_dir / "energy_dot_map.png"
await save_plotly_graph_png(
    energy_map_fig,
    graph_png_path,
    width=2200,
    height=1200,
    scale=2,
    force_canvas_size=True
)

# MINERALS

df_it = dfs_industry["2023_IT_industrial_derived"].copy()

df_minerals = df_it[
    df_it["eprtr_sectors"].str.upper() == "MINERALS"
].copy()

df_minerals["label"] = df_minerals["siteName"].astype(str)

minerals_map_fig = create_dot_distribution_map(
    data=df_minerals,
    lat_col="Latitude",
    lon_col="Longitude",
    label_col="label",
    title="Mineral Plants in Italy",
    map_engine="geo",
    style_config={**dot_distribution_map_style, "points_label": "Mineral Plants"}
)

graph_png_path = graphs_dir / "minerals_dot_map.png"
await save_plotly_graph_png(
    minerals_map_fig,
    graph_png_path,
    width=2200,
    height=1200,
    scale=2,
    force_canvas_size=True
)

# CHEMICALS

df_it = dfs_industry["2023_IT_industrial_derived"].copy()

df_chemicals = df_it[
    df_it["eprtr_sectors"].str.upper() == "CHEMICALS"
].copy()

df_chemicals["label"] = df_chemicals["siteName"].astype(str)

chemicals_map_fig = create_dot_distribution_map(
    data=df_chemicals,
    lat_col="Latitude",
    lon_col="Longitude",
    label_col="label",
    title="Chemical Plants in Italy",
    map_engine="geo",
    style_config={**dot_distribution_map_style, "points_label": "Chemical Plants"}
)

graph_png_path = graphs_dir / "chemicals_dot_map.png"
await save_plotly_graph_png(
    chemicals_map_fig,
    graph_png_path,
    width=2200,
    height=1200,
    scale=2,
    force_canvas_size=True
)

Saved PNG graph to: Assets/Graphs/metals_dot_map.png
Saved PNG graph to: Assets/Graphs/energy_dot_map.png
Saved PNG graph to: Assets/Graphs/minerals_dot_map.png
Saved PNG graph to: Assets/Graphs/chemicals_dot_map.png

In [275]:
# roma pie chart
city = "roma"

city_row = dfs_pie["IT_city_land_cover"][
    dfs_pie["IT_city_land_cover"]["city"].str.strip().str.lower() == city
].iloc[0]

labels = ["Industry Area", "Green Area", "Urban Area"]
values = [
    city_row["industry_percent"],
    city_row["green_percent"],
    city_row["urban_percent"],
]

bar_style = CHART_STYLE_PRESETS.get("horizontal_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}
vertical_style = CHART_STYLE_PRESETS.get("vertical_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}

paper_bg = bar_style.get("paper_bgcolor", "#162036")
plot_bg = bar_style.get("plot_bgcolor", "#213052")
font_family = vertical_style.get("font_family", "Arial")
font_color = vertical_style.get("font_color", "#e8eef7")
title_size = vertical_style.get("title_font_size", 25)

pie_colors = ["#007CCE", "#0097c5", "#105490"]

fig = go.Figure(
    go.Pie(
        labels=labels,
        values=values,
        hole=0,
        sort=False,
        direction="clockwise",
        textinfo="percent",
        textposition="inside",                 # force inside
        textfont=dict(color="white", size=18), # slightly smaller for fit
        marker=dict(
            colors=pie_colors,
            line=dict(width=0)
        ),
        hovertemplate="%{label}<br>Share: %{value:.2f}%<extra></extra>",
        showlegend=True
    )
)

fig.update_layout(
    title=dict(
        text="<b>Land Coverage in Rome</b>",
        x=0.02,
        y=0.95,
        font=dict(size=title_size, color="#FFFFFF"),
    ),
    paper_bgcolor=paper_bg,
    plot_bgcolor=plot_bg,
    font=dict(family=font_family, color=font_color, size=16),
    margin=dict(l=40, r=40, t=110, b=40),
    width=900,
    height=650,
    legend=dict(
        x=1.02,
        y=0.5,
        xanchor="left",
        yanchor="middle",
        font=dict(color=font_color, size=18),
        bgcolor="rgba(0,0,0,0)"
    )
)

fig.show()

graph_png_path = graphs_dir / "roma_land_cover_pie.png"

await save_plotly_graph_png(
    fig,
    graph_png_path,
    width=900,
    height=650,
    scale=2
)

Saved PNG graph to: Assets/Graphs/roma_land_cover_pie.png

In [276]:
# milan, naples, torino

cities = ["milano", "napoli", "torino"]

labels = ["Industry Area", "Green Area", "Urban Area"]

bar_style = CHART_STYLE_PRESETS.get("horizontal_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}
vertical_style = CHART_STYLE_PRESETS.get("vertical_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}

paper_bg = bar_style.get("paper_bgcolor", "#162036")
plot_bg = bar_style.get("plot_bgcolor", "#213052")
font_family = vertical_style.get("font_family", "Arial")
font_color = vertical_style.get("font_color", "#e8eef7")
title_size = vertical_style.get("title_font_size", 25)

pie_colors = ["#007CCE", "#0097c5", "#105490"]

for city in cities:
    city_row = dfs_pie["IT_city_land_cover"][
        dfs_pie["IT_city_land_cover"]["city"].str.strip().str.lower() == city
    ]

    if city_row.empty:
        print(f"{city} not found in IT_city_land_cover")
        continue

    city_row = city_row.iloc[0]

    values = [
        city_row["industry_percent"],
        city_row["green_percent"],
        city_row["urban_percent"],
    ]

    fig = go.Figure(
        go.Pie(
            labels=labels,
            values=values,
            hole=0,
            sort=False,
            direction="clockwise",
            textinfo="percent",                      # percent only
            insidetextorientation="horizontal",     # prevent vertical %
            textfont=dict(color=font_color, size=18),
            marker=dict(
                colors=pie_colors,
                line=dict(width=0)
            ),
            hovertemplate="%{label}<br>Share: %{value:.2f}%<extra></extra>",
            showlegend=True
        )
    )

    fig.update_layout(
        title=dict(
            text=f"<b>Land Coverage in {city.title()}</b>",
            x=0.02,
            y=0.95,
            font=dict(size=title_size, color="#FFFFFF"),
        ),
        paper_bgcolor=paper_bg,
        plot_bgcolor=plot_bg,
        font=dict(family=font_family, color=font_color, size=16),
        margin=dict(l=40, r=180, t=110, b=40),
        width=900,
        height=650,
        legend=dict(
            x=1.02,
            y=0.5,
            xanchor="left",
            yanchor="middle",
            font=dict(color=font_color, size=18),
            bgcolor="rgba(0,0,0,0)",
            itemsizing="constant"   # bigger color blocks
        )
    )

    fig.show()

    graph_png_path = graphs_dir / f"{city}_land_cover_pie.png"

    await save_plotly_graph_png(
        fig,
        graph_png_path,
        width=900,
        height=650,
        scale=2
    )

Saved PNG graph to: Assets/Graphs/milano_land_cover_pie.png

Saved PNG graph to: Assets/Graphs/napoli_land_cover_pie.png

Saved PNG graph to: Assets/Graphs/torino_land_cover_pie.png

In [277]:
# Compute averages
avg_industry = dfs_pie["IT_city_land_cover"]["industry_percent"].mean()
avg_green = dfs_pie["IT_city_land_cover"]["green_percent"].mean()
avg_urban = dfs_pie["IT_city_land_cover"]["urban_percent"].mean()

labels = ["Industry Area", "Green Area", "Urban Area"]
values = [avg_industry, avg_green, avg_urban]

bar_style = CHART_STYLE_PRESETS.get("horizontal_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}
vertical_style = CHART_STYLE_PRESETS.get("vertical_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}

paper_bg = bar_style.get("paper_bgcolor", "#162036")
plot_bg = bar_style.get("plot_bgcolor", "#213052")
font_family = vertical_style.get("font_family", "Arial")
font_color = vertical_style.get("font_color", "#e8eef7")
title_size = vertical_style.get("title_font_size", 25)

pie_colors = ["#007CCE", "#0097c5", "#105490"]

fig = go.Figure(
    go.Pie(
        labels=labels,
        values=values,
        hole=0,
        sort=False,
        direction="clockwise",
        textinfo="percent",
        textposition="inside",
        insidetextorientation="horizontal",
        textfont=dict(color=font_color, size=18),
        marker=dict(
            colors=pie_colors,
            line=dict(width=0)
        ),
        hovertemplate="%{label}<br>Average share: %{value:.2f}%<extra></extra>",
        showlegend=True
    )
)

fig.update_layout(
    title=dict(
        text="<b>Average Land Coverage Across Cities</b>",
        x=0.02,
        y=0.95,
        font=dict(size=title_size, color="#FFFFFF"),
    ),
    paper_bgcolor=paper_bg,
    plot_bgcolor=plot_bg,
    font=dict(family=font_family, color=font_color, size=16),
    margin=dict(l=40, r=180, t=110, b=40),
    width=900,
    height=650,
    legend=dict(
        x=1.02,
        y=0.5,
        xanchor="left",
        yanchor="middle",
        font=dict(color=font_color, size=18),
        bgcolor="rgba(0,0,0,0)",
        itemsizing="constant"
    )
)

fig.show()

graph_png_path = graphs_dir / "average_land_cover_pie.png"

await save_plotly_graph_png(
    fig,
    graph_png_path,
    width=900,
    height=650,
    scale=2
)

Saved PNG graph to: Assets/Graphs/average_land_cover_pie.png

In [278]:
# Build annual mean comparison chart
fig = create_comparison_horizontal_barchart(
    data=annual_mean_pollutants,
    category_col="Air Pollutant",
    group_col="Year",
    value_col="Air Pollution Level",
    primary_group=2023,
    secondary_group=2024,
    title="Annual Mean Air Pollution Level",
    xaxis_title="Air Pollution Level (ug/m3)",
    primary_label="2023",
    secondary_label="2024",
    sort_ascending=True,
    show_value_labels=True,
    style_config=comparison_barchart_style,
)

graph_png_path = graphs_dir / "annual_mean_pollutants_barchart.png"
await save_plotly_graph_png(fig, graph_png_path, width=900, height=700, scale=2)

Saved PNG graph to: Assets/Graphs/annual_mean_pollutants_barchart.png

In [279]:
# pie chart of annual mean comparison
# Filter 2023 data
annual_mean_2023 = annual_mean_pollutants[
    annual_mean_pollutants["Year"] == 2023
]

labels = annual_mean_2023["Air Pollutant"]
values = annual_mean_2023["Air Pollution Level"]

bar_style = CHART_STYLE_PRESETS.get("horizontal_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}
vertical_style = CHART_STYLE_PRESETS.get("vertical_bar", {}) if "CHART_STYLE_PRESETS" in globals() else {}

paper_bg = bar_style.get("paper_bgcolor", "#162036")
plot_bg = bar_style.get("plot_bgcolor", "#213052")
font_family = vertical_style.get("font_family", "Arial")
font_color = vertical_style.get("font_color", "#e8eef7")
title_size = vertical_style.get("title_font_size", 25)

pie_colors = [ "#6DAFFF", "#105490","#007CCE", "#0097c5"]

fig = go.Figure(
    go.Pie(
        labels=labels,
        values=values,
        hole=0,
        sort=False,
        direction="clockwise",
        textinfo="percent",
        textposition="inside",
        insidetextorientation="horizontal",
        textfont=dict(color=font_color, size=18),
        marker=dict(
            colors=pie_colors,
            line=dict(width=0)
        ),
        hovertemplate="%{label}<br>Annual Mean: %{value:.2f} ug/m3<extra></extra>",
        showlegend=True
    )
)

fig.update_layout(
    title=dict(
        text="<b>2023 Annual Mean Pollutant Distribution</b>",
        x=0.02,
        y=0.95,
        font=dict(size=title_size, color="#FFFFFF"),
    ),
    paper_bgcolor=paper_bg,
    plot_bgcolor=plot_bg,
    font=dict(family=font_family, color=font_color, size=16),
    margin=dict(l=40, r=180, t=110, b=40),
    width=900,
    height=650,
    legend=dict(
        x=1.02,
        y=0.5,
        xanchor="left",
        yanchor="middle",
        font=dict(color=font_color, size=18),
        bgcolor="rgba(0,0,0,0)",
        itemsizing="constant"
    )
)

fig.show()

graph_png_path = graphs_dir / "annual_mean_pollutants_2023_pie.png"

await save_plotly_graph_png(
    fig,
    graph_png_path,
    width=900,
    height=650,
    scale=2
)

Saved PNG graph to: Assets/Graphs/annual_mean_pollutants_2023_pie.png

In [280]:
# Render usage chart
fig = create_horizontal_barchart(
    data=data_aggregation_usage,
    category_col="Data Aggregation Process",
    value_col="Total # of Usage",
    title="Usage of All Data Aggregation Processes",
    xaxis_title="Total # of Usage",
    bar_label="Usage",
    show_value_labels=True,
    auto_height=True,
    style_config=bar_chart_style,
)

graph_png_path = graphs_dir / "data_aggregation_processes_usage_barchart.png"
await save_plotly_graph_png(fig, graph_png_path, width=2000, height=1700, scale=2)

Saved PNG graph to: Assets/Graphs/data_aggregation_processes_usage_barchart.png

In [281]:
air_pollution_boxplot_fig = create_boxplot(
    data=air_pollution_boxplot_data,
    category_col="Data Aggregation Process",
    value_col="Air Pollution Level",
    title="Air Pollution Levels (ug/m3) - Log Scale",
    xaxis_title="Air Pollution Level (ug/m3)",
    yaxis_title="Aggregation Method",
    use_log_x=True,
    style_config=boxplot_style,
)

plot_height = air_pollution_boxplot_fig.layout.height or 650
graph_png_path = graphs_dir / "air_pollution_boxplot.png"
await save_plotly_graph_png(air_pollution_boxplot_fig, graph_png_path, width=1600, height=plot_height, scale=2)

Saved PNG graph to: Assets/Graphs/air_pollution_boxplot.png

In [282]:
dot_distribution_map_fig = create_dot_distribution_map(
    data=air_quality_station_points,
    lat_col="Latitude",
    lon_col="Longitude",
    label_col="Station_ID",
    title="Air Quality Stations in Italy",
    map_engine="geo",
    style_config=dot_distribution_map_style,
)

graph_png_path = graphs_dir / "air_quality_stations_dot_map.png"
await save_plotly_graph_png(dot_distribution_map_fig, graph_png_path, width=2200, height=1200, scale=2, force_canvas_size=True)

Saved PNG graph to: Assets/Graphs/air_quality_stations_dot_map.png

In [283]:
station_area_pollutant_fig = create_vertical_grouped_barchart(
    data=station_area_pollutant_stats,
    category_col="Air Quality Station Area",
    group_col="Air Pollutant",
    value_col="Air Pollution Level",
    primary_group="NO2",
    secondary_groups=["O3", "PM10", "PM2.5"],
    title="Annual Mean Pollutant Concentration by Geographic Area",
    xaxis_title="Station Area",
    yaxis_title="Average Concentration (ug/m3)",
    category_order=["Rural", "Suburban", "Urban"],
    style_config=vertical_barchart_style,
)

graph_png_path = graphs_dir / "annual_mean_pollutant_concentration_barchart.png"
await save_plotly_graph_png(station_area_pollutant_fig, graph_png_path, width=2200, height=1200, scale=2)

Saved PNG graph to: Assets/Graphs/annual_mean_pollutant_concentration_barchart.png

In [284]:
#scatter plot with linear regression
pollutants = ["NO2", "O3", "PM10", "PM25"]

fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=[
        "NO2 vs Log Population",
        "O3 vs Log Population",
        "PM10 vs Log Population",
        "PM25 vs Log Population"
    ],
    horizontal_spacing=0.10,
    vertical_spacing=0.12
)

positions = {
    "NO2": (1, 1),
    "O3": (1, 2),
    "PM10": (2, 1),
    "PM25": (2, 2)
}

for pollutant in pollutants:
    row, col = positions[pollutant]

    x = df_pollution_pop["log_population"]
    y = df_pollution_pop[pollutant]

    # Retrieve stored regression results
    stats_row = df_regression_results[
        df_regression_results["Pollutant"] == pollutant
    ].iloc[0]

    intercept = stats_row["Intercept"]
    slope = stats_row["Slope_log_population"]
    r_squared = stats_row["R_squared"]
    p_value = stats_row["p_value"]

    # Scatter points
    fig.add_trace(
        go.Scatter(
            x=x,
            y=y,
            mode="markers",
            marker=dict(size=7, color="#00FFF2"),
            showlegend=False,
            text=df_pollution_pop["City"],
            hovertemplate=(
                "City: %{text}<br>"
                "log(Population): %{x:.2f}<br>"
                + pollutant + ": %{y:.2f}<extra></extra>"
            ),
        ),
        row=row,
        col=col
    )

    # Regression line from stored slope & intercept
    x_line = np.linspace(x.min(), x.max(), 100)
    y_line = intercept + slope * x_line

    fig.add_trace(
        go.Scatter(
            x=x_line,
            y=y_line,
            mode="lines",
            line=dict(color="#25b2ef", width=2.5),
            showlegend=False,
            hoverinfo="skip"
        ),
        row=row,
        col=col
    )

    # Axis labels
    fig.update_xaxes(title_text="log(Population)", row=row, col=col)
    fig.update_yaxes(title_text=f"{pollutant} (µg/m³)", row=row, col=col)

    # Add regression statistics inside subplot
    subplot_index = list(positions.values()).index((row, col)) + 1
    xref = "x domain" if subplot_index == 1 else f"x{subplot_index} domain"
    yref = "y domain" if subplot_index == 1 else f"y{subplot_index} domain"

    fig.add_annotation(
        x=0.03,
        y=0.97,
        xref=xref,
        yref=yref,
        text=f"R² = {r_squared:.3f}<br>p = {p_value:.3g}",
        showarrow=False,
        align="left",
        font=dict(size=12, color="white"),
        bgcolor="rgba(22,32,54,0.75)"
    )

fig.update_layout(
    title="Population and Annual Mean Pollutant Levels",
    paper_bgcolor="#162036",
    plot_bgcolor="#162036",
    font=dict(color="white"),
    title_font_size=24,
    width=1100,
    height=850
)

graph_png_path = graphs_dir / "population_pollutant_regressions.png"
await save_plotly_graph_png(fig, graph_png_path, width=1100, height=850, scale=2)
# note that R2 is .309 meaning population explains ~ 31% of variation in NO2

Saved PNG graph to: Assets/Graphs/population_pollutant_regressions.png

In [285]:
# most polluted cities dot maps by pollutant (NO2, PM10, PM2.5)

required_pollutants = ["NO2", "PM10", "PM25"]

if "city_pollution_dot_map_data_by_pollutant" not in globals() or not city_pollution_dot_map_data_by_pollutant:
    raise ValueError(
        "`city_pollution_dot_map_data_by_pollutant` is not available. "
        "Run the '# mean pollution per city for 2023 (NO2, PM10, PM2.5)' EDA block first."
    )

plot_year = globals().get("city_analysis_year", 2023)

pollutant_display_names = {
    "NO2": "NO2",
    "PM10": "PM10",
    "PM25": "PM2.5",
}

# Final map-ready tables expected by create_dot_distribution_map.
city_dot_map_ready_by_pollutant = {
    pollutant: city_pollution_dot_map_data_by_pollutant.get(pollutant, pd.DataFrame()).copy()
    for pollutant in required_pollutants
}

missing_pollutant_tables = [
    pollutant
    for pollutant, df in city_dot_map_ready_by_pollutant.items()
    if df.empty
]
if missing_pollutant_tables:
    raise ValueError(
        "Missing city-level map data for pollutant(s): " + ", ".join(missing_pollutant_tables)
    )

required_map_columns = ["Latitude", "Longitude", "City_Label", "Mean Pollution (ug/m3)"]
for pollutant, pollutant_df in city_dot_map_ready_by_pollutant.items():
    missing_columns = [col for col in required_map_columns if col not in pollutant_df.columns]
    if missing_columns:
        raise ValueError(
            f"{pollutant} map data is missing required column(s): {', '.join(missing_columns)}"
        )

most_polluted_cities_dot_map_figs = {}

for pollutant in required_pollutants:
    city_map_plot_data = city_dot_map_ready_by_pollutant[pollutant]
    display_name = pollutant_display_names.get(pollutant, pollutant)

    pollutant_fig = create_dot_distribution_map(
        data=city_map_plot_data,
        lat_col="Latitude",
        lon_col="Longitude",
        label_col="City_Label",
        title=f"Most Polluted Cities in {plot_year} ({display_name} Mean Pollution)",
        map_engine="geo",
        map_style="carto-darkmatter",
        size_col="Mean Pollution (ug/m3)",
        use_variable_dot_size=True,
        size_range=(3, 20),
        style_config={**dot_distribution_map_style, "points_label": "Cities"},
    )

    graph_png_path = graphs_dir / f"most_polluted_cities_dot_map_{pollutant.lower()}_{plot_year}.png"
    await save_plotly_graph_png(
        pollutant_fig,
        graph_png_path,
        width=2200,
        height=1200,
        scale=2,
        force_canvas_size=True,
    )
    print(f"Saved PNG graph to: {graph_png_path}")

    display(pollutant_fig)
    most_polluted_cities_dot_map_figs[pollutant] = pollutant_fig

most_polluted_cities_dot_map_figs

Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_no2_2023.png
Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_no2_2023.png

Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_pm10_2023.png
Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_pm10_2023.png

Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_pm25_2023.png
Saved PNG graph to: Assets/Graphs/most_polluted_cities_dot_map_pm25_2023.png

{'NO2': Figure({
     'data': [{'hoverinfo': 'skip',
               'lat': {'bdata': ('i/1l9+SHRkArTUpBtw9DQEWhJKJbwk' ... 'KDwMrpRkD+Q/rt63RGQFafq63YF0NA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('vHSTGASmHkDlm21uTK8qQK/XdhdpZC' ... 'pkO9+fIUDqBDQRNjwhQO84RUdyGS9A'),
                       'dtype': 'f8'},
               'marker': {'color': 'rgba(34, 211, 207, 0.30)',
                          'opacity': 0.55,
                          'size': {'bdata': ('AAAAAAAANkDq+jX9tsw0QN6xK8Hvtz' ... 'RQCoJcFkDy2iHBYWwVQAAAAAAAABRA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'type': 'scattergeo'},
              {'hovertemplate': '<b>%{text}</b><extra></extra>',
               'lat': {'bdata': ('i/1l9+SHRkArTUpBtw9DQEWhJKJbwk' ... 'KDwMrpRkD+Q/rt63RGQFafq63YF0NA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('vHSTGASmHkDlm21uTK8qQK/XdhdpZC' ... 'pkO9+fIUDqBDQRNjwhQO84RUdyGS9A'),
                       'dtype': 'f8'},
               'marker': {'color': '#22d3cf',
                          'line': {'color': '#b6fff8', 'width': 0.5},
                          'opacity': 0.95,
                          'size': {'bdata': ('AAAAAAAANEDq+jX9tswyQN6xK8Hvtz' ... 'igFAS5DEDjtUOCw9gKQAAAAAAAAAhA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'text': array(['Torino<br>Mean pollution: 34.27 ug/m3<br>Stations used: 4',
                              'Palermo<br>Mean pollution: 33.46 ug/m3<br>Stations used: 5',
                              'Milano (greater city)<br>Mean pollution: 33.41 ug/m3<br>Stations used: 14',
                              'Catania<br>Mean pollution: 32.94 ug/m3<br>Stations used: 3',
                              'Bergamo<br>Mean pollution: 32.06 ug/m3<br>Stations used: 2',
                              'Napoli (greater city)<br>Mean pollution: 31.7 ug/m3<br>Stations used: 10',
                              'Roma<br>Mean pollution: 31.68 ug/m3<br>Stations used: 10',
                              'Brescia<br>Mean pollution: 30.47 ug/m3<br>Stations used: 4',
                              'Firenze<br>Mean pollution: 29.36 ug/m3<br>Stations used: 3',
                              'Padova<br>Mean pollution: 29.35 ug/m3<br>Stations used: 2',
                              'Trento<br>Mean pollution: 29.22 ug/m3<br>Stations used: 2',
                              'Bologna<br>Mean pollution: 29.17 ug/m3<br>Stations used: 2',
                              'Genova<br>Mean pollution: 28.67 ug/m3<br>Stations used: 7',
                              'Bari<br>Mean pollution: 27.34 ug/m3<br>Stations used: 3',
                              'Venezia<br>Mean pollution: 27.3 ug/m3<br>Stations used: 4',
                              'Modena<br>Mean pollution: 26.99 ug/m3<br>Stations used: 2',
                              'Bolzano<br>Mean pollution: 26.05 ug/m3<br>Stations used: 3',
                              'Pavia<br>Mean pollution: 25.55 ug/m3<br>Stations used: 2',
                              'Novara<br>Mean pollution: 25.26 ug/m3<br>Stations used: 2',
                              'Treviso<br>Mean pollution: 24.9 ug/m3<br>Stations used: 2',
                              'Rimini<br>Mean pollution: 24.86 ug/m3<br>Stations used: 2',
                              'Cremona<br>Mean pollution: 24.59 ug/m3<br>Stations used: 2',
                              'Verona<br>Mean pollution: 24.21 ug/m3<br>Stations used: 2',
                              'Lecco<br>Mean pollution: 23.98 ug/m3<br>Stations used: 2',
                              'Campobasso<br>Mean pollution: 23.71 ug/m3<br>Stations used: 2',
                              'Parma<br>Mean pollution: 23.65 ug/m3<br>Stations used: 2',
                              "Reggio nell'Emilia<br>Mean pollution: 23.49 ug/m3<br>Stations used: 2",
                              'Varese<br>Mean pollution: 23.25 ug/m3<br>Stations used: 2',
                              'Alessandria<br>Mean pollution: 23.09 ug/m3<br>Stations used: 2',
                              'Messina<br>Mean pollution: 22.85 ug/m3<br>Stations used: 2'],
                             dtype=object),
               'type': 'scattergeo'},
              {'hoverinfo': 'skip',
               'lat': [41.45],
               'lon': [12.75],
               'marker': {'color': '#22d3cf', 'line': {'color': '#b6fff8', 'width': 0.5}, 'opacity': 0.95, 'size': 20},
               'mode': 'markers',
               'name': 'Cities',
               'type': 'scattergeo',
               'visible': 'legendonly'}],
     'layout': {'annotations': [{'font': {'color': '#e8eef7', 'size': 64},
                                 'showarrow': False,
                                 'text': '<b>Most Polluted Cities in 2023 (NO2 Mean Pollution)</b>',
                                 'x': 0.02,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.98,
                                 'yanchor': 'top',
                                 'yref': 'paper'}],
                'font': {'color': '#e8eef7', 'family': 'Arial', 'size': 14},
                'geo': {'bgcolor': '#162036',
                        'center': {'lat': 41.45, 'lon': 12.75},
                        'coastlinecolor': 'rgba(220,235,255,0.55)',
                        'countrycolor': 'rgba(220,235,255,0.55)',
                        'domain': {'x': [0, 1], 'y': [0, 1]},
                        'landcolor': '#162a46',
                        'lataxis': {'range': [35.25, 47.65], 'showgrid': False},
                        'lonaxis': {'range': [-2.491475490621932, 27.99147549062193], 'showgrid': False},
                        'oceancolor': '#101c33',
                        'projection': {'type': 'mercator'},
                        'showcoastlines': True,
                        'showcountries': True,
                        'showframe': False,
                        'showlakes': False,
                        'showland': True,
                        'showocean': True},
                'height': 900,
                'legend': {'bgcolor': 'rgba(12, 22, 38, 0.80)',
                           'borderwidth': 0,
                           'font': {'color': '#e8eef7', 'size': 32},
                           'itemsizing': 'trace',
                           'itemwidth': 80,
                           'orientation': 'h',
                           'x': 0.02,
                           'xanchor': 'left',
                           'y': 0.04,
                           'yanchor': 'bottom'},
                'margin': {'b': 0, 'l': 0, 'r': 0, 't': 0},
                'paper_bgcolor': '#162036',
                'plot_bgcolor': '#162036',
                'template': '...'}
 }),
 'PM10': Figure({
     'data': [{'hoverinfo': 'skip',
               'lat': {'bdata': ('c9TkPHayRkA9LNSa5sVGQOoENBE2uE' ... 'aX3ZPzREAMJCh+jONFQLgehetRuEZA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('6LSBThvIJ0BLo9yQWRAnQFg5tMh2/i' ... 'p3nKIDKUCwA+eMKIUmQATFjzF3PSFA'),
                       'dtype': 'f8'},
               'marker': {'color': 'rgba(34, 211, 207, 0.30)',
                          'opacity': 0.55,
                          'size': {'bdata': ('AAAAAAAANkDpuT0GxFc0QCZpo/ZZPD' ... '056DsLGkCjYwoZIkAXQAAAAAAAABRA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'type': 'scattergeo'},
              {'hovertemplate': '<b>%{text}</b><extra></extra>',
               'lat': {'bdata': ('c9TkPHayRkA9LNSa5sVGQOoENBE2uE' ... 'aX3ZPzREAMJCh+jONFQLgehetRuEZA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('6LSBThvIJ0BLo9yQWRAnQFg5tMh2/i' ... 'p3nKIDKUCwA+eMKIUmQATFjzF3PSFA'),
                       'dtype': 'f8'},
               'marker': {'color': '#22d3cf',
                          'line': {'color': '#b6fff8', 'width': 0.5},
                          'opacity': 0.95,
                          'size': {'bdata': ('AAAAAAAANEDpuT0GxFcyQCZpo/ZZPD' ... '056DsLEkBGxxQyRIAOQAAAAAAAAAhA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'text': array(['Padova<br>Mean pollution: 32.47 ug/m3<br>Stations used: 3',
                              'Vicenza<br>Mean pollution: 31.6 ug/m3<br>Stations used: 3',
                              'Verona<br>Mean pollution: 31.54 ug/m3<br>Stations used: 2',
                              'Cremona<br>Mean pollution: 31.12 ug/m3<br>Stations used: 2',
                              'Venezia<br>Mean pollution: 30.51 ug/m3<br>Stations used: 4',
                              'Gela<br>Mean pollution: 30.35 ug/m3<br>Stations used: 2',
                              'Treviso<br>Mean pollution: 30.32 ug/m3<br>Stations used: 2',
                              'Brescia<br>Mean pollution: 29.55 ug/m3<br>Stations used: 3',
                              'Torino<br>Mean pollution: 28.82 ug/m3<br>Stations used: 4',
                              'Alessandria<br>Mean pollution: 28.52 ug/m3<br>Stations used: 2',
                              'Modena<br>Mean pollution: 28.45 ug/m3<br>Stations used: 2',
                              'Asti<br>Mean pollution: 28.27 ug/m3<br>Stations used: 2',
                              'Catania<br>Mean pollution: 27.92 ug/m3<br>Stations used: 3',
                              'Pavia<br>Mean pollution: 27.82 ug/m3<br>Stations used: 2',
                              'Milano (greater city)<br>Mean pollution: 27.4 ug/m3<br>Stations used: 8',
                              "Reggio nell'Emilia<br>Mean pollution: 26.86 ug/m3<br>Stations used: 2",
                              'Parma<br>Mean pollution: 26.72 ug/m3<br>Stations used: 2',
                              'Terni<br>Mean pollution: 25.99 ug/m3<br>Stations used: 3',
                              'Piacenza<br>Mean pollution: 25.88 ug/m3<br>Stations used: 2',
                              'Napoli (greater city)<br>Mean pollution: 25.73 ug/m3<br>Stations used: 9',
                              'Palermo<br>Mean pollution: 25.71 ug/m3<br>Stations used: 5',
                              'Rimini<br>Mean pollution: 25.53 ug/m3<br>Stations used: 2',
                              'Siracusa<br>Mean pollution: 25.27 ug/m3<br>Stations used: 3',
                              'Caserta<br>Mean pollution: 25.05 ug/m3<br>Stations used: 2',
                              'Ferrara<br>Mean pollution: 24.83 ug/m3<br>Stations used: 2',
                              'Bergamo<br>Mean pollution: 24.82 ug/m3<br>Stations used: 2',
                              'Ravenna<br>Mean pollution: 24.46 ug/m3<br>Stations used: 2',
                              'Roma<br>Mean pollution: 24.3 ug/m3<br>Stations used: 10',
                              'Firenze<br>Mean pollution: 23.93 ug/m3<br>Stations used: 4',
                              'Novara<br>Mean pollution: 23.5 ug/m3<br>Stations used: 2'],
                             dtype=object),
               'type': 'scattergeo'},
              {'hoverinfo': 'skip',
               'lat': [41.45],
               'lon': [12.75],
               'marker': {'color': '#22d3cf', 'line': {'color': '#b6fff8', 'width': 0.5}, 'opacity': 0.95, 'size': 20},
               'mode': 'markers',
               'name': 'Cities',
               'type': 'scattergeo',
               'visible': 'legendonly'}],
     'layout': {'annotations': [{'font': {'color': '#e8eef7', 'size': 64},
                                 'showarrow': False,
                                 'text': '<b>Most Polluted Cities in 2023 (PM10 Mean Pollution)</b>',
                                 'x': 0.02,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.98,
                                 'yanchor': 'top',
                                 'yref': 'paper'}],
                'font': {'color': '#e8eef7', 'family': 'Arial', 'size': 14},
                'geo': {'bgcolor': '#162036',
                        'center': {'lat': 41.45, 'lon': 12.75},
                        'coastlinecolor': 'rgba(220,235,255,0.55)',
                        'countrycolor': 'rgba(220,235,255,0.55)',
                        'domain': {'x': [0, 1], 'y': [0, 1]},
                        'landcolor': '#162a46',
                        'lataxis': {'range': [35.25, 47.65], 'showgrid': False},
                        'lonaxis': {'range': [-2.491475490621932, 27.99147549062193], 'showgrid': False},
                        'oceancolor': '#101c33',
                        'projection': {'type': 'mercator'},
                        'showcoastlines': True,
                        'showcountries': True,
                        'showframe': False,
                        'showlakes': False,
                        'showland': True,
                        'showocean': True},
                'height': 900,
                'legend': {'bgcolor': 'rgba(12, 22, 38, 0.80)',
                           'borderwidth': 0,
                           'font': {'color': '#e8eef7', 'size': 32},
                           'itemsizing': 'trace',
                           'itemwidth': 80,
                           'orientation': 'h',
                           'x': 0.02,
                           'xanchor': 'left',
                           'y': 0.04,
                           'yanchor': 'bottom'},
                'margin': {'b': 0, 'l': 0, 'r': 0, 't': 0},
                'paper_bgcolor': '#162036',
                'plot_bgcolor': '#162036',
                'template': '...'}
 }),
 'PM25': Figure({
     'data': [{'hoverinfo': 'skip',
               'lat': {'bdata': ('UrgehevFRkBAE2HD07tGQJqZmZmZkU' ... '/VVuwNRkCGp1fKMihGQLhAguLHxEVA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('AG+BBMUPJ0BLWYY41pUoQAAAAAAAEC' ... '51cRutI0C+wRcmU/UgQEqdgCbCpiRA'),
                       'dtype': 'f8'},
               'marker': {'color': 'rgba(34, 211, 207, 0.30)',
                          'opacity': 0.55,
                          'size': {'bdata': ('AAAAAAAANkD+EHW/oIwzQLY5qpusbD' ... 'NyBGQVF0AZqOwHp8gVQAAAAAAAABRA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'type': 'scattergeo'},
              {'hovertemplate': '<b>%{text}</b><extra></extra>',
               'lat': {'bdata': ('UrgehevFRkBAE2HD07tGQJqZmZmZkU' ... '/VVuwNRkCGp1fKMihGQLhAguLHxEVA'),
                       'dtype': 'f8'},
               'lon': {'bdata': ('AG+BBMUPJ0BLWYY41pUoQAAAAAAAEC' ... '51cRutI0C+wRcmU/UgQEqdgCbCpiRA'),
                       'dtype': 'f8'},
               'marker': {'color': '#22d3cf',
                          'line': {'color': '#b6fff8', 'width': 0.5},
                          'opacity': 0.95,
                          'size': {'bdata': ('AAAAAAAANED+EHW/oIwxQLY5qpusbD' ... 'flCMgqDkAyUNkPTpELQAAAAAAAAAhA'),
                                   'dtype': 'f8'}},
               'mode': 'markers',
               'showlegend': False,
               'text': array(['Vicenza<br>Mean pollution: 23.49 ug/m3<br>Stations used: 2',
                              'Venezia<br>Mean pollution: 21.4 ug/m3<br>Stations used: 2',
                              'Cremona<br>Mean pollution: 21.3 ug/m3<br>Stations used: 2',
                              'Brescia<br>Mean pollution: 18.23 ug/m3<br>Stations used: 3',
                              'Milano (greater city)<br>Mean pollution: 17.9 ug/m3<br>Stations used: 6',
                              'Torino<br>Mean pollution: 17.3 ug/m3<br>Stations used: 3',
                              'Terni<br>Mean pollution: 15.66 ug/m3<br>Stations used: 3',
                              'Napoli (greater city)<br>Mean pollution: 14.92 ug/m3<br>Stations used: 6',
                              'Ancona<br>Mean pollution: 14.55 ug/m3<br>Stations used: 2',
                              'Prato<br>Mean pollution: 13.61 ug/m3<br>Stations used: 2',
                              'Bologna<br>Mean pollution: 13.37 ug/m3<br>Stations used: 2',
                              'Palermo<br>Mean pollution: 13.13 ug/m3<br>Stations used: 3',
                              'Roma<br>Mean pollution: 12.67 ug/m3<br>Stations used: 5',
                              'Lecce<br>Mean pollution: 12.63 ug/m3<br>Stations used: 2',
                              'Firenze<br>Mean pollution: 12.52 ug/m3<br>Stations used: 2',
                              'Pescara<br>Mean pollution: 12.52 ug/m3<br>Stations used: 2',
                              'Perugia<br>Mean pollution: 12.48 ug/m3<br>Stations used: 3',
                              'Pisa<br>Mean pollution: 12.42 ug/m3<br>Stations used: 2',
                              'Bari<br>Mean pollution: 12.11 ug/m3<br>Stations used: 2',
                              'Caserta<br>Mean pollution: 10.94 ug/m3<br>Stations used: 2',
                              'Genova<br>Mean pollution: 9.83 ug/m3<br>Stations used: 4',
                              'La Spezia<br>Mean pollution: 9.65 ug/m3<br>Stations used: 4',
                              'Savona<br>Mean pollution: 9.37 ug/m3<br>Stations used: 2',
                              'Livorno<br>Mean pollution: 8.99 ug/m3<br>Stations used: 2'],
                             dtype=object),
               'type': 'scattergeo'},
              {'hoverinfo': 'skip',
               'lat': [41.45],
               'lon': [12.75],
               'marker': {'color': '#22d3cf', 'line': {'color': '#b6fff8', 'width': 0.5}, 'opacity': 0.95, 'size': 20},
               'mode': 'markers',
               'name': 'Cities',
               'type': 'scattergeo',
               'visible': 'legendonly'}],
     'layout': {'annotations': [{'font': {'color': '#e8eef7', 'size': 64},
                                 'showarrow': False,
                                 'text': '<b>Most Polluted Cities in 2023 (PM2.5 Mean Pollution)</b>',
                                 'x': 0.02,
                                 'xanchor': 'left',
                                 'xref': 'paper',
                                 'y': 0.98,
                                 'yanchor': 'top',
                                 'yref': 'paper'}],
                'font': {'color': '#e8eef7', 'family': 'Arial', 'size': 14},
                'geo': {'bgcolor': '#162036',
                        'center': {'lat': 41.45, 'lon': 12.75},
                        'coastlinecolor': 'rgba(220,235,255,0.55)',
                        'countrycolor': 'rgba(220,235,255,0.55)',
                        'domain': {'x': [0, 1], 'y': [0, 1]},
                        'landcolor': '#162a46',
                        'lataxis': {'range': [35.25, 47.65], 'showgrid': False},
                        'lonaxis': {'range': [-2.491475490621932, 27.99147549062193], 'showgrid': False},
                        'oceancolor': '#101c33',
                        'projection': {'type': 'mercator'},
                        'showcoastlines': True,
                        'showcountries': True,
                        'showframe': False,
                        'showlakes': False,
                        'showland': True,
                        'showocean': True},
                'height': 900,
                'legend': {'bgcolor': 'rgba(12, 22, 38, 0.80)',
                           'borderwidth': 0,
                           'font': {'color': '#e8eef7', 'size': 32},
                           'itemsizing': 'trace',
                           'itemwidth': 80,
                           'orientation': 'h',
                           'x': 0.02,
                           'xanchor': 'left',
                           'y': 0.04,

In [286]:
# plot a vertical bar chart visualizing per capita pollution
if "country_pollution_per_capita_2022" not in globals() or country_pollution_per_capita_2022.empty:
    country_reference_year = 2022
    fallback_path = derived_dir / f"country_population_pm25_{country_reference_year}.csv"
    if not fallback_path.exists():
        raise FileNotFoundError(
            f"Missing {fallback_path}. Run the EDA per-capita calculation block first."
        )
    fallback_df = pd.read_csv(fallback_path)
    fallback_df["PM25_Produced_Kg_per_Person"] = (
        pd.to_numeric(fallback_df["PM25_Produced_Tonnes"], errors="coerce") * 1000
        / pd.to_numeric(fallback_df["Population"], errors="coerce")
    )
    country_pollution_per_capita_2022 = fallback_df.copy()

per_capita_plot = country_pollution_per_capita_2022[["Country", "PM25_Produced_Kg_per_Person"]].copy()

per_capita_plot["PM25_Produced_Kg_per_Person"] = pd.to_numeric(
    per_capita_plot["PM25_Produced_Kg_per_Person"],
    errors="coerce",
)
per_capita_plot = per_capita_plot.dropna(subset=["PM25_Produced_Kg_per_Person"])

per_capita_plot = per_capita_plot.sort_values(
    "PM25_Produced_Kg_per_Person",
    ascending=False,
).reset_index(drop=True)

if per_capita_plot.empty:
    raise ValueError("No country rows available to plot for per-capita pollution.")

per_capita_plot_long = per_capita_plot.copy()
per_capita_plot_long["Metric"] = "PM2.5 Produced (kg/person)"

pm25_per_capita_bar_fig = create_horizontal_barchart(
    data=per_capita_plot_long,
    category_col="Country",
    value_col="PM25_Produced_Kg_per_Person",
    title="PM2.5 Pollution Per Capita (2022)",
    xaxis_title="M2.5 Produced (kg/person)",
    style_config=bar_chart_style,
)

graph_png_path = graphs_dir / "pollution_per_capita_countries_barchart_2022.png"
await save_plotly_graph_png(pm25_per_capita_bar_fig, graph_png_path, width=800, height=1000, scale=2)
print(f"Saved PNG graph to: {graph_png_path}")

display(pm25_per_capita_bar_fig)
per_capita_plot

Saved PNG graph to: Assets/Graphs/pollution_per_capita_countries_barchart_2022.png
Saved PNG graph to: Assets/Graphs/pollution_per_capita_countries_barchart_2022.png

          Country  PM25_Produced_Kg_per_Person
0          France                     5.768292
1           Italy                     5.457413
2           Spain                     4.402605
3         Germany                     2.846178
4  United Kingdom                     1.821445

## TEST

In [287]:
# TEST 1/5 - Load and validate derived data for station heatmaps
# Goal: build Italy pollutant heatmaps using stations only.

# Local fallbacks so TEST can run even if earlier setup cells were skipped.
if "derived_dir" not in globals():
    derived_dir = Path("Data/Derived")
if "graphs_dir" not in globals():
    graphs_dir = Path("Assets/Graphs")

heatmap_source_dir = derived_dir
heatmap_export_dir = graphs_dir
heatmap_export_dir.mkdir(parents=True, exist_ok=True)

heatmap_pollutants = ["NO2", "O3", "PM10", "PM2.5"]
heatmap_min_coverage = 75

# Composite export sizing/tuning knobs (easy to tweak)
heat_output_width = 1600
heat_output_height = 1000
heat_frame_aspect = heat_output_width / heat_output_height

heat_radius = 20
heat_quantile_low = 0.02
heat_quantile_high = 0.96
heat_intensity_gamma = 0.90
heat_layer_opacity = 0.95

# Pollution colorscale (low -> high). Edit these to change heat colors.
# Current palette: cyan -> blue-violet -> magenta -> red
heat_colorscale = [
    [0.00, "#00EFFF"],
    [0.35, "#2F7BFF"],
    [0.68, "#C12BFF"],
    [1.00, "#FF2A3D"],
]

heat_white_threshold = 228
heat_alpha_scale = .85
heat_brightness_gain = .85

# Final overlay transform knobs (manual fallback only if auto alignment fails)
# - Shift: positive x => right, negative y => up
# - Scale: 1.0 means unchanged; tweak slightly (e.g., 0.98 or 1.02)
heat_overlay_shift_x_px = 0
heat_overlay_shift_y_px = 0
heat_overlay_scale_x = 1.0
heat_overlay_scale_y = 1.0
heat_auto_align_overlay = True
heat_auto_align_marker_size = 22
heat_auto_align_color_tolerance = 45
heat_export_show_colorbar = False

heat_lat_pad = 1.0
heat_lon_pad = 1.2

# Keep one fixed map frame across pollutants so the background does not move
heat_use_global_frame = True

heatmap_cols = [
    "Country",
    "Year",
    "Air Pollutant",
    "Data Aggregation Process",
    "Unit Of Air Pollution Level",
    "Data Coverage",
    "Air Quality Station EoI Code",
    "Air Quality Station Name",
    "Air Quality Station Area",
    "Latitude",
    "Longitude",
    "Air Pollution Level",
]

heatmap_paths = sorted(heatmap_source_dir.glob("*_IT_derived.csv"))
if not heatmap_paths:
    raise FileNotFoundError(f"No derived files found under {heatmap_source_dir}")

heatmap_parts = []
for path in heatmap_paths:
    part = pd.read_csv(path)
    missing_cols = [col for col in heatmap_cols if col not in part.columns]
    if missing_cols:
        raise ValueError(f"{path.name} is missing required columns: {missing_cols}")
    heatmap_parts.append(part[heatmap_cols].copy())

heatmap_source = pd.concat(heatmap_parts, ignore_index=True)

heatmap_source["Country"] = heatmap_source["Country"].astype(str).str.strip()
heatmap_source = heatmap_source[heatmap_source["Country"].eq("Italy")].copy()

available_years = sorted(pd.to_numeric(heatmap_source["Year"], errors="coerce").dropna().astype(int).unique().tolist())
if not available_years:
    raise ValueError("No valid years found in derived data.")

heatmap_year = max(available_years)

agg_process_values = sorted(
    heatmap_source["Data Aggregation Process"].dropna().astype(str).str.strip().unique().tolist()
)

print(f"Loaded files: {len(heatmap_paths)}")
print(f"Available years: {available_years}")
print(f"Selected heatmap year: {heatmap_year}")
print(f"Aggregation process values in derived data: {agg_process_values}")
print(
    "Heat tuning -> "
    f"radius={heat_radius}, q=({heat_quantile_low:.2f},{heat_quantile_high:.2f}), "
    f"gamma={heat_intensity_gamma:.2f}, opacity={heat_layer_opacity:.2f}, "
    f"shift=({heat_overlay_shift_x_px},{heat_overlay_shift_y_px}) px, "
    f"scale=({heat_overlay_scale_x:.3f},{heat_overlay_scale_y:.3f}), "
    f"auto_align={heat_auto_align_overlay}, colorbar={heat_export_show_colorbar}, "
    f"brightness={heat_brightness_gain:.2f}"
)
print(f"Heat colorscale stops: {len(heat_colorscale)}")

Loaded files: 8
Available years: [2023, 2024]
Selected heatmap year: 2024
Aggregation process values in derived data: ['Annual mean / 1 calendar year']
Heat tuning -> radius=20, q=(0.02,0.96), gamma=0.90, opacity=0.95, shift=(0,0) px, scale=(1.000,1.000), auto_align=True, colorbar=False, brightness=0.85
Heat colorscale stops: 4

In [288]:
# TEST 2/5 - Filter to heatmap-ready station observations

heatmap_filtered = heatmap_source.copy()

heatmap_filtered["Unit Of Air Pollution Level"] = (
    heatmap_filtered["Unit Of Air Pollution Level"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace("µ", "u", regex=False)
    .str.replace("μ", "u", regex=False)
    .str.replace("³", "3", regex=False)
    .str.replace(" ", "", regex=False)
)

heatmap_filtered = heatmap_filtered[
    heatmap_filtered["Unit Of Air Pollution Level"].isin({"ug/m3", "ug/m^3"})
].copy()

heatmap_filtered["Year"] = pd.to_numeric(heatmap_filtered["Year"], errors="coerce")
heatmap_filtered = heatmap_filtered[heatmap_filtered["Year"].eq(heatmap_year)].copy()

heatmap_filtered["Data Coverage"] = pd.to_numeric(heatmap_filtered["Data Coverage"], errors="coerce")
coverage_values = heatmap_filtered["Data Coverage"].copy()
if not coverage_values.dropna().empty and coverage_values.dropna().max() <= 1:
    coverage_values = coverage_values * 100
heatmap_filtered = heatmap_filtered[coverage_values >= heatmap_min_coverage].copy()

heatmap_filtered["Air Pollution Level"] = pd.to_numeric(heatmap_filtered["Air Pollution Level"], errors="coerce")
heatmap_filtered["Latitude"] = pd.to_numeric(heatmap_filtered["Latitude"], errors="coerce")
heatmap_filtered["Longitude"] = pd.to_numeric(heatmap_filtered["Longitude"], errors="coerce")
heatmap_filtered = heatmap_filtered.dropna(
    subset=["Air Pollution Level", "Latitude", "Longitude", "Air Quality Station EoI Code"]
)

heatmap_filtered["Pollutant"] = (
    heatmap_filtered["Air Pollutant"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)
heatmap_filtered.loc[heatmap_filtered["Pollutant"].isin({"PM2.5", "PM25"}), "Pollutant"] = "PM2.5"

station_pollutant_year = (
    heatmap_filtered
    .groupby(["Year", "Pollutant", "Air Quality Station EoI Code"], as_index=False)
    .agg(
        Air_Pollution_Level=("Air Pollution Level", "mean"),
        Latitude=("Latitude", "mean"),
        Longitude=("Longitude", "mean"),
        Station_Name=("Air Quality Station Name", "first"),
        Station_Area=("Air Quality Station Area", "first"),
    )
)

station_pollutant_year = station_pollutant_year[
    station_pollutant_year["Pollutant"].isin(heatmap_pollutants)
].copy()

station_points_by_pollutant = {
    pollutant: station_pollutant_year[station_pollutant_year["Pollutant"].eq(pollutant)].copy()
    for pollutant in heatmap_pollutants
}

for pollutant, dfp in station_points_by_pollutant.items():
    print(f"{pollutant}: stations={dfp['Air Quality Station EoI Code'].nunique()} rows={len(dfp)}")

# Build a shared frame dataset so all pollutant images use identical map bounds.
all_station_points = pd.concat(station_points_by_pollutant.values(), ignore_index=True)
shared_frame_points = all_station_points[["Latitude", "Longitude"]].copy()
shared_frame_points["Latitude"] = pd.to_numeric(shared_frame_points["Latitude"], errors="coerce")
shared_frame_points["Longitude"] = pd.to_numeric(shared_frame_points["Longitude"], errors="coerce")
shared_frame_points = shared_frame_points.dropna(subset=["Latitude", "Longitude"]).reset_index(drop=True)

if shared_frame_points.empty:
    raise ValueError("Shared map frame cannot be computed because no valid station coordinates are available.")

NO2: stations=616 rows=616
O3: stations=340 rows=340
PM10: stations=562 rows=562
PM2.5: stations=324 rows=324

In [289]:
# TEST 3/5 - Figure builders for composite heatmap workflow


def compute_map_frame_params(data, frame_aspect=1.6, lat_pad=1.0, lon_pad=1.2):
    if data.empty:
        raise ValueError("Cannot compute map frame for an empty dataset.")

    lat_min = float(data["Latitude"].min()) - float(lat_pad)
    lat_max = float(data["Latitude"].max()) + float(lat_pad)
    lon_min = float(data["Longitude"].min()) - float(lon_pad)
    lon_max = float(data["Longitude"].max()) + float(lon_pad)

    # Match geo-frame aspect like the dot-map helper to avoid squashed/narrow map output.
    import math

    lat_min_clip = max(-85.0, min(85.0, lat_min))
    lat_max_clip = max(-85.0, min(85.0, lat_max))
    y_min = math.log(math.tan(math.pi / 4 + math.radians(lat_min_clip) / 2))
    y_max = math.log(math.tan(math.pi / 4 + math.radians(lat_max_clip) / 2))

    current_lon_span = lon_max - lon_min
    required_lon_span = math.degrees((y_max - y_min) * float(frame_aspect))
    if required_lon_span > current_lon_span:
        extra = (required_lon_span - current_lon_span) / 2
        lon_min -= extra
        lon_max += extra

    center_lat = (lat_min + lat_max) / 2
    center_lon = (lon_min + lon_max) / 2

    span = max(lat_max - lat_min, lon_max - lon_min)
    if span > 18:
        zoom = 4.1
    elif span > 12:
        zoom = 4.4
    else:
        zoom = 4.8

    return {
        "lat_min": lat_min,
        "lat_max": lat_max,
        "lon_min": lon_min,
        "lon_max": lon_max,
        "center_lat": center_lat,
        "center_lon": center_lon,
        "zoom": zoom,
    }


def create_heat_only_density_figure(
    data,
    pollutant,
    year,
    map_frame,
    radius=34,
    quantile_low=0.03,
    quantile_high=0.98,
    intensity_gamma=0.90,
    heat_opacity=0.86,
    heat_colorscale=None,
    show_colorbar=False,
    style_config=None,
):
    if data.empty:
        raise ValueError(f"No station data available for {pollutant} in {year}.")

    base_style = {}
    if "CHART_STYLE_PRESETS" in globals() and isinstance(CHART_STYLE_PRESETS, dict):
        base_style = CHART_STYLE_PRESETS.get("map", {}) or {}
    style = {**base_style, **(style_config or {})}

    if heat_colorscale is None:
        colorscale = [
            [0.00, "#00EFFF"],
            [0.35, "#2F7BFF"],
            [0.68, "#C12BFF"],
            [1.00, "#FF2A3D"],
        ]
    else:
        colorscale = heat_colorscale

    z_raw = pd.to_numeric(data["Air_Pollution_Level"], errors="coerce")
    z_values = z_raw.dropna().to_numpy(dtype=float)
    if z_values.size == 0:
        raise ValueError(f"No valid pollution values available for {pollutant} ({year}).")

    q_low = float(np.clip(quantile_low, 0.0, 1.0))
    q_high = float(np.clip(quantile_high, 0.0, 1.0))
    if q_high <= q_low:
        q_low, q_high = 0.0, 1.0

    zmin = float(np.quantile(z_values, q_low))
    zmax = float(np.quantile(z_values, q_high))
    if zmax <= zmin:
        zmin = float(np.min(z_values))
        zmax = float(np.max(z_values))
        if zmax <= zmin:
            zmax = zmin + 1e-6

    z_norm = ((z_raw - zmin) / (zmax - zmin)).clip(lower=0, upper=1)
    z_scaled = zmin + (z_norm ** float(max(0.1, intensity_gamma))) * (zmax - zmin)

    fig = go.Figure()

    colorbar_config = None
    if bool(show_colorbar):
        colorbar_config = dict(
            title=dict(
                text=f"{pollutant} (ug/m3)",
                font=dict(color=style.get("font_color", "#e8eef7")),
            ),
            bgcolor="rgba(0,0,0,0)",
            x=0.96,
            y=0.5,
            len=0.72,
            tickfont=dict(color=style.get("font_color", "#e8eef7")),
        )

    fig.add_trace(
        go.Densitymapbox(
            lat=data["Latitude"],
            lon=data["Longitude"],
            z=z_scaled,
            zmin=zmin,
            zmax=zmax,
            radius=int(max(8, radius)),
            colorscale=colorscale,
            colorbar=colorbar_config,
            hovertemplate=(
                f"{pollutant} station influence" + "<br>Lat: %{lat:.3f}<br>Lon: %{lon:.3f}<extra></extra>"
            ),
            showscale=bool(show_colorbar),
            opacity=float(np.clip(heat_opacity, 0.05, 1.0)),
            name=f"{pollutant} heat",
        )
    )

    # White tile canvas allows clean chroma-key to transparent after export.
    fig.update_layout(
        mapbox=dict(
            style="white-bg",
            bounds=dict(
                west=map_frame["lon_min"],
                east=map_frame["lon_max"],
                south=map_frame["lat_min"],
                north=map_frame["lat_max"],
            ),
        ),
        paper_bgcolor="white",
        plot_bgcolor="white",
        font=dict(color=style.get("font_color", "#e8eef7"), family="Arial", size=14),
        margin=dict(l=0, r=0, t=0, b=0),
        height=1000,
        showlegend=False,
    )

    return fig


def create_styled_geo_base_map_figure(
    pollutant,
    year,
    map_frame,
    style_config=None,
):
    base_style = {}
    if "CHART_STYLE_PRESETS" in globals() and isinstance(CHART_STYLE_PRESETS, dict):
        base_style = CHART_STYLE_PRESETS.get("map", {}) or {}
    style = {**base_style, **(style_config or {})}

    if heat_colorscale is None:
        colorscale = [
            [0.00, "#00EFFF"],
            [0.35, "#2F7BFF"],
            [0.68, "#C12BFF"],
            [1.00, "#FF2A3D"],
        ]
    else:
        colorscale = heat_colorscale

    title_font_size = int(min(float(style.get("title_font_size", 44)), 52))

    fig = go.Figure()

    # Invisible anchor trace to instantiate the geo subplot.
    fig.add_trace(
        go.Scattergeo(
            lat=[map_frame["center_lat"]],
            lon=[map_frame["center_lon"]],
            mode="markers",
            marker=dict(size=1, opacity=0),
            hoverinfo="skip",
            showlegend=False,
        )
    )

    fig.update_layout(
        annotations=[
            dict(
                x=0.02,
                y=float(style.get("title_y", 0.98)),
                xref="paper",
                yref="paper",
                xanchor="left",
                yanchor="top",
                text=f"<b>Italy Air Pollution Heatmap - {pollutant} ({year})</b>",
                showarrow=False,
                font=dict(size=title_font_size, color=style.get("font_color", "#e8eef7")),
            )
        ],
        paper_bgcolor=style.get("paper_bgcolor", "#162036"),
        plot_bgcolor=style.get("paper_bgcolor", "#162036"),
        font=dict(color=style.get("font_color", "#e8eef7"), family="Arial", size=14),
        margin=dict(l=0, r=0, t=0, b=0),
        height=1000,
        geo=dict(
            projection_type="mercator",
            center=dict(lat=map_frame["center_lat"], lon=map_frame["center_lon"]),
            showcountries=True,
            countrycolor=style.get("country_border_color", "rgba(220,235,255,0.55)"),
            showcoastlines=True,
            coastlinecolor=style.get("coastline_color", "rgba(220,235,255,0.55)"),
            showland=True,
            landcolor=style.get("land_color", "#162a46"),
            showocean=True,
            oceancolor=style.get("ocean_color", "#101c33"),
            showlakes=True,
            lakecolor=style.get("ocean_color", "#101c33"),
            showframe=False,
            domain=dict(x=[0, 1], y=[0, 1]),
            bgcolor=style.get("paper_bgcolor", "#162036"),
            lataxis=dict(range=[map_frame["lat_min"], map_frame["lat_max"]], showgrid=False),
            lonaxis=dict(range=[map_frame["lon_min"], map_frame["lon_max"]], showgrid=False),
        ),
    )

    return fig

In [290]:
# TEST 4/5 - Generate composite PNG per pollutant (heat-only layer + styled geo base)

import asyncio
import threading
import tempfile
from PIL import Image

station_heatmap_figs = {}
station_heatmap_station_tables = {}
png_export_errors = {}


def run_coroutine_safely(coro):
    """Run an async coroutine from sync code, even if an event loop is already active."""
    result_box = {"value": None}
    error_box = {"error": None}

    def _runner():
        try:
            result_box["value"] = asyncio.run(coro)
        except Exception as exc:
            error_box["error"] = exc

    thread = threading.Thread(target=_runner, daemon=True)
    thread.start()
    thread.join()

    if error_box["error"] is not None:
        raise error_box["error"]

    return result_box["value"]


def save_plot_png_sync(fig, output_path, width=1600, height=1000, scale=2):
    if "save_plotly_graph_png" not in globals():
        raise RuntimeError(
            "save_plotly_graph_png is not available. Run the plotting helper cell that defines it before TEST exports."
        )

    save_fn = save_plotly_graph_png
    if asyncio.iscoroutinefunction(save_fn):
        run_coroutine_safely(
            save_fn(fig, output_path, width=width, height=height, scale=scale, force_canvas_size=True)
        )
    else:
        save_fn(fig, output_path, width=width, height=height, scale=scale, force_canvas_size=True)


def white_to_transparent(src_png, dst_png, white_threshold=228, alpha_scale=1.05, brightness_gain=1.20):
    """Turn near-white pixels transparent so only heat remains."""
    image = Image.open(src_png).convert("RGBA")
    arr = np.array(image, dtype=np.uint8)

    rgb = arr[:, :, :3]
    alpha = arr[:, :, 3].astype(np.float32)

    white_mask = (
        (rgb[:, :, 0] >= white_threshold)
        & (rgb[:, :, 1] >= white_threshold)
        & (rgb[:, :, 2] >= white_threshold)
    )

    alpha[white_mask] = 0
    non_white = ~white_mask
    alpha[non_white] = np.clip(alpha[non_white] * float(alpha_scale), 0, 255)

    rgb_float = rgb.astype(np.float32)
    rgb_float[non_white] = np.clip(rgb_float[non_white] * float(brightness_gain), 0, 255)

    arr[:, :, :3] = rgb_float.astype(np.uint8)
    arr[:, :, 3] = alpha.astype(np.uint8)
    Image.fromarray(arr, mode="RGBA").save(dst_png)


def extract_color_marker_centroids(image_path, marker_colors, tolerance=45, min_pixels=30):
    arr = np.array(Image.open(image_path).convert("RGB"), dtype=np.int16)
    centroids = {}

    for idx, (r, g, b) in enumerate(marker_colors):
        target = np.array([r, g, b], dtype=np.int16)
        mask = np.max(np.abs(arr - target), axis=2) <= int(tolerance)
        ys, xs = np.where(mask)
        if xs.size < int(min_pixels):
            continue
        centroids[idx] = (float(xs.mean()), float(ys.mean()))

    return centroids


def estimate_overlay_transform_for_map_frame(map_frame, width, height, scale=2):
    marker_colors = [
        (255, 0, 0),
        (0, 200, 0),
        (0, 120, 255),
        (255, 165, 0),
        (180, 0, 255),
    ]

    lat_span = float(map_frame["lat_max"] - map_frame["lat_min"])
    lon_span = float(map_frame["lon_max"] - map_frame["lon_min"])
    lat_pad = max(0.6, lat_span * 0.08)
    lon_pad = max(0.6, lon_span * 0.08)

    probe_points = [
        (map_frame["lat_max"] - lat_pad, map_frame["lon_min"] + lon_pad),
        (map_frame["lat_max"] - lat_pad, map_frame["lon_max"] - lon_pad),
        ((map_frame["lat_min"] + map_frame["lat_max"]) / 2, (map_frame["lon_min"] + map_frame["lon_max"]) / 2),
        (map_frame["lat_min"] + lat_pad, map_frame["lon_min"] + lon_pad),
        (map_frame["lat_min"] + lat_pad, map_frame["lon_max"] - lon_pad),
    ]

    marker_size = int(max(10, globals().get("heat_auto_align_marker_size", 22)))

    heat_probe_fig = go.Figure()
    for (lat, lon), (r, g, b) in zip(probe_points, marker_colors):
        heat_probe_fig.add_trace(
            go.Scattermapbox(
                lat=[lat],
                lon=[lon],
                mode="markers",
                marker=dict(size=marker_size, color=f"rgb({r},{g},{b})", opacity=1.0),
                hoverinfo="skip",
                showlegend=False,
            )
        )

    heat_probe_fig.update_layout(
        mapbox=dict(
            style="white-bg",
            bounds=dict(
                west=map_frame["lon_min"],
                east=map_frame["lon_max"],
                south=map_frame["lat_min"],
                north=map_frame["lat_max"],
            ),
        ),
        paper_bgcolor="white",
        plot_bgcolor="white",
        margin=dict(l=0, r=0, t=0, b=0),
        height=height,
        showlegend=False,
    )

    base_probe_fig = go.Figure()
    for (lat, lon), (r, g, b) in zip(probe_points, marker_colors):
        base_probe_fig.add_trace(
            go.Scattergeo(
                lat=[lat],
                lon=[lon],
                mode="markers",
                marker=dict(size=marker_size, color=f"rgb({r},{g},{b})", opacity=1.0),
                hoverinfo="skip",
                showlegend=False,
            )
        )

    base_probe_fig.update_layout(
        paper_bgcolor="white",
        plot_bgcolor="white",
        margin=dict(l=0, r=0, t=0, b=0),
        height=height,
        showlegend=False,
        geo=dict(
            projection_type="mercator",
            center=dict(lat=map_frame["center_lat"], lon=map_frame["center_lon"]),
            showframe=False,
            showcountries=False,
            showcoastlines=False,
            showland=False,
            showocean=False,
            showlakes=False,
            domain=dict(x=[0, 1], y=[0, 1]),
            bgcolor="white",
            lataxis=dict(range=[map_frame["lat_min"], map_frame["lat_max"]], showgrid=False),
            lonaxis=dict(range=[map_frame["lon_min"], map_frame["lon_max"]], showgrid=False),
        ),
    )

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_dir = Path(tmp_dir)
        heat_probe_png = tmp_dir / "heat_probe.png"
        base_probe_png = tmp_dir / "base_probe.png"

        save_plot_png_sync(heat_probe_fig, heat_probe_png, width=width, height=height, scale=scale)
        save_plot_png_sync(base_probe_fig, base_probe_png, width=width, height=height, scale=scale)

        tolerance = int(globals().get("heat_auto_align_color_tolerance", 45))
        min_pixels = max(20, marker_size)

        heat_centroids = extract_color_marker_centroids(
            heat_probe_png,
            marker_colors,
            tolerance=tolerance,
            min_pixels=min_pixels,
        )
        base_centroids = extract_color_marker_centroids(
            base_probe_png,
            marker_colors,
            tolerance=tolerance,
            min_pixels=min_pixels,
        )

        with Image.open(heat_probe_png) as probe_img:
            sample_w, sample_h = probe_img.size

    matched_ids = sorted(set(heat_centroids).intersection(base_centroids))
    if len(matched_ids) < 3:
        raise RuntimeError(f"Overlay auto-alignment needs >=3 marker matches; got {len(matched_ids)}")

    heat_x = np.array([heat_centroids[idx][0] for idx in matched_ids], dtype=float)
    heat_y = np.array([heat_centroids[idx][1] for idx in matched_ids], dtype=float)
    base_x = np.array([base_centroids[idx][0] for idx in matched_ids], dtype=float)
    base_y = np.array([base_centroids[idx][1] for idx in matched_ids], dtype=float)

    scale_x, intercept_x = np.polyfit(heat_x, base_x, 1)
    scale_y, intercept_y = np.polyfit(heat_y, base_y, 1)

    scale_x = float(np.clip(scale_x, 0.5, 1.5))
    scale_y = float(np.clip(scale_y, 0.5, 1.5))

    shift_x = float(intercept_x - sample_w * (1 - scale_x) / 2)
    shift_y = float(intercept_y - sample_h * (1 - scale_y) / 2)

    residual_x = base_x - (heat_x * scale_x + intercept_x)
    residual_y = base_y - (heat_y * scale_y + intercept_y)

    return {
        "scale_x": scale_x,
        "scale_y": scale_y,
        "shift_x_px": shift_x,
        "shift_y_px": shift_y,
        "calibration_width_px": int(sample_w),
        "calibration_height_px": int(sample_h),
        "matched_markers": int(len(matched_ids)),
        "rmse_px": float(np.sqrt(np.mean(residual_x ** 2 + residual_y ** 2))),
    }


global_map_frame = None
if globals().get("heat_use_global_frame", True):
    global_map_frame = compute_map_frame_params(
        shared_frame_points,
        frame_aspect=heat_frame_aspect,
        lat_pad=heat_lat_pad,
        lon_pad=heat_lon_pad,
    )

overlay_transform = {
    "scale_x": float(globals().get("heat_overlay_scale_x", 1.0)),
    "scale_y": float(globals().get("heat_overlay_scale_y", 1.0)),
    "shift_x_px": float(globals().get("heat_overlay_shift_x_px", 0)),
    "shift_y_px": float(globals().get("heat_overlay_shift_y_px", 0)),
    "calibration_width_px": int(heat_output_width * 2),
    "calibration_height_px": int(heat_output_height * 2),
    "matched_markers": 0,
    "rmse_px": float("nan"),
}
overlay_transform["scale_x"] = float(np.clip(overlay_transform["scale_x"], 0.5, 1.5))
overlay_transform["scale_y"] = float(np.clip(overlay_transform["scale_y"], 0.5, 1.5))

if globals().get("heat_auto_align_overlay", True):
    calibration_map_frame = global_map_frame
    if calibration_map_frame is None:
        calibration_map_frame = compute_map_frame_params(
            shared_frame_points,
            frame_aspect=heat_frame_aspect,
            lat_pad=heat_lat_pad,
            lon_pad=heat_lon_pad,
        )

    try:
        overlay_transform = estimate_overlay_transform_for_map_frame(
            calibration_map_frame,
            width=heat_output_width,
            height=heat_output_height,
            scale=2,
        )
        print(
            "Auto overlay transform -> "
            f"scale=({overlay_transform['scale_x']:.4f},{overlay_transform['scale_y']:.4f}), "
            f"shift=({overlay_transform['shift_x_px']:.1f},{overlay_transform['shift_y_px']:.1f}) px, "
            f"markers={overlay_transform['matched_markers']}, rmse={overlay_transform['rmse_px']:.2f}px"
        )
    except Exception as alignment_error:
        print(
            "Auto overlay transform failed; using manual fallback -> "
            f"{alignment_error}"
        )
else:
    print(
        "Auto overlay transform disabled; using manual fallback -> "
        f"scale=({overlay_transform['scale_x']:.4f},{overlay_transform['scale_y']:.4f}), "
        f"shift=({overlay_transform['shift_x_px']:.1f},{overlay_transform['shift_y_px']:.1f}) px"
    )

for pollutant in heatmap_pollutants:
    pollutant_points = station_points_by_pollutant.get(pollutant, pd.DataFrame()).copy()
    if pollutant_points.empty:
        print(f"Skipping {pollutant}: no station points available.")
        continue

    pollutant_points = pollutant_points.sort_values("Air_Pollution_Level", ascending=False).reset_index(drop=True)
    station_heatmap_station_tables[pollutant] = pollutant_points.copy()

    map_frame = global_map_frame
    if map_frame is None:
        map_frame = compute_map_frame_params(
            pollutant_points,
            frame_aspect=heat_frame_aspect,
            lat_pad=heat_lat_pad,
            lon_pad=heat_lon_pad,
        )

    heat_fig = create_heat_only_density_figure(
        data=pollutant_points,
        pollutant=pollutant,
        year=heatmap_year,
        map_frame=map_frame,
        radius=heat_radius,
        quantile_low=heat_quantile_low,
        quantile_high=heat_quantile_high,
        intensity_gamma=heat_intensity_gamma,
        heat_opacity=heat_layer_opacity,
        heat_colorscale=heat_colorscale,
        show_colorbar=heat_export_show_colorbar,
        style_config=dot_distribution_map_style if "dot_distribution_map_style" in globals() else None,
    )

    base_fig = create_styled_geo_base_map_figure(
        pollutant=pollutant,
        year=heatmap_year,
        map_frame=map_frame,
        style_config=dot_distribution_map_style if "dot_distribution_map_style" in globals() else None,
    )

    station_heatmap_figs[pollutant] = {
        "heat_layer": heat_fig,
        "base_map": base_fig,
    }

    pollutant_safe = pollutant.lower().replace(".", "")
    final_png_path = heatmap_export_dir / f"italy_station_heatmap_{pollutant_safe}_{heatmap_year}.png"

    try:
        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_dir = Path(tmp_dir)
            base_png = tmp_dir / "base.png"
            heat_raw_png = tmp_dir / "heat_raw.png"
            heat_alpha_png = tmp_dir / "heat_alpha.png"

            save_plot_png_sync(base_fig, base_png, width=heat_output_width, height=heat_output_height, scale=2)
            save_plot_png_sync(heat_fig, heat_raw_png, width=heat_output_width, height=heat_output_height, scale=2)

            white_to_transparent(
                heat_raw_png,
                heat_alpha_png,
                white_threshold=heat_white_threshold,
                alpha_scale=heat_alpha_scale,
                brightness_gain=heat_brightness_gain,
            )

            base_image = Image.open(base_png).convert("RGBA")
            heat_image = Image.open(heat_alpha_png).convert("RGBA")

            base_w, base_h = base_image.size
            if heat_image.size != base_image.size:
                heat_image = heat_image.resize(base_image.size, resample=Image.Resampling.BICUBIC)

            # Apply the run-level overlay transform (auto-calibrated by default).
            scale_x = float(np.clip(overlay_transform.get("scale_x", 1.0), 0.5, 1.5))
            scale_y = float(np.clip(overlay_transform.get("scale_y", 1.0), 0.5, 1.5))

            transformed_heat = heat_image
            if abs(scale_x - 1.0) > 1e-6 or abs(scale_y - 1.0) > 1e-6:
                new_w = max(1, int(round(base_w * scale_x)))
                new_h = max(1, int(round(base_h * scale_y)))
                transformed_heat = heat_image.resize((new_w, new_h), resample=Image.Resampling.BICUBIC)

            shift_x = float(overlay_transform.get("shift_x_px", 0.0))
            shift_y = float(overlay_transform.get("shift_y_px", 0.0))
            calibration_w = int(max(1, overlay_transform.get("calibration_width_px", base_w)))
            calibration_h = int(max(1, overlay_transform.get("calibration_height_px", base_h)))
            if calibration_w != base_w:
                shift_x *= float(base_w) / float(calibration_w)
            if calibration_h != base_h:
                shift_y *= float(base_h) / float(calibration_h)
            shift_x = int(round(shift_x))
            shift_y = int(round(shift_y))

            aligned_heat = Image.new("RGBA", base_image.size, (0, 0, 0, 0))
            paste_x = (base_w - transformed_heat.size[0]) // 2 + shift_x
            paste_y = (base_h - transformed_heat.size[1]) // 2 + shift_y
            aligned_heat.paste(transformed_heat, (paste_x, paste_y), transformed_heat)

            final_image = Image.alpha_composite(base_image, aligned_heat)
            final_image.save(final_png_path)

        print(f"Saved composite PNG for {pollutant}: {final_png_path.name}")

        if "display" in globals():
            try:
                from IPython.display import Image as IPImage
                display(IPImage(filename=str(final_png_path)))
            except Exception:
                pass

    except Exception as export_error:
        png_export_errors[pollutant] = str(export_error)
        print(f"Composite export failed for {pollutant}: {export_error}")

/var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/ipykernel_1833/3385369542.py:117: DeprecationWarning: *scattermapbox* is deprecated! Use *scattermap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  go.Scattermapbox(

Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp47qoyj9m/heat_probe.png
Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp47qoyj9m/base_probe.png
Auto overlay transform -> scale=(0.9956,0.9956), shift=(-0.0,-50.7) px, markers=5, rmse=0.05px

/var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/ipykernel_1833/3218261995.py:120: DeprecationWarning: *densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  go.Densitymapbox(

Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp7utv6wbu/base.png
Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp7utv6wbu/heat_raw.png
Saved composite PNG for NO2: italy_station_heatmap_no2_2024.png

/var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/ipykernel_1833/3218261995.py:120: DeprecationWarning: *densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  go.Densitymapbox(

Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp_g3ass1p/base.png
Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmp_g3ass1p/heat_raw.png
Saved composite PNG for O3: italy_station_heatmap_o3_2024.png

/var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/ipykernel_1833/3218261995.py:120: DeprecationWarning: *densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  go.Densitymapbox(

Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmpm8mz76v8/base.png
Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmpm8mz76v8/heat_raw.png
Saved composite PNG for PM10: italy_station_heatmap_pm10_2024.png

/var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/ipykernel_1833/3218261995.py:120: DeprecationWarning: *densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  go.Densitymapbox(

Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmpyvbpfa5u/base.png
Saved PNG graph to: /var/folders/wt/0gmd6bld53j9fst_0yrqbhn80000gn/T/tmpyvbpfa5u/heat_raw.png
Saved composite PNG for PM2.5: italy_station_heatmap_pm25_2024.png

In [291]:
# TEST 5/5 - QA summary for generated heatmaps

if not station_heatmap_station_tables:
    raise ValueError("No pollutant heatmap outputs were generated.")

heatmap_summary_rows = []
for pollutant, dfp in station_heatmap_station_tables.items():
    heatmap_summary_rows.append({
        "Year": int(heatmap_year),
        "Pollutant": pollutant,
        "Stations": int(dfp["Air Quality Station EoI Code"].nunique()),
        "Min (ug/m3)": float(dfp["Air_Pollution_Level"].min()),
        "Mean (ug/m3)": float(dfp["Air_Pollution_Level"].mean()),
        "Max (ug/m3)": float(dfp["Air_Pollution_Level"].max()),
    })

station_heatmap_summary = pd.DataFrame(heatmap_summary_rows).sort_values("Pollutant").reset_index(drop=True)

print("Heatmap QA summary")
if "display" in globals():
    display(station_heatmap_summary)
else:
    print(station_heatmap_summary)

if "png_export_errors" in globals() and png_export_errors:
    print("\nPNG export warnings")
    for pollutant, message in png_export_errors.items():
        print(f"- {pollutant}: {message}")

Heatmap QA summary
   Year Pollutant  Stations  Min (ug/m3)  Mean (ug/m3)  Max (ug/m3)
0  2024       NO2       616        0.681     17.104794       52.923
1  2024        O3       340       30.600     55.792756       97.323
2  2024      PM10       562        9.164     22.400594       46.787
3  2024     PM2.5       324        2.981     12.945133       24.717